window.__ModuleLoader__.load({
  id: "dsh-better-sidebar",
  factory: (require) => {
    const module = { exports: {} };
    const exports = module.exports;
    const React = require("react");
    const inject = ["slots"];
    const ID = "dsh-better-sidebar";
    const states = new Map();
    const listeners = new Set();
    const defaults = { open: false, width: 470, tab: "explorer", dir: "", file: "", siteToken: "" };
    const css = `
.dbs-launch{display:grid;place-items:center;width:28px;height:28px;padding:0;border:0;border-radius:8px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}.dbs-launch:hover,.dbs-launch[data-open=true]{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}
.dbs-panel{position:fixed;z-index:72;right:12px;top:64px;bottom:76px;width:min(var(--dbs-width),calc(100vw - 24px));min-width:340px;display:flex;flex-direction:column;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;background:var(--dsw-alias-bg-base);box-shadow:var(--dsw-shadow-lv3);overflow:hidden}.dbs-resize{position:absolute;left:-4px;top:0;bottom:0;width:8px;cursor:ew-resize}.dbs-head{height:42px;display:flex;align-items:center;gap:8px;padding:0 10px;border-bottom:1px solid var(--dsw-alias-border-l1)}.dbs-title{font-size:13px;font-weight:600;flex:1}.dbs-tabs{display:flex;gap:2px}.dbs-tab,.dbs-icon{height:28px;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}.dbs-tab{padding:0 9px;font-size:12px}.dbs-tab[data-active=true],.dbs-tab:hover,.dbs-icon:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}.dbs-body{min-height:0;flex:1;display:grid;grid-template-columns:180px minmax(0,1fr)}.dbs-tree{overflow:auto;border-right:1px solid var(--dsw-alias-border-l1);padding:6px}.dbs-row{width:100%;height:28px;display:flex;align-items:center;gap:6px;padding:0 7px;border:0;border-radius:5px;background:transparent;color:var(--dsw-alias-label-secondary);font-size:12px;text-align:left;cursor:pointer}.dbs-row:hover,.dbs-row[data-active=true]{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}.dbs-view{min-width:0;min-height:0;display:flex;flex-direction:column}.dbs-path{height:34px;display:flex;align-items:center;padding:0 10px;border-bottom:1px solid var(--dsw-alias-border-l1);color:var(--dsw-alias-label-tertiary);font:12px var(--ds-font-family-code);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dbs-content{min-height:0;flex:1;overflow:auto;margin:0;padding:12px;color:var(--dsw-alias-label-secondary);font:12px/1.55 var(--ds-font-family-code);white-space:pre-wrap;word-break:break-word}.dbs-frame{width:100%;height:100%;border:0;background:#fff}.dbs-state{display:grid;place-items:center;height:100%;padding:24px;color:var(--dsw-alias-label-tertiary);font-size:13px;text-align:center}.dbs-error{color:var(--dsw-alias-state-error-primary)}
@media(max-width:760px){.dbs-panel{left:12px;width:auto!important}.dbs-body{grid-template-columns:140px minmax(0,1fr)}}`;
    function style(){ if(document.querySelector(`style[data-plugin-css="${ID}"]`))return;const tag=document.createElement("style");tag.dataset.pluginCss=ID;tag.textContent=css;document.head.appendChild(tag); }
    function get(id){return states.get(id)||{...defaults};}
    function set(id,patch){states.set(id,{...get(id),...patch});for(const fn of listeners)fn();}
    function useStateFor(id){return React.useSyncExternalStore((fn)=>{listeners.add(fn);return()=>listeners.delete(fn);},()=>get(id),()=>get(id));}
    function endpoint(op,id,path){const q=new URLSearchParams({sessionId:id});if(path)q.set("path",path);return `/__dsh-preview/${op}?${q}`;}
    async function json(url,options){const response=await fetch(url,options);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||body.error||`HTTP ${response.status}`);return body;}
    function parent(path){const parts=String(path||"").split("/").filter(Boolean);parts.pop();return parts.join("/");}
    function isHtml(path){return /\.(html?|svg)$/i.test(path);}
    function site(id,token,path){const host=location.hostname==="127.0.0.1"?"localhost":"127.0.0.1";const p=String(path||"").split("/").filter(Boolean).map(encodeURIComponent).join("/");return `${location.protocol}//${host}:${location.port}/__dsh-preview/site/${encodeURIComponent(token)}/${encodeURIComponent(id)}/${p}`;}
    function Launch({sessionId}){const state=useStateFor(sessionId);return React.createElement("button",{type:"button",className:"dbs-launch","data-open":state.open||undefined,"aria-label":"打开增强侧边栏",title:"增强侧边栏",onClick:()=>set(sessionId,{open:!state.open})},React.createElement("svg",{viewBox:"0 0 20 20",width:18,height:18,fill:"none","aria-hidden":true},React.createElement("rect",{x:2.5,y:3,width:15,height:14,rx:2,stroke:"currentColor",strokeWidth:1.4}),React.createElement("path",{d:"M8 3v14M11 7h4M11 10h4M11 13h3",stroke:"currentColor",strokeWidth:1.3,strokeLinecap:"round"})));}
    function Panel({sessionId}){const state=useStateFor(sessionId);const [listing,setListing]=React.useState(null);const [content,setContent]=React.useState("");const [error,setError]=React.useState("");const [token,setToken]=React.useState(state.siteToken||"");
      React.useEffect(()=>{if(!state.open)return;setError("");json(endpoint("meta",sessionId)).then((m)=>{const t=m.siteToken||m.token||"";setToken(t);if(t)set(sessionId,{siteToken:t});}).catch((e)=>setError(e.message));},[state.open,sessionId]);
      React.useEffect(()=>{if(!state.open)return;setError("");json(endpoint("tree",sessionId,state.dir)).then(setListing).catch((e)=>setError(e.message));},[state.open,state.dir,sessionId]);
      React.useEffect(()=>{if(!state.open||!state.file||isHtml(state.file))return;setError("");fetch(endpoint("file",sessionId,state.file)).then(async(r)=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);setContent(await r.text());}).catch((e)=>setError(e.message));},[state.open,state.file,sessionId]);
      if(!state.open)return null;const entries=listing?.entries||[];const viewer=error?React.createElement("div",{className:"dbs-state dbs-error"},error):state.tab==="browser"?(state.file&&isHtml(state.file)&&token?React.createElement("iframe",{className:"dbs-frame",src:site(sessionId,token,state.file),sandbox:"allow-scripts allow-forms allow-modals allow-popups",title:state.file}):React.createElement("div",{className:"dbs-state"},"在资源管理器中选择 HTML 或 SVG 文件后，可在此隔离预览。")):(state.file?React.createElement("pre",{className:"dbs-content"},content):React.createElement("div",{className:"dbs-state"},"选择工作区文件查看内容。"));
      const resize=(event)=>{const start=event.clientX,width=state.width;event.currentTarget.setPointerCapture(event.pointerId);const move=(e)=>set(sessionId,{width:Math.max(340,Math.min(900,width+start-e.clientX))});const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)};
      return React.createElement("section",{className:"dbs-panel",style:{"--dbs-width":`${state.width}px`},"aria-label":"增强侧边栏"},React.createElement("div",{className:"dbs-resize",onPointerDown:resize}),React.createElement("header",{className:"dbs-head"},React.createElement("span",{className:"dbs-title"},"增强侧边栏 · Rust"),React.createElement("nav",{className:"dbs-tabs"},React.createElement("button",{className:"dbs-tab","data-active":state.tab==="explorer"||undefined,onClick:()=>set(sessionId,{tab:"explorer"})},"资源管理器"),React.createElement("button",{className:"dbs-tab","data-active":state.tab==="browser"||undefined,onClick:()=>set(sessionId,{tab:"browser"})},"浏览器")),React.createElement("button",{className:"dbs-icon","aria-label":"关闭增强侧边栏",onClick:()=>set(sessionId,{open:false})},"×")),React.createElement("div",{className:"dbs-body"},React.createElement("aside",{className:"dbs-tree"},state.dir&&React.createElement("button",{className:"dbs-row",onClick:()=>set(sessionId,{dir:parent(state.dir)})},"↰ 上一级"),entries.map((entry)=>React.createElement("button",{key:entry.path,className:"dbs-row","data-active":entry.path===state.file||undefined,title:entry.path,onClick:()=>entry.kind==="directory"?set(sessionId,{dir:entry.path}):set(sessionId,{file:entry.path,tab:isHtml(entry.path)?"browser":"explorer"})},entry.kind==="directory"?"▸":"·",React.createElement("span",null,entry.name||entry.path.split("/").pop())))),React.createElement("main",{className:"dbs-view"},React.createElement("div",{className:"dbs-path",title:state.file||state.dir||"工作区"},state.file||state.dir||"工作区"),viewer)));
    }
    function apply(ctx){style();ctx.slots.inject("conversation.session.header.utilities",()=>ctx.slots.register({name:"conversation.session.header.utilities",id:"better-sidebar",order:680,label:"Better sidebar"},Launch));ctx.slots.inject("shell.overlay",()=>ctx.slots.register({name:"shell.overlay",id:"better-sidebar-panel",order:90,label:"Better sidebar panel"},Panel));}
    exports.apply=apply;exports.inject=inject;return module.exports;
  }
});
