const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const modules=process.argv[2],React=require(path.join(modules,'react')),{JSDOM}=require(path.join(modules,'jsdom'));const h=React.createElement;
const dom=new JSDOM('<main></main>',{url:'http://localhost/'});Object.assign(globalThis,{window:dom.window,document:dom.window.document,IS_REACT_ACT_ENVIRONMENT:true});const root=require(path.join(modules,'react-dom/client')).createRoot(document.querySelector('main'));
let state={revision:0,storageError:null,canRestore:true,scopes:['screen_read','input','clipboard_read'],targets:[{id:'verified-target',ownerSessionId:'owner-a',identity:{label:'Fixture App',deviceId:'device',applicationId:'fixture.exe',applicationRevision:'hash',origin:'https://fixture.invalid'}}],grants:[]},fail=false;const requests=[];
const context={react:React,setInterval,clearInterval,fetch:async(url,options)=>{assert.equal(url,'/__dsh-computer-permissions');const args=JSON.parse(options.body);requests.push(args);if(args.action==='list')return {ok:true,json:async()=>structuredClone(state)};if(fail){fail=false;state.revision++;return {ok:false,json:async()=>({error:'授权列表已变化'})};}assert.equal(args.expectedRevision,state.revision);state.revision++;if(args.action==='grant'){assert.equal(args.targetId,'verified-target');assert.equal(args.ownerSessionId,state.targets[0].ownerSessionId);state.grants.push({id:'grant-'+state.revision,identity:state.targets[0].identity,scope:args.scope,scopes:args.scopes,remaining:null,revoked:false})}else if(args.action==='revoke'){state.grants.find(g=>g.id===args.grantId).revoked=true}else if(args.action==='recover'){assert.equal(args.strategy,'last-good');state.storageError=null;state.targets=[];}return {ok:true,json:async()=>structuredClone(state)}}};
const source=fs.readFileSync(path.join(__dirname,'../../web/src/runtime-plugins/ui-settings-general.js'),'utf8');vm.runInNewContext(source.slice(source.indexOf('function ComputerPermissionsSection('),source.indexOf('\t\tfunction apply(ctx)')),context);
const act=fn=>React.act(async()=>{await fn();await new Promise(r=>setImmediate(r))});const props=node=>node[Object.keys(node).find(k=>k.startsWith('__reactProps$'))];const button=text=>[...document.querySelectorAll('button')].find(b=>b.textContent===text);
(async()=>{
 await act(()=>root.render(h(context.ComputerPermissionsSection)));assert.match(document.body.textContent,/Fixture App/);assert.equal(button('授权所选目标'),undefined);
 await act(()=>props(document.querySelector('input[type=radio]')).onChange());assert.ok(button('授权所选目标'));await act(()=>props(document.querySelectorAll('input[type=checkbox]')[2]).onChange({target:{checked:true}}));await act(()=>button('授权所选目标').click());
 const saved=requests.find(r=>r.action==='grant');assert.equal(saved.scope,'session');assert.deepEqual(saved.scopes,['screen_read','clipboard_read']);assert.equal(saved.ownerSessionId,'owner-a');assert.match(document.body.textContent,/有效/);
 await act(()=>button('撤销').click());assert.equal(state.grants[0].revoked,true);assert.match(document.body.textContent,/已撤销/);
 fail=true;await act(()=>button('授权所选目标').click());assert.match(document.querySelector('[role=alert]').textContent,/列表已变化/);assert.equal(state.grants.length,1,'failed CAS is not silently retried');assert.ok(document.querySelectorAll('input[type=checkbox]')[2].checked,'draft scopes survive a rejected write');
 state.storageError='corrupt';await act(()=>button('刷新目标与授权').click());assert.equal(button('授权所选目标'),undefined);assert.match(document.body.textContent,/自动控制保持拒绝/);await act(()=>button('恢复有效备份').click());assert.equal(state.storageError,null);assert.equal(document.querySelector('input[type=radio]'),null);
 await act(()=>root.unmount());dom.window.close();console.log('PASS application permissions UI: explicit target/owner/scopes, revocation, CAS draft preservation and closed-storage recovery');
})().catch(e=>{console.error(e);process.exitCode=1;dom.window.close()});
