const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../../release/plugins/dsh-better-sidebar/lib/client.js'),'utf8');
const context={console,notifyRegistry(){}};
vm.runInNewContext(source.slice(source.indexOf('class DocumentPreviewRegistry {'),source.indexOf('const documentPreviews='))+'\nthis.Registry=DocumentPreviewRegistry;',context);
const registry=new context.Registry();let notices=0;const stop=registry.subscribe(()=>notices++);
const definition=(id,extensions,priority)=>({id,extensions,priority,title:()=>id,loading:'text-pages'});
const original=registry.getSnapshot();assert.equal(original,registry.getSnapshot());
const first=registry.register(definition('builtin',['gz','md'],'builtin'));
const second=registry.register(definition('compound',['tar.gz'],'builtin'));
const third=registry.register(definition('extension',['gz']));
assert.deepEqual(Array.from(registry.candidates('C:\\work\\DATA.TAR.GZ'),entry=>entry.id),['extension','compound','builtin']);
assert.equal(registry.candidates('notsuffix-md').length,0);
assert.equal(registry.candidates('README.MD')[0].id,'builtin');
assert.notEqual(original,registry.getSnapshot());assert.equal(notices,3);
assert.throws(()=>registry.register(definition('extension',['gz'])),/duplicate/);
assert.throws(()=>registry.register(definition('invalid',['../gz'])),/invalid/);
const metadata=definition('immutable',['js']);const remove=registry.register(metadata);metadata.extensions.push('rs');assert.equal(registry.candidates('main.rs').length,0);
remove();third();third();assert.equal(notices,6);stop();first();second();assert.equal(notices,6);
console.log('PASS document previews: extension precedence, compound suffixes, stable immutable snapshots, duplicate refusal, lifecycle cleanup');
