const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
let plugin,definition,tail;
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../web/src/runtime-plugins/ui-deliverables.js'),'utf8'),{window:{__ModuleLoader__:{load:entry=>{plugin=entry.factory(()=>({isAppendSurfaceEvent:event=>event.surfaceOp==='append'}))}}}});
plugin.apply({get:()=>({isLoopback:true,generation:{getSnapshot:()=>({}),subscribe:()=>()=>{}}}),conversationEvents:{register:value=>{definition=value}},effect:fn=>fn(),locale:{register:()=>{},bind:()=>key=>key},slots:{inject:(_,fn)=>fn(),register:value=>{tail=value}},provide:()=>{}});
const start={type:'turn/start',seq:0,data:{turn:1}};
let state=definition.start({}, {event:start});
state=definition.update({state},{event:{type:'tool/call',seq:1,data:{turn:1,callId:'edit'}},view:{for:'call',view:{card:'diff',locations:[{path:'intermediate.txt'}]}}});
state=definition.update({state},{event:{type:'tool/result',seq:2,surfaceOp:'append',data:{turn:1,message:{content:[{isError:false}],source:{callId:'edit'}}}}});
assert.deepEqual(Array.from(plugin.producedForClosing(state)),['intermediate.txt']);
const declared={type:'deliverables/presented',seq:5,data:{turn:1,callId:'present',files:[{path:'final.pdf',description:'Final report'},{path:'final.pdf'}]}};
assert.equal(definition.match(declared).id,'1');state=definition.update({state},{event:declared});
assert.deepEqual(Array.from(plugin.producedForClosing(state,4)),['intermediate.txt'],'future declarations cannot rewrite an earlier closing');
assert.deepEqual(Array.from(plugin.producedForClosing(state,6)),['final.pdf'],'explicit output is independent of the creation tool and deduplicated');
const match=tail.select({turn:{data:new Map([['deliverables',state]])},seq:6});assert.equal(match.declared,true);assert.deepEqual(Array.from(match.paths),['final.pdf']);
const fresh=definition.start({}, {event:{...start,data:{turn:2}}});assert.equal(plugin.producedForClosing(fresh).length,0,'declarations do not leak into another turn');
assert.equal(definition.match({...declared,data:{...declared.data,turn:-1}}),null);
assert.equal(definition.match({...declared,data:{...declared.data,files:Array(9).fill({path:'too-many'})}}),null);
assert.equal(definition.match({...declared,data:{turn:1,files:[{path:'missing-call'}]}}),null);
console.log('PASS explicit deliverables: model declaration, legacy fallback, closing boundary, deduplication and per-turn isolation');
