const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const text=fs.readFileSync(require('node:path').join(__dirname,'../../web/dist/plugins/client-runtime.js'),'utf8');
const start=text.indexOf('const HISTORY_PAGE_MESSAGES'),end=text.indexOf('\n\t\tvar SessionManager = class',start);
const ctx={console,clearTimeout,conversationInput:x=>x};vm.runInNewContext(text.slice(start,end)+';this.TestSession=Session;',ctx);
const managerStart=text.indexOf('\n\t\tvar SessionManager = class');
vm.runInNewContext(text.slice(managerStart,text.indexOf('\n\t\t//#endregion',managerStart))+';this.TestSessionManager=SessionManager;',ctx);
const session=Object.create(ctx.TestSession.prototype);
let rebuilds=0,prepends=0;
Object.assign(session,{events:[],views:[],historyPages:[],hasMoreBefore:true,hasMoreAfter:false,baseSeq:0,openState:'open',openGeneration:0,loadingOlder:false,loadingNewer:false,historyTargetSeq:null,notifier:{markDirty(){}},conversation:{replaceWindow(){rebuilds++},prepend(){prepends++}},liveBuffer:[]});
const entry=seq=>({event:{seq,type:'user/message',time:seq,data:{text:'x'.repeat(180000)}},view:undefined});
const appendPage=first=>{const page=Array.from({length:12},(_,i)=>entry(first+i));session.events.push(...page.map(x=>x.event));session.views.push(...page.map(x=>x.view));session.historyPages.push(session.pageMeta(page));return page;};
appendPage(1200);assert.equal(session.trimHistoryWindow('head'),false);assert.equal(rebuilds,0,'unchanged windows must not rebuild');
session.baseSeq=1200;
session.history=async payload=>({result:{ok:true,value:{events:Array.from({length:12},(_,i)=>entry(payload.beforeSeq-12+i)),hasMoreBefore:payload.beforeSeq>12}}});
(async()=>{
 for(let i=0;i<85;i++){
  const before=rebuilds;await session.loadOlder();assert.ok(rebuilds-before<=1,'paging must rebuild at most once');
  assert.ok(session.historyPages.length<=5);assert.ok(session.historyPages.length===1||session.historyPages.reduce((n,p)=>n+p.bytes,0)<=8*1024*1024);
  assert.equal(session.events.length,session.historyPages.reduce((n,p)=>n+p.eventCount,0));
  assert.equal(session.hasMoreAfter,true);assert.notEqual(session.historyTargetSeq,null,'evicting the live tail must enter historical browsing');
 }
 const before=session.events;
 let release;session.history=()=>new Promise(resolve=>{release=resolve});const pending=session.loadOlder();await Promise.resolve();session.openGeneration++;
 release({result:{ok:true,value:{events:Array.from({length:12},(_,i)=>entry(session.baseSeq-12+i)),hasMoreBefore:true}}});await pending;
 assert.equal(session.events,before,'stale pages cannot rewrite a new window');
 const manager=Object.create(ctx.TestSessionManager.prototype);
 Object.assign(manager,{sessions:new Map(),historyRecency:new Map(),selected:'selected'});
 const createResident=(id,bytes=6*1024*1024)=>{
  const resident=Object.create(ctx.TestSession.prototype),draft={text:'keep unsent input'},waits=new Map([['approval',{key:'approval'}]]);
  Object.assign(resident,{sessionId:id,options:{},events:[{seq:100,type:'user/message',data:{text:'resident payload'}}],views:[{body:'rendered payload'}],historyPages:[{bytes,eventCount:1}],liveBuffer:[{event:{seq:101}}],openState:'open',openGeneration:0,historyNavigationRevision:0,historyTargetSeq:100,baseSeq:100,openPromise:null,stitching:false,running:false,promptInFlight:[],draft,pending:waits});
  resident.conversation={retained:resident.events,replaceWindow(events){this.retained=events;}};
  resident.snapshotCache={events:resident.events};
  resident.notifier={listeners:new Set(),markDirty(){},notifyNow(){resident.snapshotCache={events:resident.events};}};
  manager.sessions.set(id,resident);manager.touchHistory(resident);return resident;
 };
 const first=createResident('first'),draft=first.draft,waits=first.pending;
 const visible=createResident('visible');visible.notifier.listeners.add(()=>{});
 const active=createResident('active');active.running=true;
 const submitting=createResident('submitting');submitting.promptInFlight.push({});
 const selected=createResident('selected');
 for(let i=0;i<40;i++)createResident('visited-'+i);
 const inactive=[...manager.sessions.values()].filter(s=>s.events.length&&!['visible','active','selected','submitting'].includes(s.sessionId));
 assert.ok(inactive.length<=8,'visited inactive sessions must not retain unbounded windows');
 assert.ok(inactive.reduce((n,s)=>n+s.historyPages.reduce((n,p)=>n+p.bytes,0),0)<=32*1024*1024,'cross-session byte budget');
 assert.equal(first.openState,'cold');assert.equal(first.events.length,0);assert.equal(first.views.length,0);assert.equal(first.liveBuffer.length,0);
 assert.equal(first.conversation.retained.length,0);assert.equal(first.snapshotCache.events.length,0,'snapshot must not retain old nodes');
 assert.equal(first.draft,draft);assert.equal(first.pending,waits,'suspension must preserve live interactions');
 assert.equal(first.historyTargetSeq,100,'historical read anchor survives suspension');
 for(const protectedSession of [visible,active,submitting,selected])assert.equal(protectedSession.events.length,1);
 const staleGeneration=first.openGeneration;let resolveOpen;
 first.history=()=>new Promise(resolve=>{resolveOpen=resolve});
 first.fetchHistory=ctx.TestSession.prototype.fetchHistory;
 const opening=first.doOpen(staleGeneration);await Promise.resolve();await Promise.resolve();
 first.releaseHistory();resolveOpen({result:{ok:true,value:{events:[entry(100)],hasMore:false}}});await opening;
 assert.equal(first.events.length,0,'late history responses cannot resurrect an evicted window');
 manager.drop('first');assert.equal(first.disposed,true);assert.equal(manager.sessions.has('first'),false);
 const realContext={console,setTimeout,clearTimeout,queueMicrotask};
 vm.runInNewContext(text.slice(text.indexOf('var Notifier = class'),text.indexOf('\n\t\t//#endregion',managerStart))+';this.SessionClass=Session;',realContext);
 const resident=new realContext.SessionClass('real-assembler',{},{});
 const realEntry={event:{seq:100,type:'user/message',time:0,data:{content:[{type:'text',text:'x'.repeat(1024*1024)}]}}};
 resident.installWindow([realEntry],false);resident.openState='open';resident.notifier.notifyNow();
 assert.equal(resident.conversation.inputs.size,1);
 resident.rememberReadingPosition(true);resident.releaseHistory();
 assert.equal(resident.conversation.inputs.size,0);assert.equal(resident.conversation.contexts.size,0);
 assert.equal(resident.conversation.locationIndex.coordinates.size,0,'real assembler indexes release loaded events');
 let restoredRequest;
 resident.api={sessions:{history:async payload=>{restoredRequest=payload;return {result:{ok:true,value:{events:[realEntry],hasMore:false,hasMoreBefore:true,hasMoreAfter:true}}};}}};
 await resident.open();
 assert.equal(restoredRequest.afterSeq,100,'reopening restores the saved reading anchor');
 assert.equal(resident.openState,'open');assert.equal(resident.events.length,1);
 console.log(JSON.stringify({pages:85,retainedEvents:session.events.length,retainedBytes:session.historyPages.reduce((n,p)=>n+p.bytes,0),rebuilds,prepends}));
})().catch(error=>{console.error(error);process.exitCode=1});
