const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const modules=process.env.DSH_REACT_TEST_MODULES||process.argv[2];if(!modules)throw Error('Pass react/react-dom/jsdom node_modules');
const {JSDOM}=require(path.join(modules,'jsdom')),dom=new JSDOM('<!doctype html><html><head></head><body><main id="root"></main></body></html>',{url:'http://learning.fixture.invalid',pretendToBeVisual:true});Object.assign(global,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});
const React=require(path.join(modules,'react')),jsx=require(path.join(modules,'react/jsx-runtime')),Client=require(path.join(modules,'react-dom/client'));
let connectionCodec;
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../web/dist/plugins/connection.js'),'utf8').replace('return module.exports;','exports.testPreviewSchema=memoryLearningPreviewValueSchema;return module.exports;'),{URL,TextEncoder,TextDecoder,AbortController,setTimeout,clearTimeout,window:{__ModuleLoader__:{load:def=>{connectionCodec=def.factory(()=>({}))}}}});
assert.throws(()=>connectionCodec.testPreviewSchema.parse({mode:'unknown-preview',enabled:true,workspaceKey:'workspace-a',items:[]}));
const copy=value=>JSON.parse(JSON.stringify(value)),now=Date.now();
const entry=(id,status,verification,extra={})=>({id,workspaceKey:'workspace-a',workspaceLabel:'示例项目',tool:'shell',category:'arguments',code:'SCHEMA_INVALID',source:'tool',provider:'provider-a',models:[{provider:'provider-a',model:'model-a',count:2}],occurrences:2,firstSeen:now-10000,lastSeen:now-5000,lastRecovered:null,status,verification,suggestion:'检查必填参数与参数类型。',ruleId:'tool-input-schema',message:'工具参数不符合当前定义。',enabled:true,revision:1,applicationCount:0,lastApplied:null,lastApplicationOutcome:null,...extra});
let ledger={enabled:true,memoryEnabled:true,effectiveEnabled:true,revision:10,lastError:null,items:[entry('pending','pending',null),entry('confirmed','verified','user-confirmed',{source:'provider',tool:'provider.request',code:'RATE_LIMITED',applicationCount:3,lastApplied:now-3000,lastApplicationOutcome:'advisory'}),entry('recovered','verified','recovered',{lastRecovered:now-2000,applicationCount:1,lastApplied:now-1000,lastApplicationOutcome:'preflight_blocked'})]},calls=[],readError=null,writeError=null,previewBad=false,previewSource="current",previewNotice=null,previewMatchReason="same-workspace-provider-model";
const result=value=>({result:{ok:true,value:copy(value.mode?connectionCodec.testPreviewSchema.parse(value):value)}}),timers=new Map();let sequence=0;
function responseList(payload){let rows=ledger.items.filter(item=>(!payload.workspaceKey||item.workspaceKey===payload.workspaceKey)&&(!payload.status||item.status===payload.status)&&(!payload.query||JSON.stringify(item).toLowerCase().includes(payload.query.toLowerCase())));return{...ledger,items:rows.slice(0,payload.limit||100),total:rows.length}}
const api={memory:{}};
for(const name of ['learningList','learningConfigure','learningToggle','learningRemove','learningConfirm','learningPreview'])api.memory[name]=async payload=>{
 calls.push({name,payload:copy(payload)});if(name==='learningList'){if(readError)throw Error(readError);return result(responseList(payload))}
 if(name==='learningPreview')return result({mode:previewSource==='last-request'?'historical-context-preview':'next-request-preview',toolSource:previewSource,notice:previewNotice,workspaceKey:previewBad?'':'workspace-a',enabled:ledger.effectiveEnabled,provider:'provider-a',model:'model-a',budget:2200,usedCharacters:200,maxItems:6,items:ledger.effectiveEnabled?[{id:'confirmed',tool:'provider.request',ruleId:'provider-rate-limit',category:'provider',verification:'user-confirmed',suggestion:'等待限流恢复，再重试一次。',matchReason:previewMatchReason}]:[],excluded:[{id:'recovered',reason:'context-budget'}],text:ledger.effectiveEnabled?'已验证操作经验：等待限流恢复，再重试一次。':'',selectionRules:['verified-and-enabled','same-workspace','bounded-context']});
 if(writeError)return{result:{ok:false,error:{code:'conflict',message:writeError}}};
 if(name==='learningConfigure'){assert.equal(payload.expectedRevision,ledger.revision);ledger.enabled=payload.enabled;ledger.effectiveEnabled=ledger.enabled&&ledger.memoryEnabled;ledger.revision++;return result(responseList({}))}
 const row=ledger.items.find(item=>item.id===payload.id);assert.ok(row);assert.equal(payload.expectedRevision,row.revision);ledger.revision++;
 if(name==='learningRemove'){ledger.items=ledger.items.filter(item=>item!==row);return result({removed:true})}
 row.revision++;if(name==='learningToggle')row.enabled=payload.enabled;
 if(name==='learningConfirm'){assert.equal(payload.confirmed,true);assert.equal('verification' in payload,false);assert.equal('status' in payload,false);row.status='verified';row.verification='user-confirmed';row.suggestion=payload.suggestion}
 return result({entry:row});
};
let plugin;const source=fs.readFileSync(path.join(__dirname,'../../web/dist/plugins/ui-settings-general.js'),'utf8');const context={document,window,console,setTimeout,clearTimeout,setInterval:fn=>{const id=++sequence;timers.set(id,fn);return id},clearInterval:id=>timers.delete(id),window:{__ModuleLoader__:{load:def=>{plugin=def.factory(name=>name==='react'?React:name==='react/jsx-runtime'?jsx:{})}}}};vm.runInNewContext(source.replace('return module.exports;','exports.test={ExperiencePanel,MemorySection};return module.exports;'),context);
const root=Client.createRoot(document.getElementById('root')),{act}=React;
const flush=async(ms=20)=>act(async()=>{await new Promise(resolve=>setTimeout(resolve,ms))});
const render=async props=>{await act(async()=>root.render(React.createElement(plugin.test.ExperiencePanel,{api,...props})));await flush()};
const row=id=>document.querySelector(`[data-experience-id="${id}"]`);
async function click(text,within=document){const button=[...within.querySelectorAll('button')].find(node=>node.textContent===text);assert.ok(button,text);await act(async()=>button.click());await flush()}
async function input(selector,value){const target=document.querySelector(selector);assert.ok(target,selector);await act(async()=>{Object.getOwnPropertyDescriptor(target.tagName==='TEXTAREA'?dom.window.HTMLTextAreaElement.prototype:dom.window.HTMLInputElement.prototype,'value').set.call(target,value);target.dispatchEvent(new dom.window.Event('input',{bubbles:true}))});await flush(250)}
async function poll(){await act(async()=>{for(const callback of [...timers.values()])callback();await new Promise(resolve=>setImmediate(resolve))});await flush()}
(async()=>{
 await render({});assert.equal(document.querySelectorAll('[data-experience-id]').length,3);assert.match(row('pending').textContent,/待验证/);assert.match(row('confirmed').textContent,/用户确认/);assert.match(row('recovered').textContent,/工具恢复/);assert.match(row('pending').textContent,/重复 1 次/);assert.match(row('pending').textContent,/示例项目/);assert.match(row('pending').textContent,/provider-a \/ model-a × 2/);assert.match(row('pending').textContent,/工具前应用次数/);assert.match(row('confirmed').textContent,/模型请求前应用次数/);assert.match(row('pending').textContent,/错误类别与诊断/);assert.match(row('pending').textContent,/SCHEMA_INVALID/);assert.equal(document.body.textContent.includes('原始错误'),false);
 await input('input[aria-label="查询自动经验"]','RATE_LIMITED');assert.equal(document.querySelectorAll('[data-experience-id]').length,1);assert.equal(calls.filter(call=>call.name==='learningList').at(-1).payload.query,'RATE_LIMITED');await input('input[aria-label="查询自动经验"]','');
 await click('确认修正建议',row('pending'));await input('textarea[aria-label="确认的修正建议"]','先核对必填参数，再执行一次。');ledger.items[0].occurrences++;ledger.items[0].revision++;ledger.revision++;await poll();assert.equal(document.querySelector('textarea').value,'先核对必填参数，再执行一次。','capture refresh preserves human draft');assert.match(row('pending').textContent,/重复 2 次/);assert.equal([...row('pending').querySelectorAll('button')].find(button=>button.textContent==='确认此建议').disabled,true);await click('已核对最新记录',row('pending'));await click('确认此建议',row('pending'));assert.equal(ledger.items[0].verification,'user-confirmed');assert.equal(ledger.items[0].lastRecovered,null);assert.equal(ledger.items[0].applicationCount,0);assert.match(row('pending').textContent,/已确认 · 用户确认/);assert.ok(calls.some(call=>call.name==='learningConfirm'&&call.payload.expectedRevision===2));
 writeError='记录已更新，请重试';await act(async()=>row('confirmed').querySelector('input[type=checkbox]').click());await flush();assert.equal(row('confirmed').querySelector('input').checked,true);assert.match(document.body.textContent,/记录已更新/);writeError=null;await act(async()=>row('confirmed').querySelector('input').click());await flush();assert.equal(row('confirmed').querySelector('input').checked,false);assert.match(row('confirmed').textContent,/不参与经验复用/);
 const removes=calls.filter(call=>call.name==='learningRemove').length;await click('删除',row('pending'));await click('取消',row('pending'));assert.equal(calls.filter(call=>call.name==='learningRemove').length,removes);await click('删除',row('pending'));await click('确认删除',row('pending'));assert.equal(row('pending'),null);
 const configureBefore=calls.filter(call=>call.name==='learningConfigure').length;ledger.memoryEnabled=false;ledger.effectiveEnabled=false;await render({memoryEnabled:false});const capture=document.querySelector('input[aria-label="自动捕获与复用经验"]');assert.equal(capture.checked,true,'own learning preference remains on under master pause');assert.equal(capture.disabled,true);assert.match(document.body.textContent,/持久记忆已关闭，自动捕获与复用暂停/);await act(async()=>capture.click());assert.equal(calls.filter(call=>call.name==='learningConfigure').length,configureBefore);
 ledger.memoryEnabled=true;ledger.effectiveEnabled=true;await render({memoryEnabled:true});await act(async()=>document.querySelector('input[aria-label="自动捕获与复用经验"]').click());await flush();assert.equal(ledger.enabled,false);assert.equal(ledger.effectiveEnabled,false);assert.match(document.body.textContent,/自动捕获与经验复用已暂停/);assert.equal(document.querySelectorAll('[data-experience-id]').length,2);
 ledger.enabled=true;ledger.effectiveEnabled=true;ledger.items.find(item=>item.id==='confirmed').enabled=true;const applications=ledger.items.reduce((sum,item)=>sum+item.applicationCount,0);await render({key:'context',sessionId:'s1'});assert.ok(calls.some(call=>call.name==='learningPreview'&&call.payload.sessionId==='s1'));assert.equal(calls.filter(call=>call.name==='learningList').at(-1).payload.workspaceKey,'workspace-a');assert.match(document.querySelector('[data-experience-preview]').textContent,/下次请求匹配预览/);assert.match(document.querySelector('[data-experience-preview]').textContent,/200 \/ 2200 字符/);assert.match(row('confirmed').querySelector('[data-experience-reuse]').textContent,/工作区、提供方和模型一致/);assert.match(row('recovered').querySelector('[data-experience-reuse]').textContent,/达到条目数或上下文字符预算/);assert.equal(ledger.items.reduce((sum,item)=>sum+item.applicationCount,0),applications,'read-only preview never changes actual application counts');
 previewSource='last-request';previewNotice='当前展示最近请求的工具快照，实际执行前会重新匹配。';previewMatchReason='same-workspace-tool';await poll();assert.ok(document.querySelector('[data-experience-preview]').textContent.includes(previewNotice));assert.match(row('confirmed').querySelector('[data-experience-reuse]').textContent,/最近请求的工具快照/);assert.equal(row('confirmed').querySelector('[data-experience-reuse]').textContent.includes('当前工具可用'),false);
 readError='连接中断';await poll();assert.equal(document.querySelectorAll('[data-experience-id]').length,2);assert.match(document.body.textContent,/连接中断/);readError=null;previewBad=true;const listCalls=calls.filter(call=>call.name==='learningList').length;await render({key:'bad-context',sessionId:'s2'});assert.match(document.body.textContent,/预览返回的数据不完整/);assert.equal(calls.filter(call=>call.name==='learningList').length,listCalls,'unresolved context never falls back to all workspaces');
 previewBad=false;ledger.items=[entry('pending-feedback','pending',null,{tool:'',source:'feedback',category:'feedback',ruleId:'user-feedback',suggestion:''}),entry('pending-auth','pending',null,{tool:'',source:'provider',category:'authentication',ruleId:'provider-auth'}),entry('pending-unknown-tool','pending',null,{tool:'missing-tool',category:'tool-availability',ruleId:'tool-availability'}),entry('pending-schema','pending',null,{tool:'glob',ruleId:'tool-input-schema'}),entry('pending-observe','pending',null,{tool:'edit',category:'filesystem-observation',ruleId:'observe-before-write'})];await render({key:'pending-strategies'});assert.equal(row('pending-feedback').querySelector('.dshMemoryItemHead strong').textContent,'用户反馈');assert.equal(row('pending-auth').querySelector('.dshMemoryItemHead strong').textContent,'账号与访问权限');assert.equal(row('pending-schema').querySelector('.dshMemoryItemHead strong').textContent,'glob');for(const id of ['pending-feedback','pending-auth','pending-unknown-tool']){const text=row(id).querySelector('[data-experience-reuse]').textContent;assert.match(text,/需要你检查并确认明确的修正建议/);assert.equal(text.includes('等待后续工具恢复'),false)}for(const id of ['pending-schema','pending-observe'])assert.match(row(id).querySelector('[data-experience-reuse]').textContent,/同一任务内符合条件的工具成功来验证恢复/);
 await act(async()=>root.unmount());assert.equal(timers.size,0);console.log('PASS learning React DOM: captured failure/repeat/model/workspace evidence; server query; draft-safe automatic refresh; explicit user confirmation without fake recovery; conflict/retry; disable/delete; master pause; precise next-request preview/budget exclusion with unchanged application counts; read failure and unresolved-scope isolation; polling cleanup');
})().catch(error=>{console.error(error);process.exitCode=1});
