const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const work=process.argv[2],phase=process.argv[3]||'save';if(!work)throw Error('Pass the isolated fixture directory');const owned=JSON.parse(fs.readFileSync(path.join(work,'ui-owned-process.json'),'utf8'));assert.ok(Number.isInteger(owned.port)&&owned.port>0&&owned.port<65536,'isolated Host port');assert.equal(path.resolve(owned.home),path.resolve(work,'ui-home'));const fixture=JSON.parse(fs.readFileSync(path.join(work,'ui-fixtures.json'),'utf8')),base='http://127.0.0.1:'+owned.port,modules=owned.nodeModules||path.join(work,'react-tests/node_modules');
const {JSDOM}=require(path.join(modules,'jsdom')),dom=new JSDOM('<!doctype html><html><head></head><body><main id="root"></main></body></html>',{url:base});Object.assign(global,{window:dom.window,document:dom.window.document,IS_REACT_ACT_ENVIRONMENT:true});
const React=require(path.join(modules,'react')),jsx=require(path.join(modules,'react/jsx-runtime')),ReactDOM=require(path.join(modules,'react-dom/client'));
const request=async(url,options={})=>fetch(new URL(url,base),{...options,headers:{...options.headers,Origin:base}});
async function rpc(method,payload={}){const response=await request('/api/'+method,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'client-request',rpcId:crypto.randomUUID(),method,payload})});const value=await response.json();assert.equal(value.result.ok,true,method+': '+JSON.stringify(value.result));return value}
async function account(){const response=await request('/provider-auth/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:'ui-fixture'})});const value=await response.json();assert.equal(response.ok,true,JSON.stringify(value));return value}
const hash=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
async function snapshot(){const history={};for(const sessionId of fixture.sessionIds)history[sessionId]=hash((await rpc('session.history',{sessionId})).result.value.events);const listing=(await rpc('session.list')).result.value;return{history,sessionIds:(listing.items??listing.sessions??listing).map(row=>row.sessionId).sort()}}
let test;const context={document,window:{__ModuleLoader__:{load:def=>{test=def.factory(id=>id==='react'?React:id==='react/jsx-runtime'?jsx:id.endsWith('ui-primitives')?{IconCheckOutline14:()=>React.createElement('svg')}:{}).test}}},fetch:request,setTimeout,clearTimeout,structuredClone,console};
let artifactUiHash,artifactSelectorHash,selectionPlugin;
const selectionHarness=require("./model_current_label_dom_harness.cjs");
async function loadComponent(){const response=await request('/plugins/ui-settings-models.js');assert.equal(response.ok,true,'packaged UI module is served');const raw=Buffer.from(await response.arrayBuffer()),source=raw.toString('utf8');assert.ok(source.includes('function ProviderModelManager('),'packaged UI has model manager');artifactUiHash=crypto.createHash('sha256').update(raw).digest('hex');const manifestResponse=await request('/plugins/manifest.json');assert.equal(manifestResponse.ok,true);const manifest=await manifestResponse.json(),entry=manifest.entries.find(row=>row.id==='@deepseek-ai/dsh-client-ui-settings-models');assert.equal(entry?.rev,artifactUiHash.slice(0,16),'served plugin manifest revision must match the actual UI bundle');vm.runInNewContext(source.replace('return module.exports;','exports.test={ProviderModelManager,en};return module.exports;'),context);const selectorResponse=await request('/plugins/ui-model-selection.js');assert.equal(selectorResponse.ok,true);const selectorRaw=Buffer.from(await selectorResponse.arrayBuffer());artifactSelectorHash=crypto.createHash('sha256').update(selectorRaw).digest('hex');assert.equal(manifest.entries.find(row=>row.id==='@deepseek-ai/dsh-client-ui-model-selection')?.rev,artifactSelectorHash.slice(0,16),'served selector manifest revision must match');selectionPlugin=selectionHarness.loadSelectionModule(selectorRaw.toString('utf8'),React,jsx,document)}

const evidencePath=path.join(work,'model-management-rpc-evidence.json');
(async()=>{
await loadComponent();
const before=await snapshot(),catalog=await account(),root=ReactDOM.createRoot(document.getElementById('root')),t=key=>test.en[key]??key;
const until=async(check,label)=>{const deadline=Date.now()+10000;while(!check()&&Date.now()<deadline)await React.act(async()=>{await new Promise(resolve=>setTimeout(resolve,25))});assert.ok(check(),label)};
const currentDirectory=new selectionPlugin.ModelDirectory({models:payload=>rpc('session.models',payload)},fixture.sessionIds[0],()=>true,async()=>{}),loadCurrent=()=>currentDirectory.load().catch(()=>{}),currentT=selectionHarness.translator(selectionPlugin.zh);
await React.act(async()=>root.render(React.createElement(React.Fragment,null,React.createElement(test.ProviderModelManager,{provider:'ui-fixture',api:{settings:{mutate:payload=>rpc('settings.mutate',payload)}},t,disabled:false,revision:catalog.namespaceRevision}),React.createElement('div',{'data-test-composer':true},React.createElement(selectionPlugin.ModelSelect,{locked:false,available:true,directory:currentDirectory.store,load:loadCurrent,select:async()=>true,t:currentT})))));
await until(()=>currentDirectory.store.getSnapshot().status==='ready','current model did not load');
const currentTrigger=()=>document.querySelector('[data-test-composer] button[aria-haspopup=menu]');
const verifyHiddenLabel=async expected=>{await React.act(async()=>currentDirectory.refresh());assert.equal(currentTrigger().dataset.currentModelState,'hidden');assert.ok(currentTrigger().textContent.includes(expected),currentTrigger().textContent);assert.ok(currentTrigger().textContent.includes('已隐藏'));await React.act(async()=>currentTrigger().click());await until(()=>currentDirectory.store.getSnapshot().status==='ready','current model refresh did not settle');await React.act(async()=>document.querySelector('[data-test-composer] [role=menuitem]').click());const candidates=[...document.querySelectorAll('[data-test-composer] [role=menuitemradio]')];assert.ok(candidates.some(node=>node.title==='Fixture Two'),'visible model stays selectable');assert.ok(candidates.every(node=>node.title!=='Fixture One'&&!node.textContent.includes('fixture-one')),'hidden current model must not be selectable');await React.act(async()=>currentTrigger().click());return currentTrigger().textContent};
await until(()=>document.querySelector('[data-model-id="fixture-one"] input[type=checkbox]'),'real catalog did not render');
const checkbox=document.querySelector('[data-model-id="fixture-one"] input[type=checkbox]');assert.ok(checkbox,'real host catalog rendered');
if(phase==='save'){
 assert.equal(currentTrigger().textContent,'Fixture One');assert.equal(checkbox.checked,true);await React.act(async()=>checkbox.click());assert.equal((await account()).models.find(row=>row.id==='fixture-one').enabled!==false,true,'draft does not write RPC');
 await React.act(async()=>{[...document.querySelectorAll('button')].find(node=>node.textContent===t('apply')).click()});await until(()=>document.querySelector('.dshModelFooter [role=status]')?.textContent===t('modelPreferencesSaved')||document.querySelector('[role=alert]'),'save did not settle');assert.equal(document.querySelector('[role=alert]'),null,document.body.textContent);
 const refreshed=await request('/provider-auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:'ui-fixture'})});assert.equal(refreshed.ok,true,await refreshed.text());const saved=await account();const sessionModels=(await rpc('session.models',{sessionId:fixture.sessionIds[0]})).result.value;assert.equal(sessionModels.current.model,'fixture-one','hiding does not replace the current model');assert.equal(sessionModels.routable,true,'hidden current model remains callable');assert.equal(saved.models.find(row=>row.id==='fixture-one').enabled,false);assert.deepEqual(await snapshot(),before,'model preference cannot remove sessions or alter any conversation event');
 const currentTriggerLabel=await verifyHiddenLabel('Fixture One');
 const sessionId=fixture.sessionIds[0],historyBefore=(await rpc('session.history',{sessionId})).result.value.events,ends=historyBefore.filter(row=>row.event.type==='turn/end').length;await rpc('session.prompt',{sessionId,content:[{type:'text',text:'隐藏当前模型后继续隔离验证'}],mode:'queue'});let continued=[];const deadline=Date.now()+30000;while(Date.now()<deadline){continued=(await rpc('session.history',{sessionId})).result.value.events;if(continued.filter(row=>row.event.type==='turn/end').length>ends)break;await new Promise(resolve=>setTimeout(resolve,50))}assert.ok(continued.filter(row=>row.event.type==='turn/end').length>ends,'hidden current model must complete another turn');assert.ok(JSON.stringify(continued.filter(row=>row.event.type==='assistant/message').at(-1)).includes('隔离会话正文'),'hidden current model produced a real fixture reply');const afterContinuation=await snapshot();assert.deepEqual(afterContinuation.sessionIds,before.sessionIds);
 fs.writeFileSync(evidencePath,JSON.stringify({phase:'saved',home:owned.home,artifactUiHash,artifactSelectorHash,currentTriggerLabel,before:afterContinuation,beforePreferenceSave:before,preferenceWritePreservedHistory:true,hiddenCurrentModelCompletedTurn:true,accountScope:saved.accountScope,preferencePath:saved.preferencePath,model:'fixture-one',enabled:false,revision:saved.namespaceRevision},null,2));
 console.log('PASS real isolated Host + React DOM: catalog rendered, toggle draft stayed local, Apply persisted scoped hidden preference, all three sessions and event hashes unchanged by settings; hidden current model completed another real turn');
}else{
 const evidence=JSON.parse(fs.readFileSync(evidencePath,'utf8'));assert.equal(checkbox.checked,false,'new mount after host restart reads durable hidden preference');assert.equal(catalog.accountScope,evidence.accountScope);assert.equal(artifactUiHash,evidence.artifactUiHash);assert.equal(artifactSelectorHash,evidence.artifactSelectorHash);evidence.freshCurrentTriggerLabel=await verifyHiddenLabel('fixture-one');assert.deepEqual(before,evidence.before,'restart preserves all session event hashes and IDs');evidence.phase='restart-verified';evidence.restartVerifiedAt=new Date().toISOString();fs.writeFileSync(evidencePath,JSON.stringify(evidence,null,2));console.log('PASS real isolated Host restart + fresh React mount: model visibility persisted; conversation hashes and session list unchanged');
}
await React.act(async()=>root.unmount());
})().catch(error=>{console.error(error);process.exitCode=1});
