const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const plugins=path.resolve(__dirname,'../../web/dist/plugins');
const clone=value=>JSON.parse(JSON.stringify(value));
const defer=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject}};
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function snapshot(value){return{getSnapshot:()=>value,update:fn=>fn(value)}}
function directoryClass(){const source=fs.readFileSync(path.join(plugins,'ui-model-selection.js'),'utf8');const start=source.indexOf('var ModelDirectory = class');const end=source.indexOf('\n\t\t//#endregion',start);const context={_deepseek_ai_dsh_client_runtime_client:{createSnapshotStore:snapshot}};vm.runInNewContext(source.slice(start,end)+';globalThis.Directory=ModelDirectory;',context);return context.Directory}
function preferenceHelpers(){const source=fs.readFileSync(path.join(plugins,'ui-settings-models.js'),'utf8');const start=source.indexOf('        function modelCatalog(');const end=source.indexOf('        class ModelEditorBoundary',start);const context={};vm.runInNewContext(source.slice(start,end)+';globalThis.helpers={modelCatalog,draftModelRows,preferenceOps,savePreferenceDraft};',context);return context.helpers}
function runtimeClasses(){const source=fs.readFileSync(path.join(plugins,'client-runtime.js'),'utf8');const start=source.indexOf('var Session = class');const end=source.indexOf('\n\t\t//#endregion',source.indexOf('function workspaceAttachSessionId',start));const context={console,HISTORY_PAGE_MESSAGES:12,HISTORY_WINDOW_PAGES:5,transportError:error=>({ok:false,error:{code:'transport',message:error.message}}),flattenLineage:rows=>rows.map(row=>({...row,depth:0}))};vm.runInNewContext(source.slice(start,end)+';globalThis.classes={Session,SessionManager};',context);return context.classes}
async function run(){
const Directory=directoryClass(),reads=[],writes=[];let saveFailure=false;
const directory=new Directory({models:()=>{const request=defer();reads.push(request);return request.promise},selectModel:request=>{const pending=defer();writes.push({request,...pending});return pending.promise}},'session',()=>true,async()=>{if(saveFailure)throw Error('settings offline')});
const initial=directory.load();await tick();reads.shift().resolve({result:{ok:true,value:{current:{provider:'p',model:'one'},routable:true,groups:[{models:[{id:'one'},{id:'two'}]}],failures:[]}}});await initial;
const lastGroups=directory.store.getSnapshot().groups;const failed=directory.load();await tick();reads.shift().reject(Error('offline'));await assert.rejects(failed,/offline/);assert.equal(directory.store.getSnapshot().groups,lastGroups);assert.equal(directory.store.getSnapshot().current.model,'one');assert.equal(directory.store.getSnapshot().status,'error');
const stale=directory.load();await tick();const change=directory.select({provider:'p',model:'two'});assert.equal(directory.select({provider:'p',model:'two'}),change);await assert.rejects(directory.select({provider:'p',model:'three'}),/already/);const invalidation=directory.refresh();await tick();assert.equal(writes.length,1);writes.shift().resolve({result:{ok:true,value:{selected:{provider:'p',model:'two'}}}});await change;assert.equal(directory.store.getSnapshot().current.model,'two');reads.shift().resolve({result:{ok:true,value:{current:{provider:'p',model:'one'},routable:true,groups:[],failures:[]}}});await stale;await tick();assert.equal(reads.length,1,'stale in-flight read cannot swallow pending refresh');assert.equal(directory.store.getSnapshot().current.model,'two');reads.shift().resolve({result:{ok:true,value:{current:{provider:'p',model:'two'},routable:true,groups:lastGroups,failures:[]}}});await invalidation;
saveFailure=true;const selected=directory.select({provider:'p',model:'one'});await tick();writes.shift().resolve({result:{ok:true,value:{selected:{provider:'p',model:'one'}}}});await selected;assert.equal(directory.store.getSnapshot().status,'ready');assert.match(directory.store.getSnapshot().error,/default could not be saved/);directory.resetConnected();assert.equal(directory.store.getSnapshot().current.model,'one');assert.equal(directory.store.getSnapshot().groups,lastGroups);await tick();reads.shift().reject(Error('reconnecting'));await tick();assert.equal(directory.store.getSnapshot().current.model,'one');
console.log('PASS model directory: stale read/write race, coalescing, failures, reconnect, committed selection/default-write distinction');
const h=preferenceHelpers(),catalog={provider:'p',accountScope:'account-a',settingsNs:'llm-pi-ai',settingsPath:['providers','p'],preferencePath:['providers','p','modelPreferences','account-a'],namespaceRevision:3,profileModels:[],preferences:{},models:[{id:'one',name:'Remote',contextWindow:128000,enabled:true},{id:'two',enabled:true}]};
const changes={one:{enabled:{base:undefined,effectiveBase:true,value:false},name:{base:undefined,effectiveBase:'Remote',value:'My name'}}};let saved;
await h.savePreferenceDraft({provider:'p',accountScope:'account-a',changes,manual:[],read:async()=>({...catalog,models:[{...catalog.models[0],contextWindow:256000}]}),write:async value=>{saved=value;return{result:{ok:true}}}});assert.equal(saved.ops.length,2);assert.equal(saved.ops.some(op=>op.path.includes('contextWindow')),false);assert.deepEqual(clone(saved.ops[0].path),['providers','p','modelPreferences','account-a','one','enabled']);
assert.equal(h.preferenceOps({...catalog,preferences:{one:{name:'Remote',enabled:true}}},changes,[]).length,2,'legacy migration of unchanged effective values does not create a false conflict');
let readCount=0,writeCount=0;await h.savePreferenceDraft({provider:'p',accountScope:'account-a',changes,manual:[],read:async()=>({...catalog,namespaceRevision:++readCount,preferences:readCount===1?{}:{two:{enabled:false}}}),write:async()=>({result:++writeCount===1?{ok:false,error:{code:'settings-conflict'}}:{ok:true}})});assert.equal(writeCount,2);
await assert.rejects(h.savePreferenceDraft({provider:'p',accountScope:'account-a',changes,manual:[],read:async()=>({...catalog,preferences:{one:{name:'Someone else'}}}),write:async()=>{throw Error('must not write')}}),/modelPreferenceConflict/);
await assert.rejects(h.savePreferenceDraft({provider:'p',accountScope:'account-a',changes,manual:[],read:async()=>({...catalog,accountScope:'account-b'}),write:async()=>{throw Error('must not write')}}),/modelAccountChanged/);
const manualOps=h.preferenceOps(catalog,{},[{id:'new',enabled:false,_draftId:'draft-1'}]);assert.equal(manualOps[0].value[0].accountScope,'account-a');assert.equal(manualOps[0].value[0]._draftId,undefined);assert.equal(manualOps[0].value[0].source,'manual');assert.equal(h.draftModelRows({...catalog,models:[]},changes,[])[0].name,'My name');
console.log('PASS model preferences: field-level writes, unrelated revision rebase, same-field conflict, account switch, manual account scope, refreshed catalog');
const {Session,SessionManager}=runtimeClasses(),manager=Object.create(SessionManager.prototype);Object.assign(manager,{summaries:[{sessionId:'keep',updatedAt:1,blank:false,running:false,title:'Keep me'}],selected:'keep',sessions:new Map(),projectionStores:new Map(),pendingInteractions:new Map(),completedNotifications:new Set(),entryCache:new Map(),itemsCache:[],addresses:new Map(),catalogs:new Map(),jobsBySession:new Map(),listState:'ready',listPhase:'ready',listError:null,listMutations:null,syncCompletedNotifications(){},notifier:{markDirty(){}}});let list=manager.buildListSnapshot();assert.equal(list.current,'keep');const entry=list.items[0];manager.summaries=[];list=manager.buildListSnapshot();assert.equal(list.current,'keep');assert.equal(list.items[0],entry,'same selected entry retains mounted scope');manager.recordMutation({kind:'remove',sessionId:'keep'});assert.equal(manager.buildListSnapshot().current,undefined);assert.equal(manager.buildListSnapshot().items.length,0,'explicit deletion is respected');
const session=Object.create(Session.prototype),events=[{seq:30},{seq:31}];Object.assign(session,{openState:'open',openGeneration:0,openPromise:null,openError:null,events,views:[{},{}],baseSeq:30,historyTargetSeq:31,historyPages:[{},{}],pending:new Map(),pendingRev:0,liveBuffer:[],notifier:{markDirty(){}},loadingOlder:false,loadingNewer:false,subscribedLastSeq:200,windowTailSeq(){return this.events.at(-1)?.seq},installWindow(entries,more,projections,state){this.events=entries.map(entry=>entry.event);this.installedState=state},open(){return this.doOpen(this.openGeneration)}});let requests=[];session.history=async request=>{requests.push(request);return{result:{ok:true,value:{events:[{event:{seq:30}},{event:{seq:31}}],hasMore:true,hasMoreBefore:true,hasMoreAfter:true}}}};await session.resync();assert.equal(session.historyTargetSeq,31);assert.equal(requests.length,1);assert.equal(requests[0].afterSeq,30);assert.equal(requests[0].maxMessages,24);assert.equal(session.installedState.hasMoreAfter,true);session.historyTargetSeq=null;session.rememberReadingPosition(true);session.openState='open';requests=[];await session.resync();assert.equal(requests[0].afterSeq,30,'ordinary upward scroll retains loaded history on reconnect');assert.equal(session.historyTargetSeq,30);const retained=session.events;session.history=async()=>{throw Error('offline')};await session.resync();assert.equal(session.events,retained);assert.equal(session.openState,'error');assert.equal(session.historyTargetSeq,30);
session.openState='open';let staleHistory=defer();session.history=()=>staleHistory.promise;const around=session.loadAround(100,true);session.openGeneration++;staleHistory.resolve({result:{ok:true,value:{events:[]}}});assert.equal(await around,false);assert.equal(session.events,retained);staleHistory=defer();const latest=session.returnLatest();session.openGeneration++;session.stitching=false;staleHistory.resolve({result:{ok:true,value:{events:[],hasMore:false}}});await latest;assert.equal(session.events,retained,'old return-latest response cannot replace reconnected history');
console.log('PASS session continuity: transient list gaps retain scope; explicit deletion clears; historical reconnect uses anchor; failure retains window');
}
if(require.main===module)run().catch(error=>{console.error(error);process.exitCode=1});
module.exports={preferenceHelpers,directoryClass,runtimeClasses,plugins};
