const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
function snapshotStore(initial){let value=initial;const listeners=new Set();return{getSnapshot:()=>value,subscribe:listener=>{listeners.add(listener);return()=>listeners.delete(listener)},update:change=>{const next={...value};change(next);value=next;for(const listener of listeners)listener()}}}
function loadSelectionModule(source,React,jsx,document){let exported;const primitives=new Proxy({Toast:()=>null},{get:(object,key)=>object[key]||((props)=>React.createElement('svg',props))});const context={document,Node:document.defaultView.Node,queueMicrotask,setTimeout,clearTimeout,console,window:{__ModuleLoader__:{load:def=>{exported=def.factory(id=>id==='react'?React:id==='react/jsx-runtime'?jsx:id==='@deepseek-ai/cordis'?{Service:class{}}:id.endsWith('/client')?{createSnapshotStore:snapshotStore}:primitives)}}}};assert.ok(source.includes('exports.ModelDirectory = ModelDirectory;'));vm.runInNewContext(source.replace('exports.ModelDirectory = ModelDirectory;','exports.ModelSelect=ModelSelect;exports.zh=zh;exports.en=en;exports.ModelDirectory = ModelDirectory;'),context);return exported}
function translator(dictionary){return(key,values={})=>Object.entries(values).reduce((text,[name,value])=>text.replaceAll('{'+name+'}',String(value)),dictionary[key]??key)}
async function run(modules){
 const {JSDOM}=require(path.join(modules,'jsdom')),dom=new JSDOM('<!doctype html><html><head></head><body><main id="root"></main></body></html>',{url:'http://fixture.invalid'});Object.assign(global,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});
 const React=require(path.join(modules,'react')),jsx=require(path.join(modules,'react/jsx-runtime')),ReactDOM=require(path.join(modules,'react-dom/client')),source=fs.readFileSync(path.join(__dirname,'../../web/dist/plugins/ui-model-selection.js'),'utf8'),plugin=loadSelectionModule(source,React,jsx,document),t=translator(plugin.zh);
 let reply={current:{provider:'fixture',model:'fixture-one'},routable:true,groups:[{id:'fixture',name:'Fixture',models:[{id:'fixture-one',name:'Fixture One'},{id:'fixture-two',name:'Fixture Two'}]}],failures:[]};
 const create=()=>new plugin.ModelDirectory({models:async()=>({result:{ok:true,value:structuredClone(reply)}})},'session',()=>true,async()=>{});
 let directory=create(),root=ReactDOM.createRoot(document.getElementById('root'));const refresh=async()=>React.act(async()=>directory.refresh());const render=async()=>{const load=()=>directory.load().catch(()=>{});await React.act(async()=>{root.render(React.createElement(plugin.ModelSelect,{locked:false,available:true,directory:directory.store,load,select:async()=>true,t}));await new Promise(resolve=>setImmediate(resolve))});await React.act(async()=>{await new Promise(resolve=>setImmediate(resolve))})};const trigger=()=>document.querySelector('button[aria-haspopup=menu]');
 await render();assert.equal(trigger().textContent,'Fixture One');reply={...reply,groups:[{id:'fixture',name:'Fixture',models:[{id:'fixture-two',name:'Fixture Two'}]}]};await refresh();assert.equal(trigger().textContent,'Fixture One · 已隐藏');assert.equal(trigger().dataset.currentModelState,'hidden');assert.match(trigger().getAttribute('aria-label'),/Fixture One.*已隐藏/);
 await React.act(async()=>trigger().click());await React.act(async()=>document.querySelector('[role=menuitem]').click());assert.deepEqual([...document.querySelectorAll('[role=menuitemradio]')].map(node=>node.textContent),['Fixture Two'],'hidden current model is a label, never a selectable candidate');
 await React.act(async()=>root.unmount());root=ReactDOM.createRoot(document.getElementById('root'));await render();assert.equal(trigger().textContent,'Fixture One · 已隐藏','known name survives a component remount');
 reply={...reply,routable:false};await refresh();assert.equal(trigger().textContent,'Fixture One · 不可用');assert.equal(trigger().dataset.currentModelState,'unavailable');assert.equal(trigger().textContent.includes('已隐藏'),false);
 reply={...reply,routable:true,failures:[{id:'fixture',name:'Fixture',message:'directory offline'}]};await refresh();assert.equal(trigger().textContent,'Fixture One');assert.equal(trigger().dataset.currentModelState,undefined,'a failed provider catalog is not classified as hidden');
 reply={...reply,failures:[]};await React.act(async()=>root.unmount());root=ReactDOM.createRoot(document.getElementById('root'));directory=create();await render();assert.equal(trigger().textContent,'fixture-one · 已隐藏','fresh reload retains model ID and hidden marker without a cached name');
 reply={...reply,current:{provider:'other',model:'fixture-one'}};await refresh();assert.equal(trigger().textContent,'fixture-one · 已隐藏','a different provider cannot reuse the previous friendly name');reply={...reply,current:null,routable:false};await refresh();assert.equal(trigger().textContent,'选择模型');assert.equal(trigger().dataset.currentModelState,undefined);
 await React.act(async()=>root.unmount());console.log('PASS React DOM current model label: preserved known name; hidden marker after hide/remount/fresh load; hidden row excluded from candidates; explicit unavailable and failed catalog retained; unset fallback preserved');
}
if(require.main===module){const modules=process.env.DSH_REACT_TEST_MODULES||process.argv[2];if(!modules)throw Error('Pass react/react-dom/jsdom node_modules');run(modules).catch(error=>{console.error(error);process.exitCode=1})}
module.exports={loadSelectionModule,snapshotStore,translator,run};
