const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const moduleRoot=process.env.DSH_REACT_TEST_MODULES||process.argv[2];
if(!moduleRoot)throw Error('Pass the temporary node_modules directory containing react, react-dom and jsdom');
const React=require(path.join(moduleRoot,'react')),jsx=require(path.join(moduleRoot,'react/jsx-runtime')),{JSDOM}=require(path.join(moduleRoot,'jsdom'));
const dom=new JSDOM('<!doctype html><html><head></head><body><main id="root"></main></body></html>',{url:'http://fixture.invalid'});
Object.assign(global,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});
const ReactDOM=require(path.join(moduleRoot,'react-dom/client'));
const plugins=path.resolve(__dirname,'../../web/dist/plugins'),source=fs.readFileSync(path.join(plugins,'ui-settings-models.js'),'utf8');
const clone=x=>JSON.parse(JSON.stringify(x));
let catalog={provider:'fixture',accountScope:'a',settingsNs:'llm-pi-ai',settingsPath:['providers','fixture'],preferencePath:['providers','fixture','modelPreferences','a'],namespaceRevision:1,preferences:{},profileModels:[],models:[{id:'one',name:'One',enabled:true,contextWindow:131072},{id:'two',name:'Two',enabled:true}]};
let writeError=null,writes=[],readError=null,apiCalls=[],startPending=null,accountRows=[{id:'fixture',name:'Account',signedIn:true,settingsNs:'llm-pi-ai'}];let freeReport={models:[{provider:'opencode-free',model:'free-one',status:'pending',available:false,freePricingVerified:true,verifiedAt:null}]};
function mergeOps(ops){for(const op of ops){let target=catalog.preferences;const tail=op.path.slice(4);for(const part of tail.slice(0,-1))target=target[part]??={};if(op.op==='unset')delete target[tail.at(-1)];else target[tail.at(-1)]=op.value;}catalog.namespaceRevision++;catalog.models=catalog.models.map(row=>({...row,...catalog.preferences[row.id]}));}
let exported;const context={document,window:{__ModuleLoader__:{load(def){exported=def.factory(id=>id==='react'?React:id==='react/jsx-runtime'?jsx:id.endsWith('ui-primitives')?{IconCheckOutline14:()=>React.createElement('svg',{'data-check-icon':true})}: {})}}},fetch:async(url,init)=>{const action=url.split('/').at(-1),body=init.body?JSON.parse(init.body):{};apiCalls.push({action,body});if(url.startsWith('/__dsh-free/')){if(action==='test')freeReport.models[0]={...freeReport.models[0],status:'available',available:true,verifiedAt:Date.now()};return{ok:true,json:async()=>clone(action==='enable'?{enabled:true,provider:'opencode-free',model:body.model}:freeReport)}};if(readError)throw readError;if(action==='providers')return{ok:true,json:async()=>({providers:accountRows})};if(action==='start'&&startPending)return startPending.promise;if(action==='cancel')return{ok:true,json:async()=>({status:'cancelled'})};return{ok:true,json:async()=>clone(catalog)}},setTimeout,clearTimeout,structuredClone,console};
vm.runInNewContext(source.replace('return module.exports;','exports.test={ProviderModelManager,AccountConnections,ModelEditorBoundary,ProviderEditor,Loaded,FreeModelsSection,zh,en};return module.exports;'),context);
const test=exported.test,t=key=>test.en[key]??key,api={settings:{mutate:async request=>{writes.push(request);if(writeError)return{result:{ok:false,error:{code:'write-error',message:writeError}}};mergeOps(request.ops);return{result:{ok:true,value:{}}}}}};
let root=ReactDOM.createRoot(document.getElementById('root'));const {act}=React;
const flush=async()=>act(async()=>{await new Promise(resolve=>setImmediate(resolve))});
async function render(element){await act(async()=>root.render(element));await flush()}
async function click(label){const button=[...document.querySelectorAll('button')].find(node=>node.textContent===label);assert.ok(button,'button '+label);await act(async()=>button.click());await flush()}
async function check(id,value){const node=document.querySelector(`[data-model-id="${id}"] input[type=checkbox]`);assert.ok(node);assert.equal(node.checked,!value);await act(async()=>node.click());await flush()}
async function input(selector,value){const node=document.querySelector(selector);assert.ok(node,selector);await act(async()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set.call(node,value);node.dispatchEvent(new dom.window.Event('input',{bubbles:true}))});await flush()}
async function main(){
const props={provider:'fixture',api,t,disabled:false,revision:1};
await render(React.createElement(test.ProviderModelManager,props));assert.equal(document.querySelectorAll('[data-model-id]').length,2);assert.equal(document.querySelectorAll('[data-check-icon]').length,2);assert.equal(document.querySelector('input[type=checkbox]').getAttribute('role'),null,'real checkbox semantics, original-token visible box');
await check('one',false);assert.equal(writes.length,0,'toggle is draft until Apply');await click(t('cancel'));assert.equal(document.querySelector('[data-model-id=one] input').checked,true);assert.equal(writes.length,0);
await check('one',false);catalog.models[0].contextWindow=262144;await render(React.createElement(test.ProviderModelManager,{...props,revision:2}));assert.equal(document.querySelector('[data-model-id=one] input').checked,false,'remote metadata update preserves draft');await click(t('apply'));assert.equal(writes.length,1);assert.deepEqual(clone(writes[0].ops.map(op=>op.path.at(-1))),['enabled']);assert.equal(catalog.models[0].contextWindow,262144);assert.equal(document.querySelector('[data-model-id=one] input').checked,false);
await act(async()=>root.unmount());root=ReactDOM.createRoot(document.getElementById('root'));await render(React.createElement(test.ProviderModelManager,props));assert.equal(document.querySelector('[data-model-id=one] input').checked,false,'remount rereads persisted preference');
await click(t('modelManage'));await input('input[type=search]','Two');assert.equal(document.querySelectorAll('[data-model-id]').length,1);assert.ok(document.querySelector('[data-model-id=two]'));await click(t('modelHideFiltered'));await input('input[type=search]','');assert.equal(document.querySelector('[data-model-id=two] input').checked,false);writeError='disk unavailable';await click(t('apply'));assert.equal(document.querySelector('[data-model-id=two] input').checked,false);assert.match(document.body.textContent,/disk unavailable/);writeError=null;await click(t('apply'));assert.equal(catalog.preferences.two.enabled,false);
await input('input[aria-label="one contextWindow"]','128 K');assert.equal(document.querySelector('input[aria-label="one contextWindow"]').value,'128 K');await input('input[aria-label="one contextWindow"]','invalid capacity');assert.equal([...document.querySelectorAll('button')].find(node=>node.textContent===t('apply')).disabled,true);await render(React.createElement(test.ProviderModelManager,{...props,revision:5}));assert.equal(document.querySelector('input[aria-label="one contextWindow"]').value,'invalid capacity');await click(t('cancel'));
await check('one',true);catalog={...catalog,accountScope:'b',preferencePath:['providers','fixture','modelPreferences','b'],preferences:{}};await render(React.createElement(test.ProviderModelManager,{...props,revision:3}));assert.match(document.body.textContent,/account changed/i);assert.equal(document.querySelector('[data-model-id=one] input').disabled,true);await click(t('cancel'));assert.equal(document.querySelector('[data-model-id=one] input').disabled,false);
readError=Error('offline');await render(React.createElement(test.ProviderModelManager,{...props,revision:4}));assert.equal(document.querySelectorAll('[data-model-id]').length,2,'network failure keeps last good rows');assert.match(document.body.textContent,/offline/);readError=null;
await render(React.createElement(test.AccountConnections,{controller:{load:async()=>{}},api,namespaces:new Map(),t,disabled:false}));assert.ok(document.querySelector('[data-model-manager=fixture]'),'signed-in account exposes its model manager');assert.equal(document.querySelectorAll('input[type=password]').length,0,'account connection never exposes API-key editing');
accountRows=[{id:'fixture',name:'Account',signedIn:false,settingsNs:'llm-pi-ai'}];await render(React.createElement('span',null,'reopen account settings'));let resolveStart;startPending={promise:new Promise(resolve=>{resolveStart=resolve})};await render(React.createElement(test.AccountConnections,{controller:{load:async()=>{}},api,namespaces:new Map(),t,disabled:false}));const starts=apiCalls.filter(call=>call.action==='start').length;await act(async()=>{const login=[...document.querySelectorAll('button')].find(node=>node.textContent===t('accountLogin'));login.click();login.click()});assert.equal(apiCalls.filter(call=>call.action==='start').length-starts,1,'rapid login clicks start one attempt');await render(React.createElement('span',null,'account settings closed'));resolveStart({ok:true,json:async()=>({attempt:'late-auth-attempt',interval:99,verificationUri:'https://fixture.invalid/authorize'})});await flush();await flush();assert.ok(apiCalls.some(call=>call.action==='cancel'&&call.body.attempt==='late-auth-attempt'),'late start is cancelled after settings unmount');startPending=null;
freeReport={models:[],refreshing:true};await render(React.createElement(test.FreeModelsSection,{key:'empty-refresh',controller:{load:async()=>{}},t}));assert.ok(document.body.textContent.includes(t('freeReading')),'empty initial refresh announces directory loading');assert.equal(document.body.textContent.includes(t('modelNoMatches')),false);
freeReport={models:[{provider:null,api:null,model:'unknown-model',status:'pending',available:false,freePricingVerified:false,verifiedAt:null}],refreshing:false};await render(React.createElement(test.FreeModelsSection,{key:'unknown',controller:{load:async()=>{}},t}));const unknownIdentity=document.querySelector('[data-free-model="unknown-model"] .dshModelId').textContent;assert.equal(unknownIdentity,'OpenCode Zen / unknown-model · '+t('freeProtocolPending'));assert.equal(/null|undefined/.test(unknownIdentity),false);assert.ok(document.body.textContent.includes('Free model candidates'));assert.equal([...document.querySelectorAll('button')].find(node=>node.textContent===t('freeTest')).disabled,true,'unverified pricing remains gated');assert.equal([...document.querySelectorAll('button')].find(node=>node.textContent===t('freeEnable')).disabled,true);
freeReport={models:[],refreshing:false};await render(React.createElement(test.FreeModelsSection,{key:'empty-ready',controller:{load:async()=>{}},t}));assert.ok(document.body.textContent.includes(t('modelNoMatches')));assert.equal(document.body.textContent.includes(t('freeReading')),false);
freeReport={models:[{provider:'opencode-free',model:'free-one',status:'pending',available:false,freePricingVerified:true,verifiedAt:null}]};
await render(React.createElement(test.FreeModelsSection,{controller:{load:async()=>{}},t}));assert.equal([...document.querySelectorAll('button')].find(node=>node.textContent===t('freeEnable')).disabled,true);const beforeFree=apiCalls.length;await click(t('freeRefresh'));assert.equal(apiCalls.slice(beforeFree).some(call=>call.action==='test'),false,'directory refresh never triggers inference');await click(t('freeTest'));assert.equal([...document.querySelectorAll('button')].find(node=>node.textContent===t('freeEnable')).disabled,false);await click(t('freeEnable'));assert.equal(apiCalls.find(call=>call.action==='enable').body.model,'free-one');
function Broken(){throw Error('schema fixture failure')};const previousError=console.error;console.error=()=>{};await render(React.createElement(React.Fragment,null,React.createElement('article',{'data-session-body':true},'Durable conversation'),React.createElement(test.ModelEditorBoundary,{t},React.createElement(Broken))));console.error=previousError;assert.match(document.querySelector('[data-session-body]').textContent,/Durable/);assert.match(document.body.textContent,/schema fixture failure/);
assert.ok(document.querySelector('style[data-dsh-model-manager]').textContent.includes('input:focus-visible+.dshModelCheckBox'));
await act(async()=>root.unmount());console.log('PASS React DOM: visible checkboxes; cancel/save; refresh draft preservation; remount persistence; bulk changes; failed write retry; account-switch isolation; read failure retention; search; invalid capacity draft; signed-in account model manager; gated free test/enable; local error boundary protects conversation');
}
main().then(()=>require('./model_current_label_dom_harness.cjs').run(moduleRoot)).catch(error=>{console.error(error);process.exitCode=1});
