const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const moduleRoot=process.env.DSH_REACT_TEST_MODULES||process.argv[2];
if(!moduleRoot)throw Error('Pass the temporary node_modules directory containing react, react-dom and jsdom');
const React=require(path.join(moduleRoot,'react')),jsx=require(path.join(moduleRoot,'react/jsx-runtime')),{JSDOM}=require(path.join(moduleRoot,'jsdom'));
const dom=new JSDOM('<!doctype html><html><head></head><body><main id="root"></main></body></html>',{url:'http://fixture.invalid'});
Object.assign(global,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});
const ReactDOM=require(path.join(moduleRoot,'react-dom/client'));
const plugins=path.resolve(__dirname,'../../web/dist/plugins'),source=fs.readFileSync(process.env.DSH_MODEL_SETTINGS_SOURCE||path.join(plugins,'ui-settings-models.js'),'utf8');
const clone=x=>JSON.parse(JSON.stringify(x));
let catalog={provider:'fixture',accountScope:'a',settingsNs:'llm-pi-ai',settingsPath:['providers','fixture'],preferencePath:['providers','fixture','modelPreferences','a'],namespaceRevision:1,preferences:{},profileModels:[],models:[{id:'one',name:'One',enabled:true,contextWindow:131072},{id:'two',name:'Two',enabled:true}]};
let writeError=null,writes=[],readError=null,apiCalls=[],startPending=null,usageReply=null,accountRows=[{id:'fixture',name:'Account',signedIn:true,settingsNs:'llm-pi-ai'}];let freeReport={models:[{provider:'opencode-free',model:'free-one',status:'pending',available:false,freePricingVerified:true,verifiedAt:null}]};
function mergeOps(ops){for(const op of ops){if(JSON.stringify(op.path)===JSON.stringify([...catalog.settingsPath,'models'])){catalog.profileModels=clone(op.value);continue;}assert.deepEqual(clone(op.path.slice(0,catalog.preferencePath.length)),catalog.preferencePath);let target=catalog.preferences;const tail=op.path.slice(catalog.preferencePath.length);for(const part of tail.slice(0,-1))target=target[part]??={};if(op.op==='unset')delete target[tail.at(-1)];else target[tail.at(-1)]=op.value;}catalog.namespaceRevision++;const known=catalog.models.filter(row=>row.source!=='manual'),knownIds=new Set(known.map(row=>row.id));catalog.models=[...known,...catalog.profileModels.filter(row=>!knownIds.has(row.id)&&(!row.accountScope||row.accountScope===catalog.accountScope))].map(row=>({...row,name:row.name||row.id,...catalog.preferences[row.id]}));}
function snapshotStore(initial){let value=initial;const listeners=new Set();const set=next=>{value=next;for(const fn of listeners)fn()};return {getSnapshot:()=>value,subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn)},set,update:fn=>{const next={...value};fn(next);set(next)}}}
let providersReply=null,accountActionReply=null;
const primitives=new Proxy({IconCheckOutline14:()=>React.createElement('svg',{'data-check-icon':true}),Modal:({open,children,footer,title})=>open?React.createElement('section',{role:'dialog','aria-label':title},children,footer):null,Button:({variant,...props})=>React.createElement('button',props)},{get:(target,key)=>target[key]??(()=>React.createElement('svg',{'data-icon':key}))});
let exported;const context={document,window:{__ModuleLoader__:{load(def){exported=def.factory(id=>id==='react'?React:id==='react/jsx-runtime'?jsx:id.endsWith('ui-primitives')?primitives:id.endsWith('schema-form')?{getPath:(value,parts)=>parts.reduce((current,key)=>current?.[key],value),rehydrateSchema:value=>value,nodeAtPath:()=>null}: {createSnapshotStore:snapshotStore})}}},fetch:async(url,init)=>{const action=url.split('/').at(-1),body=init.body?JSON.parse(init.body):{};apiCalls.push({action,body});if(accountActionReply&&['switch','logout','start','poll'].includes(action))return accountActionReply(action,body);if(usageReply&&['usage','usage-login'].includes(action))return usageReply(action);if(url.startsWith('/__dsh-free/')){if(action==='test')freeReport.models[0]={...freeReport.models[0],status:'available',available:true,verifiedAt:Date.now()};return{ok:true,json:async()=>clone(action==='enable'?{enabled:true,provider:'opencode-free',model:body.model}:freeReport)}};if(readError)throw readError;if(action==='providers'&&providersReply)return providersReply();if(action==='reset-prepare')return{ok:true,json:async()=>({operation:{operationId:'fixture-reset',state:'prepared'}})};if(action==='reset-consume'){assert.equal(body.confirmed,true);assert.equal(body.operationId,'fixture-reset');return{ok:true,json:async()=>({operation:{operationId:'fixture-reset',state:'complete',outcome:'reset'}})}};if(action==='providers')return{ok:true,json:async()=>({providers:accountRows})};if(action==='start'&&startPending)return startPending.promise;if(action==='cancel')return{ok:true,json:async()=>({status:'cancelled'})};return{ok:true,json:async()=>clone(catalog)}},setTimeout,clearTimeout,setInterval,clearInterval,structuredClone,console};
vm.runInNewContext(source.replace('return module.exports;','exports.test={ProviderModelManager,CodexUsagePanel,AccountConnections,ModelEditorBoundary,ProviderEditor,Loaded,FreeModelsSection,createAccountDirectory,SidebarAccount,zh,en};return module.exports;'),context);
const test=exported.test,t=key=>test.en[key]??key,api={settings:{mutate:async request=>{writes.push(request);if(writeError)return{result:{ok:false,error:{code:'write-error',message:writeError}}};mergeOps(request.ops);return{result:{ok:true,value:{}}}}}};
const makeController=()=>({load:async()=>{},accounts:test.createAccountDirectory()});
async function expandAccounts(name){await act(async()=>document.querySelector('.dshAccountDisclosure').click());await click(name)}
let root=ReactDOM.createRoot(document.getElementById('root'));const {act}=React;
const flush=async()=>act(async()=>{await new Promise(resolve=>setImmediate(resolve))});
async function render(element){await act(async()=>root.render(element));await flush()}
async function click(label){const button=[...document.querySelectorAll('button')].find(node=>node.textContent===label);assert.ok(button,'button '+label);await act(async()=>button.click());await flush()}
async function check(id,value){const node=document.querySelector(`[data-model-id="${id}"] input[type=checkbox]`);assert.ok(node);assert.equal(node.checked,!value);await act(async()=>node.click());await flush()}
async function input(selector,value){const node=document.querySelector(selector);assert.ok(node,selector);await act(async()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set.call(node,value);node.dispatchEvent(new dom.window.Event('input',{bubbles:true}))});await flush()}
async function main(){
const props={provider:'fixture',api,t,disabled:false,revision:1};
await render(React.createElement(test.ProviderModelManager,props));assert.equal(document.querySelectorAll('[data-model-id]').length,2);assert.equal(document.querySelectorAll('[data-check-icon]').length,2);assert.equal(document.querySelector('input[type=checkbox]').getAttribute('role'),null,'real checkbox semantics, original-token visible box');
await check('one',false);assert.equal(writes.length,0,'toggle is draft until Apply');await click(t('cancel'));assert.equal(document.querySelector('[data-model-id=one] input').checked,true);assert.equal(writes.length,0);
await check('one',false);catalog.models[0].contextWindow=262144;await render(React.createElement(test.ProviderModelManager,{...props,revision:2}));assert.equal(document.querySelector('[data-model-id=one] input').checked,false,'remote metadata update preserves draft');await click(t('apply'));assert.equal(writes.length,1);assert.deepEqual(clone(writes[0].ops.map(op=>op.path.at(-1))),['enabled']);assert.equal(catalog.models[0].contextWindow,262144);assert.equal(document.querySelector('[data-model-id=one] input').checked,false);
await act(async()=>root.unmount());root=ReactDOM.createRoot(document.getElementById('root'));await render(React.createElement(test.ProviderModelManager,props));assert.equal(document.querySelector('[data-model-id=one] input').checked,false,'remount rereads persisted preference');
await click(t('modelManage'));await input('input[type=search]','Two');assert.equal(document.querySelectorAll('[data-model-id]').length,1);assert.ok(document.querySelector('[data-model-id=two]'));await click(t('modelHideFiltered'));await input('input[type=search]','');assert.equal(document.querySelector('[data-model-id=two] input').checked,false);writeError='disk unavailable';await click(t('apply'));assert.equal(document.querySelector('[data-model-id=two] input').checked,false);assert.match(document.body.textContent,/disk unavailable/);writeError=null;await click(t('apply'));assert.equal(catalog.preferences.two.enabled,false);
await input('input[aria-label="one contextWindow"]','128 K');assert.equal(document.querySelector('input[aria-label="one contextWindow"]').value,'128 K');await input('input[aria-label="one contextWindow"]','invalid capacity');assert.equal([...document.querySelectorAll('button')].find(node=>node.textContent===t('apply')).disabled,true);await render(React.createElement(test.ProviderModelManager,{...props,revision:5}));assert.equal(document.querySelector('input[aria-label="one contextWindow"]').value,'invalid capacity');await click(t('cancel'));
await check('one',true);catalog={...catalog,accountScope:'b',preferencePath:['providers','fixture','modelPreferences','b'],preferences:{}};await render(React.createElement(test.ProviderModelManager,{...props,revision:3}));assert.match(document.body.textContent,/account changed/i);assert.equal(document.querySelector('[data-model-id=one] input').disabled,true);await click(t('cancel'));assert.equal(document.querySelector('[data-model-id=one] input').disabled,false);
readError=Error('offline');await render(React.createElement(test.ProviderModelManager,{...props,revision:4}));assert.equal(document.querySelectorAll('[data-model-id]').length,2,'network failure keeps last good rows');assert.match(document.body.textContent,/offline/);readError=null;
await render(React.createElement(test.AccountConnections,{controller:makeController(),api,namespaces:new Map(),t,disabled:false}));assert.equal(document.querySelector('[data-model-manager=fixture]'),null,'account model details stay unmounted until expanded');await expandAccounts('Account');assert.ok(document.querySelector('[data-model-manager=fixture]'),'signed-in account exposes its model manager');assert.equal(document.querySelectorAll('input[type=password]').length,0,'account connection never exposes API-key editing');
accountRows=[{id:'fixture',name:'Account',signedIn:false,settingsNs:'llm-pi-ai'}];await render(React.createElement('span',null,'reopen account settings'));let resolveStart;startPending={promise:new Promise(resolve=>{resolveStart=resolve})};await render(React.createElement(test.AccountConnections,{controller:makeController(),api,namespaces:new Map(),t,disabled:false}));await expandAccounts('Account');const starts=apiCalls.filter(call=>call.action==='start').length;await act(async()=>{const login=[...document.querySelectorAll('button')].find(node=>node.textContent===t('accountLogin'));login.click();login.click()});assert.equal(apiCalls.filter(call=>call.action==='start').length-starts,1,'rapid login clicks start one attempt');await render(React.createElement('span',null,'account settings closed'));resolveStart({ok:true,json:async()=>({attempt:'late-auth-attempt',interval:99,verificationUri:'https://fixture.invalid/authorize'})});await flush();await flush();assert.ok(apiCalls.some(call=>call.action==='cancel'&&call.body.attempt==='late-auth-attempt'),'late start is cancelled after settings unmount');startPending=null;
freeReport={models:[],refreshing:true};await render(React.createElement(test.FreeModelsSection,{key:'empty-refresh',controller:makeController(),t}));assert.ok(document.body.textContent.includes(t('freeReading')),'empty initial refresh announces directory loading');assert.equal(document.body.textContent.includes(t('modelNoMatches')),false);
freeReport={models:[{provider:null,api:null,model:'unknown-model',status:'pending',available:false,freePricingVerified:false,verifiedAt:null}],refreshing:false};await render(React.createElement(test.FreeModelsSection,{key:'unknown',controller:makeController(),t}));const unknownIdentity=document.querySelector('[data-free-model="unknown-model"] .dshModelId').textContent;assert.equal(unknownIdentity,'OpenCode Zen / unknown-model · '+t('freeProtocolPending'));assert.equal(/null|undefined/.test(unknownIdentity),false);assert.ok(document.body.textContent.includes('Free model candidates'));assert.equal([...document.querySelectorAll('button')].find(node=>node.textContent===t('freeTest')).disabled,true,'unverified pricing remains gated');assert.equal([...document.querySelectorAll('button')].find(node=>node.textContent===t('freeEnable')).disabled,true);
freeReport={models:[],refreshing:false};await render(React.createElement(test.FreeModelsSection,{key:'empty-ready',controller:makeController(),t}));assert.ok(document.body.textContent.includes(t('modelNoMatches')));assert.equal(document.body.textContent.includes(t('freeReading')),false);
freeReport={models:[{provider:'opencode-free',model:'free-one',status:'pending',available:false,freePricingVerified:true,verifiedAt:null}]};
await render(React.createElement(test.FreeModelsSection,{controller:makeController(),t}));assert.equal([...document.querySelectorAll('button')].find(node=>node.textContent===t('freeEnable')).disabled,true);const beforeFree=apiCalls.length;await click(t('freeRefresh'));assert.equal(apiCalls.slice(beforeFree).some(call=>call.action==='test'),false,'directory refresh never triggers inference');await click(t('freeTest'));assert.equal([...document.querySelectorAll('button')].find(node=>node.textContent===t('freeEnable')).disabled,false);await click(t('freeEnable'));assert.equal(apiCalls.find(call=>call.action==='enable').body.model,'free-one');
const exactId='deepseek-v4.1-flash-expires-on-0910';
const builtins=[{id:'deepseek-v4-flash',name:'DeepSeek-V4-Flash'},{id:'deepseek-v4-pro',name:'DeepSeek-V4-Pro'},{id:'deepseek-v4-flash-vision-exp',name:'DeepSeek-V4-Flash-Vision-Exp'}];
catalog={provider:'deepseek-official',accountScope:'native-test',settingsNs:'llm-deepseek',settingsPath:[],preferencePath:['modelPreferences','native-test'],namespaceRevision:10,preferences:{},profileModels:clone(builtins),models:clone(builtins)};
const exactProps={provider:'deepseek-official',api,t,disabled:false,revision:10};
await render(React.createElement(test.ProviderModelManager,{...exactProps,key:'manual-model'}));
await click(t('modelManage'));await input('input[type=search]',exactId);assert.equal(document.querySelectorAll('[data-model-id]').length,0);
const beforeManual=writes.length;
await click(t('modelManualAdd'));
let draft=document.querySelector('[data-model-draft]');assert.ok(draft,'searching an absent ID cannot hide a newly added manual form');
let idInput=draft.querySelector('input[required]');assert.ok(idInput,'manual model ID is an actual editable field');assert.equal(idInput.closest('details'),null,'required ID is visible without opening Advanced');
assert.ok([...draft.querySelectorAll('input[type=text]')].some(node=>node.getAttribute('placeholder')===t('modelNamePlaceholder')&&!node.closest('details')),'optional display name is visible beside the required ID');
assert.equal([...document.querySelectorAll('button')].find(node=>node.textContent===t('apply')).disabled,true,'an empty manual ID cannot be submitted');assert.equal(writes.length,beforeManual);
await input('[data-model-draft] input[required]',exactId);await check(exactId,false);
writeError='manual model save failed';await click(t('apply'));assert.ok(document.querySelector('[data-model-draft]'));assert.equal(document.querySelector('[data-model-draft] input[required]').value,exactId);assert.ok(!catalog.models.some(model=>model.id===exactId),'failed persistence cannot be shown as saved');
writeError=null;await click(t('apply'));assert.equal(document.querySelector('[data-model-draft]'),null);
const manualWrite=clone(writes.at(-1));assert.equal(manualWrite.ns,'llm-deepseek');assert.deepEqual(manualWrite.ops[0].path,['models']);assert.deepEqual(manualWrite.ops[0].value.slice(0,3),builtins,'manual add preserves the inherited native catalog');
const stored=manualWrite.ops[0].value.at(-1);assert.equal(stored.id,exactId);assert.equal(stored.enabled,false);assert.equal(stored.accountScope,'native-test');assert.equal(stored.source,'manual');assert.equal(Object.hasOwn(stored,'name'),false,'optional blank display names use the exact model ID');
await render(React.createElement(test.ProviderModelManager,{...exactProps,key:'manual-remount'}));assert.equal(document.querySelector(`[data-model-id="${exactId}"] input[type=checkbox]`).checked,false,'saved visibility survives a fresh manager mount');
const Directory=require('./model_management_harness.cjs').directoryClass();
const directory=new Directory({models:async()=>({result:{ok:true,value:{current:{provider:'deepseek',model:builtins[0].id},routable:true,groups:[{models:catalog.models.filter(model=>model.enabled!==false)}],failures:[]}}})},'fixture-session',()=>true,async()=>{});
await directory.load();assert.ok(!directory.store.getSnapshot().groups.flatMap(group=>group.models).some(model=>model.id===exactId),'a saved hidden manual model is absent from the real model directory state');
await check(exactId,true);await click(t('apply'));
assert.deepEqual(clone(writes.at(-1).ops[0].path),['modelPreferences','native-test',exactId,'enabled'],'the dot and expiry suffix remain one literal settings path component');
await directory.load();assert.ok(directory.store.getSnapshot().groups.flatMap(group=>group.models).some(model=>model.id===exactId),'a saved visible manual model is selectable through the same directory');
await click(t('modelManage'));await input('input[type=search]',exactId);await click(t('modelManualAdd'));await input('[data-model-draft] input[required]',exactId);
assert.equal([...document.querySelectorAll('button')].find(node=>node.textContent===t('apply')).disabled,true,'duplicate IDs cannot replace an existing model');
const beforeRemove=writes.length;await click(t('modelManualRemove'));assert.equal(writes.length,beforeRemove,'removing an unsaved draft never deletes stored models');assert.ok(catalog.models.some(model=>model.id===exactId));
assert.ok(writes.slice(beforeManual).every(write=>write.ops.every(op=>op.path[0]==='models'||op.path[0]==='modelPreferences')),'manual model operations never touch provider credentials or connection fields');
const freshUsage={status:'fresh',updatedAt:1788800000,rateLimits:{limitId:'codex',primary:{usedPercent:35,windowDurationMins:300}},rateLimitResetCredits:{availableCount:0}};
let resolveOldUsage,usageSyncError=null,usageSynced=freshUsage;
usageReply=action=>action==='usage'?new Promise(resolve=>{resolveOldUsage=resolve}):usageSyncError?Promise.reject(Error(usageSyncError)):Promise.resolve({ok:true,json:async()=>clone(usageSynced)});
await render(React.createElement(test.CodexUsagePanel,{account:{accountScope:'usage-fixture'},disabled:false}));
await click('同步用量账号');assert.match(document.body.textContent,/剩余 65%/,'fresh sync response immediately renders existing-account usage');
assert.equal([...document.querySelectorAll('button')].find(node=>node.textContent==='Token 统计').disabled,false,'fresh usage unlocks available statistics');
assert.equal(document.body.textContent.includes('打开官方登录页'),false);assert.equal(document.querySelector('code'),null,'usage sync never fabricates a second device-code login');
resolveOldUsage({ok:true,json:async()=>({status:'stale',error:'old request',rateLimits:{limitId:'codex',primary:{usedPercent:99}}})});await flush();assert.match(document.body.textContent,/剩余 65%/,'pre-sync read cannot overwrite the synchronized account snapshot');assert.equal(document.body.textContent.includes('old request'),false);
usageSyncError='usage synchronization unavailable';await click('同步用量账号');assert.match(document.body.textContent,/usage synchronization unavailable/);assert.match(document.body.textContent,/剩余 65%/,'failed sync keeps the last displayed usage');
usageSyncError=null;usageSynced={...freshUsage,status:'stale',error:'usage data is stale'};await click('同步用量账号');assert.match(document.body.textContent,/数据待刷新/);assert.match(document.body.textContent,/usage data is stale/);assert.match(document.body.textContent,/剩余 65%/);assert.equal([...document.querySelectorAll('button')].find(node=>node.textContent==='Token 统计').disabled,true,'stale sync response cannot be presented as fresh');
usageReply=()=>Promise.resolve({ok:true,json:async()=>clone(freshUsage)});
const providerRow=id=>({configured:true,entry:{provider:id,displayName:'ChatGPT/Codex',settingsNs:'llm-pi-ai',settingsPath:['providers',id],active:true,declared:true},removable:true});
const loadedState={status:'ready',writable:true,rows:[providerRow('openai-codex'),providerRow('custom-codex')],namespaces:new Map([['llm-pi-ai',{revision:1,value:{providers:{'openai-codex':{authProvider:'openai-codex',models:[]},'custom-codex':{models:[]}}},schema:{}}]])};
const loadedProps={injected:{api,t,controller:makeController(),useSnapshot:select=>select(loadedState)}};
accountRows=[{id:'openai-codex',name:'ChatGPT/Codex',signedIn:true,settingsNs:'llm-pi-ai',accountScope:'usage-fixture'}];
await render(React.createElement(test.Loaded,{...loadedProps,key:'account-deduplication'}));await flush();await expandAccounts('ChatGPT/Codex');
assert.equal(document.querySelectorAll('[data-model-manager="openai-codex"]').length,1,'a connected account has one model manager, not another disabled provider copy');
assert.ok(document.querySelector('[data-model-manager="custom-codex"]'),'a custom provider with the same display name stays editable');
assert.ok([...document.querySelectorAll('button')].some(node=>node.getAttribute('aria-label')?.includes('custom-codex')&&!node.disabled),'same-label custom connection retains its edit action');
accountRows=[{...accountRows[0],signedIn:false}];await click(t('accountRefresh'));assert.equal(document.querySelectorAll('[data-model-manager="openai-codex"]').length,1,'signed-out account falls back to the configured provider manager');assert.ok(document.querySelector('[data-model-manager="openai-codex"]').closest('li'),'fallback is rendered in the provider list when the account manager is absent');
accountRows=[{...accountRows[0],signedIn:true,scope:'subagent'}];await click(t('accountRefresh'));assert.ok(document.querySelector('[data-model-manager="openai-codex"]').closest('li'),'subagent-only account cannot suppress the full provider fallback');
accountRows=[];await click(t('accountRefresh'));assert.ok(document.querySelector('[data-model-manager="openai-codex"]').closest('li'),'missing account data does not hide a configured provider');
await render(React.createElement('span',null,'mock reset confirmation'));
usageReply=()=>Promise.resolve({ok:true,json:async()=>({...freshUsage,rateLimitResetCredits:{availableCount:1}})});
await render(React.createElement(test.CodexUsagePanel,{account:{accountScope:'mock-reset',name:'Synthetic account'},disabled:false}));
const resetCalls=()=>apiCalls.filter(call=>call.action.startsWith('reset-'));
const beforeReset=resetCalls().length;await click('使用 1 张重置卡');
assert.ok(document.querySelector('[role=dialog]'));assert.equal(resetCalls().length,beforeReset,'opening confirmation never prepares a card');
await click('取消');assert.equal(resetCalls().length,beforeReset,'cancel performs no operation');
await click('使用 1 张重置卡');await click('确认使用 1 张');
assert.deepEqual(resetCalls().slice(beforeReset).map(row=>row.action),['reset-prepare','reset-consume']);
assert.match(document.body.textContent,/已使用 1 张重置卡/);
await render(React.createElement('span',null,'multiple accounts under one login provider'));
accountRows=[{id:'openai-codex',name:'ChatGPT/Codex',signedIn:true,settingsNs:'llm-pi-ai',accountScope:'account-a',accounts:[{accountScope:'account-a',accountId:'a',label:'first@example.invalid',active:true}]}];
catalog={...catalog,provider:'openai-codex',accountScope:'account-a',settingsNs:'llm-pi-ai',settingsPath:['providers','openai-codex'],preferencePath:['providers','openai-codex','modelPreferences','account-a'],models:[],preferences:{},profileModels:[]};
let switchError=false,modelLoads=0,modelLoadError=false;
accountActionReply=async(action,body)=>{
 assert.equal(body.provider??'openai-codex','openai-codex');
 if(action==='start')return{ok:true,json:async()=>({attempt:'second-account-login',userCode:'FIXTURE-CODE',verificationUri:'https://fixture.invalid/device',interval:3})};
 if(action==='poll'){accountRows=[{...accountRows[0],accountScope:'account-b',accounts:[{...accountRows[0].accounts[0],active:false},{accountScope:'account-b',accountId:'b',label:'second@example.invalid',active:true}]}];return{ok:true,json:async()=>({status:'complete'})};}
 if(action==='switch'){
  if(switchError)return{ok:false,status:400,json:async()=>({error:'Account switch failed'})};
  accountRows=accountRows.map(row=>({...row,accountScope:body.accountScope,accounts:row.accounts.map(item=>({...item,active:item.accountScope===body.accountScope}))}));
  catalog={...catalog,accountScope:body.accountScope,preferencePath:['providers','openai-codex','modelPreferences',body.accountScope]};
  return{ok:true,json:async()=>({status:'switched'})};
 }
 throw Error('unexpected account action '+action);
};
usageReply=async()=>({ok:true,json:async()=>({status:'fresh',rateLimits:{primary:{usedPercent:25}}})});
const multiController={...makeController(),load:async()=>{modelLoads++;if(modelLoadError){modelLoadError=false;throw Error('Signed-in model reload failed')}}};
await render(React.createElement(test.AccountConnections,{controller:multiController,api,namespaces:new Map(),t,disabled:false}));await expandAccounts('ChatGPT/Codex');
assert.ok(document.querySelector('[data-account-scope="account-a"]'),'existing account is listed before another login');
const beforeAdd=apiCalls.length;await click(t('accountAdd'));assert.equal(apiCalls.slice(beforeAdd).filter(call=>call.action==='start').length,1);assert.equal(apiCalls.slice(beforeAdd).some(call=>call.action==='connect'||call.action==='logout'),false,'additional login neither reconnects nor signs out the existing account');assert.match(document.body.textContent,/FIXTURE-CODE/);
modelLoadError=true;
await act(async()=>{await new Promise(resolve=>setTimeout(resolve,3100))});await flush();
assert.equal(document.querySelectorAll('[data-account-scope]').length,2,'completed login displays both saved accounts');
assert.match(document.querySelector('[role=alert]').textContent,/Signed-in model reload failed/,'post-login refresh errors remain visible after the attempt completes');
assert.match(document.querySelector('[data-account-scope="account-b"]').textContent,/Current account/);
const loadsBeforeSwitch=modelLoads;await click(t('accountSwitch'));assert.ok(modelLoads>loadsBeforeSwitch,'switch refreshes the model controller');
assert.equal(apiCalls.filter(call=>call.action==='switch').at(-1).body.accountScope,'account-a');
assert.equal(apiCalls.filter(call=>call.action==='usage').at(-1).body.accountScope,'account-a','usage is requested for the newly active identity');
switchError=true;await click(t('accountSwitch'));assert.match(document.querySelector('[role=alert]').textContent,/Account switch failed/,'failed switch is visible');assert.equal(accountRows[0].accountScope,'account-a');switchError=false;
await render(React.createElement('span',null,'sidebar same-provider account controls'));
await render(React.createElement(test.SidebarAccount,{controller:multiController,t,wide:true}));await act(async()=>document.querySelector('.dshAccountBadge').click());await flush();
assert.equal(document.querySelectorAll('[data-account-scope]').length,2,'statistics dialog exposes both accounts for the selected login method');
await click(t('accountSwitch'));assert.equal(accountRows[0].accountScope,'account-b');assert.equal(apiCalls.filter(call=>call.action==='usage').at(-1).body.accountScope,'account-b');
await click(t('accountAdd'));assert.match(document.body.textContent,/FIXTURE-CODE/,'another account can be authorized directly from the statistics dialog');await click(t('cancel'));assert.equal(document.body.textContent.includes('FIXTURE-CODE'),false);
await render(React.createElement('span',null,'account directory race'));multiController.accounts.dispose();accountActionReply=null;usageReply=null;
const service=test.createAccountDirectory();let resolveProviders,providerReads=0;
providersReply=()=>{providerReads++;return providerReads===1?new Promise(resolve=>resolveProviders=resolve):Promise.resolve({ok:true,json:async()=>({providers:[{id:'new-account'}]})})};
const firstLoad=service.load();service.invalidate();const secondLoad=service.load(true);
resolveProviders({ok:true,json:async()=>({providers:[{id:'stale-account'}]})});await Promise.all([firstLoad,secondLoad]);
assert.equal(service.store.getSnapshot().accounts[0].id,'new-account');assert.equal(providerReads,2);service.dispose();providersReply=null;
await render(React.createElement('span',null,'sidebar account lifecycle'));
const originalModal=primitives.Modal;
primitives.Modal=({open,children,footer,onClose})=>React.createElement('section',{role:'dialog',hidden:!open},children,footer,React.createElement('button',{onClick:onClose},'Fixture close'));
context.window.dispatchEvent=window.dispatchEvent.bind(window);context.CustomEvent=dom.window.CustomEvent;
accountRows=[{id:'openai-codex',name:'ChatGPT/Codex',signedIn:true,accountScope:'sidebar-fixture'}];
usageReply=()=>Promise.resolve({ok:true,json:async()=>freshUsage});
const footerController=makeController(),usageCount=()=>apiCalls.filter(call=>call.action==='usage').length;
const beforeClosed=usageCount();await render(React.createElement(test.SidebarAccount,{controller:footerController,t,wide:true}));
assert.equal(usageCount(),beforeClosed,'a closed usage dialog never mounts its polling panel even if Modal preserves children');
await act(async()=>document.querySelector('.dshAccountBadge').click());await flush();assert.equal(usageCount(),beforeClosed+1);assert.ok(document.querySelector('.dshCodexUsage'));
await act(async()=>[...document.querySelectorAll('button')].find(node=>node.textContent==='Fixture close'&&!node.closest('[hidden]')).click());assert.equal(!!document.querySelector('.dshCodexUsage'),false,'closing the dialog releases usage effects');
await render(React.createElement('span',null,'signed-out footer'));
accountRows=[];const unsigned=makeController();let settingsRequest=null;const requested=event=>{settingsRequest=event.detail};window.addEventListener('dsh-open-settings',requested);
await render(React.createElement(test.SidebarAccount,{controller:unsigned,t,wide:false}));assert.equal(document.querySelector('.dshAccountBadge'),null,'signed-out account is hidden from the sidebar');
window.removeEventListener('dsh-open-settings',requested);await render(null);footerController.accounts.dispose();unsigned.accounts.dispose();primitives.Modal=originalModal;
let sidebar;
const sideWindow={setTimeout,clearTimeout,__ModuleLoader__:{load:def=>{sidebar=def.factory(id=>id==='react'?React:id==='react/jsx-runtime'?jsx:primitives)}}};
vm.runInNewContext(fs.readFileSync(path.join(plugins,'ui-sidebar.js'),'utf8').replace('return module.exports;','exports.SidebarRoot=SidebarRoot;return module.exports;'),{document,window:sideWindow,console,setTimeout,clearTimeout});
for(const collapsed of [false,true]){
 await render(React.createElement(sidebar.SidebarRoot,{key:String(collapsed),collapsed,width:248,startSession:()=>{},toggleSidebar:()=>{},t:key=>key,renderSlot:name=>React.createElement('button',{'data-slot':name},name)}));
 const account=document.querySelector('[data-slot="sidebar.account"]'),settings=document.querySelector('[data-slot="sidebar.settings"]');
 assert.ok(account.closest('.dshSidebarAccount'));assert.ok(account.parentElement.nextElementSibling===settings,'account is immediately above Settings in both sidebar forms');
 if(collapsed)assert.equal(window.getComputedStyle(settings.parentElement).flexDirection,'column','collapsed account and Settings are stacked vertically');
}
usageReply=null;
function Broken(){throw Error('schema fixture failure')};const previousError=console.error;console.error=()=>{};await render(React.createElement(React.Fragment,null,React.createElement('article',{'data-session-body':true},'Durable conversation'),React.createElement(test.ModelEditorBoundary,{t},React.createElement(Broken))));console.error=previousError;assert.match(document.querySelector('[data-session-body]').textContent,/Durable/);assert.match(document.body.textContent,/schema fixture failure/);
assert.ok(document.querySelector('style[data-dsh-model-manager]').textContent.includes('input:focus-visible+.dshModelCheckBox'));
await act(async()=>root.unmount());console.log('PASS React DOM: visible checkboxes; cancel/save; refresh draft preservation; remount persistence; bulk changes; failed write retry; account-switch isolation; read failure retention; search; invalid capacity draft; signed-in account model manager; exact manual model ID add/save/remount/visibility; blank and duplicate rejection; existing-account usage sync and stale read race; exact-provider account deduplication and disconnected fallback; gated free test/enable; local error boundary protects conversation');
}
main().then(()=>require('./model_current_label_dom_harness.cjs').run(moduleRoot)).catch(async error=>{console.error(error);process.exitCode=1;try{await act(async()=>root.unmount())}catch{}dom.window.close()});
