const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), vm = require('node:vm');
const code = fs.readFileSync(path.join(__dirname, '../../web/src/runtime-plugins/client-runtime.js'), 'utf8');
const start = code.indexOf('function createRevisionDraftStore('), end = code.indexOf('exports.createRevisionDraftStore', start);
let fail = false, id = 0;
const disk = new Map();
const storage = { get length() { return disk.size; }, key: index => [...disk.keys()][index], getItem: key => disk.get(key), setItem: (key, value) => { if (fail) throw Error('quota'); disk.set(key, value); }, removeItem: key => disk.delete(key) };
const ctx = {}; vm.runInNewContext(code.slice(start, end), ctx);
const create = () => ctx.createRevisionDraftStore('test', { storage, uid: () => 'token-' + ++id });
const store = create(), other = create();
store.write('a', 'writer-a', { text: 'durable a' }); other.write('a', 'writer-b', { text: 'durable b' });
assert.equal(store.list('a').length, 2);
fail = true; store.write('a', 'writer-a', { text: 'volatile a' });
assert.equal(store.list('a').find(row => row.value.writer === 'writer-a').value.data.text, 'volatile a', 'volatile newest version wins');
assert.equal(create().list('a').find(row => row.value.writer === 'writer-a').value.data.text, 'durable a', 'quota failure leaves durable backup');
const matches = (a, b) => a.text === b.text;
assert.equal(store.complete('a', { text: 'volatile a' }, matches), false);
assert.equal(store.list('a').length, 1, 'volatile completion receipt retires only matched writer in this window');
assert.equal(create().list('a').length, 2, 'failed receipt must not delete durable recovery');
fail = false; store.write('a', 'writer-a', { text: 'saved a' });
assert.equal(store.complete('a', { text: 'saved a' }, matches), true);
assert.equal(create().list('a').length, 1); assert.equal(other.list('a')[0].value.data.text, 'durable b', 'another writer survives cleanup');
other.write('b', 'writer-b', { text: 'separate session' }); assert.equal(other.list('b').length, 1); assert.equal(other.list('a').length, 1);
console.log('PASS immutable drafts: multiwriter isolation, quota fallback, durable receipts and scoped cleanup');
