const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), vm = require('node:vm');
const source = fs.readFileSync(process.env.DSH_RUNTIME_PLUGINS_DIR ? path.join(process.env.DSH_RUNTIME_PLUGINS_DIR, 'ui-conversation.js') : path.join(__dirname, '../../web/dist/plugins/ui-conversation.js'), 'utf8');
const context = { console, AbortController, TextEncoder, TextDecoder, Uint8Array, atob, btoa,
  _deepseek_ai_dsh_client_runtime_client: { createSnapshotStore: value => ({ getSnapshot: () => value, set: next => { value = next; }, subscribe: () => () => {} }) } };
const runtimeSource=fs.readFileSync(path.join(__dirname,'../../web/src/runtime-plugins/client-runtime.js'),'utf8'),tracker={};
vm.runInNewContext(runtimeSource.slice(runtimeSource.indexOf('const activePromptRequests ='),runtimeSource.indexOf('function resolvedClientTimeZone(')),tracker);
Object.assign(context._deepseek_ai_dsh_client_runtime_client,{trackPromptRequest:tracker.trackPromptRequest,pendingPromptRequestIds:tracker.pendingPromptRequestIds,cancelPromptRequests:tracker.cancelPromptRequests});
const helperStart = source.indexOf('function sessionReferenceMention('), helperEnd = source.indexOf('/** Mounts the conversation plugin.', helperStart);
vm.runInNewContext(source.slice(helperStart, helperEnd), context);
const shellStart = source.indexOf('const EMPTY_QUEUE$1'), shellEnd = source.indexOf('//#region lib/types/client/input/hub.js', shellStart);
vm.runInNewContext(source.slice(shellStart, shellEnd), context);
const snapshots = { ids: ['self', 'source-中文', 'duplicate'], byId: { self: { title: 'Current' }, 'source-中文': { title: '标题]\\', cwd: 'E:/工作区' }, duplicate: { title: '标题]\\', cwd: 'E:/other' } } };
const references = context.createSessionReferenceSource({ list: { getSnapshot: () => snapshots } });
(async () => {
const sendStart=source.indexOf('async sendSession('),sendEnd=source.indexOf('\n\t\t\t/**',sendStart);
const sender=vm.runInNewContext('({'+source.slice(sendStart,sendEnd)+'})',{_deepseek_ai_dsh_client_runtime_client:context._deepseek_ai_dsh_client_runtime_client});
let released=0;const attachment={file:{}};
Object.assign(sender,{draftImages:()=>[attachment],serializeImages:async()=>[{type:'image'}],releaseDraftImages:()=>released++});
for(const reply of [{ok:true,value:{accepted:false}},{ok:false,error:{code:'offline',message:'offline'}}]) {
  await assert.rejects(()=>sender.sendSession({prompt:async()=>reply},'draft',['image'],'queue'));
  assert.equal(released,0,'a rejected admission must retain attachment ownership and draft');
}
await sender.sendSession({prompt:async()=>({ok:true,value:{accepted:true}})},'draft',['image'],'queue');assert.equal(released,1);
let completeUpload, dispatched=0;const uploadSession={promptCancelGeneration:0,prompt:async()=>{dispatched++;return{ok:true,value:{accepted:true}}}};
sender.serializeImages=()=>new Promise(resolve=>{completeUpload=resolve});
const uploading=sender.sendSession(uploadSession,'old upload',['image'],'queue');uploadSession.promptCancelGeneration++;
completeUpload([{type:'image'}]);await assert.rejects(()=>uploading,error=>error.code==='cancelled');assert.equal(dispatched,0,'Stop before attachment serialization completes prevents a new request ID from being dispatched');assert.equal(released,1,'a stopped unsent attachment stays available in the draft');
sender.serializeImages=async()=>[{type:'image'}];
const abort = new AbortController(), candidates = await references.candidates({ sessionId: 'self' }, { query: '', signal: abort.signal });
assert.equal(candidates.length, 2); assert.notEqual(candidates[0].name, candidates[1].name, 'duplicate titles have distinct menu identities');
const selected = references.onPick({ candidate: candidates[0] }).insert;
const text = references.codec.serialize(selected.ref, abort.signal);
const encoded = /dsh-session:([A-Za-z0-9_-]+)/.exec(text)[1];
assert.equal(JSON.parse(Buffer.from(encoded, 'base64url').toString('utf8')), 'source-中文', 'reference URI encodes the exact UTF-8 session id');
assert.ok(text.startsWith('@[标题\\]\\\\]('), 'labels escape bracket and backslash with the Host codec');
const subscribers = new Set(), sent = [];
const deps = { queue: { getSnapshot: () => [], subscribe: fn => { subscribers.add(fn); return () => subscribers.delete(fn); } },
  inputTriggers: () => ({ serializeReference: (_source, ref, signal) => references.codec.serialize(ref, signal) }), defaultSink: (...args) => sent.push(args) };
  const shell = new context.SessionInputShell(deps), mirrors = [];
  let triggerModule;
  const triggerSource=fs.readFileSync(path.join(__dirname,'../../web/dist/plugins/ui-input-trigger.js'),'utf8');
  vm.runInNewContext(triggerSource,{AbortController,console,window:{__ModuleLoader__:{load:definition=>{triggerModule=definition.factory(id=>id==='@deepseek-ai/cordis'?{Service:class{}}:id==='@deepseek-ai/dsh-client-runtime/client'?context._deepseek_ai_dsh_client_runtime_client:{})}}}});
  const controller=new triggerModule.InputTriggerController({sessionId:'self',actx:{bail:(_scope,event,request)=>event==='slash/input-insert-reference'&&shell.insertReference(request.reference,request.span)},roster:{all:()=>[references],sources:trigger=>trigger==='@'?[references]:[]}});
  deps.inputTriggers=()=>controller;
  controller.toggleSource('session-reference',{trigger:'@',query:'',position:'leading',span:{start:0,end:0,draftRev:shell.snapshot.draftRev}});
  await new Promise(resolve=>setImmediate(resolve));
  const menu=controller.menu.getSnapshot();
  assert.equal(menu.open,true,'the production trigger menu opens');
  assert.equal(menu.groups[0].status,'ready','the production trigger accepts the async candidate contract');
  assert.equal(menu.groups[0].items.length,2);
  controller.pick('session-reference',0);
  assert.equal(shell.snapshot.occurrences.length,1,'the production menu pick inserts a chip through its scoped event');
  assert.equal(controller.menu.getSnapshot().open,false);
  shell.setDraft('');
  shell.bindMirror(value => mirrors.push(value)); shell.setDraft('Analyze ');
  shell.insertReference(selected, { start: 8, end: 8, draftRev: shell.snapshot.draftRev });
  assert.equal(shell.snapshot.occurrences.length, 1);
  assert.ok(mirrors.at(-1).includes('dsh-session:'), 'persisted drafts contain portable references, never bare placeholders');
  const saved = mirrors.at(-1), restored = new context.SessionInputShell(deps);
  restored.restoreDraft(saved);
  assert.equal(restored.snapshot.occurrences.length, 1, 'reference chips survive shell recreation');
  assert.equal(restored.clipboardDraft(), saved);
  shell.submit('queue'); await new Promise(resolve => setImmediate(resolve));
  const [submitted, images, mode, sourceDraft] = sent.at(-1);
  assert.ok(submitted.includes(text)); assert.equal(mode, 'queue');
  assert.equal(shell.commitAcceptedSend(submitted, images, sourceDraft), true, 'serialized references commit against their captured raw draft');
  assert.equal(shell.snapshot.draft, ''); assert.equal(shell.snapshot.occurrences.length, 0);
  shell.setDraft('  whitespace draft  '); shell.submit();
  const attempt = sent.at(-1);
  assert.equal(attempt[0], 'whitespace draft');
  assert.equal(shell.commitAcceptedSend(attempt[0], attempt[1], attempt[3]), true, 'trimmed ordinary sends also clear after acceptance');
  shell.setDraft('older'); shell.submit(); const earlier = sent.at(-1); shell.setDraft('newer');
  assert.equal(shell.commitAcceptedSend(earlier[0], earlier[1], earlier[3]), false, 'late acceptance preserves text edited while sending');
  assert.equal(shell.snapshot.draft, 'newer');
  let finishReference, referenceSignal;
  const cancelledSends=[];
  const cancellingShell=new context.SessionInputShell({defaultSink:(...args)=>cancelledSends.push(args),inputTriggers:()=>({track(){},serializeReference:(_source,_ref,signal)=>{referenceSignal=signal;return new Promise(resolve=>{finishReference=resolve})}})});
  cancellingShell.setDraft('Before ');cancellingShell.insertReference(selected,{start:7,end:7,draftRev:cancellingShell.snapshot.draftRev});
  const keptDraft=cancellingShell.snapshot.draft;cancellingShell.submit();assert.equal(cancellingShell.snapshot.phase,'submitting');
  cancellingShell.cancelPending();assert.equal(referenceSignal.aborted,true);assert.equal(cancellingShell.snapshot.phase,'plain');assert.equal(cancellingShell.snapshot.draft,keptDraft);
  finishReference(text);await new Promise(resolve=>setImmediate(resolve));assert.equal(cancelledSends.length,0,'late reference serialization cannot revive a stopped send');cancellingShell.dispose();
  shell.dispose(); restored.dispose(); controller.dispose(); assert.equal(subscribers.size, 0);
  for (let i = 0; i < 200; i++) { const transient = new context.SessionInputShell(deps); transient.setDraft('x'.repeat(10000)); transient.dispose(); }
  assert.equal(subscribers.size, 0, 'repeated open/close cannot retain input shells through queue subscriptions');
  console.log('PASS reference input: production InputTriggerController async candidates/pick, native chip codec, UTF-8/escaping, restore, accepted-send clearing, edit race and 200 shell disposals');
})().catch(error => { console.error(error); process.exitCode = 1; });
