const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), vm = require('node:vm');
const modules = process.argv[2] || process.env.DSH_REACT_TEST_MODULES;
const { JSDOM } = require(path.join(modules, 'jsdom'));
const dom = new JSDOM('<main id="root"></main>', { pretendToBeVisual: true, url: 'http://localhost' });
Object.assign(global, { window: dom.window, document: dom.window.document, IS_REACT_ACT_ENVIRONMENT: true });
const React = require(path.join(modules, 'react')), jsx = require(path.join(modules, 'react/jsx-runtime'));
const root = require(path.join(modules, 'react-dom/client')).createRoot(document.getElementById('root'));
const directory = process.env.DSH_RUNTIME_PLUGIN_DIRECTORY || path.resolve(__dirname, '../../web/src/runtime-plugins');
const source = fs.readFileSync(path.join(directory, 'ui-workspace.js'), 'utf8');
const context = { sessionTitle: summary => summary.title || summary.id, assertNever: value => { throw Error(value); } };
let start = source.indexOf('function sessionNode('), end = source.indexOf('\n\t\t/**', start);
vm.runInNewContext(source.slice(start, end), context);
start = source.indexOf('function sessionStatuses('); end = source.indexOf('\n\t\t/**', start);
vm.runInNewContext(source.slice(start, end), context);
const node = reason => context.sessionNode({ id: 'case', completed: true, running: false, projectionValues: { sessionListMetadata: { lastTurnReason: reason } } }, new Map());
const status = (reason, overrides) => context.sessionStatuses({ ...node(reason), ...overrides }, key => key)[0];
for (const reason of ['error', 'aborted', 'interrupted', 'cancelled', 'blocked', 'max-tokens', 'refusal']) assert.notEqual(status(reason).label, 'status.completed', `${reason} must never be presented as successful completion`);
assert.equal(status('error').label, 'status.failed'); assert.equal(status('error').state, 'error');
assert.equal(status('aborted').label, 'status.stopped'); assert.equal(status('aborted').state, 'warning');
assert.equal(status('completed').label, 'status.completed'); assert.equal(status('completed').state, 'done');
assert.equal(status(undefined).label, 'status.ended', 'running → idle without a durable outcome only proves that activity ended');
assert.equal(status(undefined, { completed: false }).label, 'status.idle');
assert.equal(status('error', { running: true }).label, 'status.running', 'a newer live run cannot retain the old failure status');
assert.equal(status('error', { pendingInteraction: 'approval' }).label, 'status.waitingApproval');
const runtimeSource = fs.readFileSync(path.join(directory, 'client-runtime.js'), 'utf8');
const runtime = { console, flattenLineage: rows => rows.map(row => ({ ...row, depth: 0 })) };
start = runtimeSource.indexOf('var Session = class'); end = runtimeSource.indexOf('\n\t\t//#endregion', runtimeSource.indexOf('function workspaceAttachSessionId', start));
vm.runInNewContext(runtimeSource.slice(start, end), runtime);
const manager = Object.create(runtime.SessionManager.prototype);
Object.assign(manager, { summaries: [{ sessionId: 'unopened', running: true, blank: false, updatedAt: 1 }], selected: 'other', sessions: new Map(), projectionStores: new Map(), pendingInteractions: new Map(), completedNotifications: new Set(), prevRunning: new Map([['unopened', true]]), runOutcomes: new Map(), entryCache: new Map(), itemsCache: [], addresses: new Map(), catalogs: new Map(), catalogInflight: new Map(), jobsBySession: new Map(), listState: 'ready', listPhase: 'ready', listError: null, listMutations: null, notifier: { markDirty() {} } });
manager.handleHostEnvelope({ payload: { type: 'host/agent-error', sessionId: 'unopened', message: 'MISSING_CREDENTIAL' } });
manager.handleHostEnvelope({ payload: { type: 'host/session-status', sessionId: 'unopened', running: false } });
assert.equal(manager.buildListSnapshot().items[0].lastTurnReason, 'error', 'a global agent error updates an unopened sidebar row');
manager.handleHostEnvelope({ payload: { type: 'host/session-status', sessionId: 'unopened', running: true } });
assert.equal(manager.buildListSnapshot().items[0].lastTurnReason, undefined, 'starting a new turn clears the previous live failure');

const general = fs.readFileSync(path.join(directory, 'ui-settings-general.js'), 'utf8');
const settingsContext = { react: React, react_jsx_runtime: jsx, window, document, clsx: (...values) => values.filter(Boolean).join(' '), SettingsRoot_module_css_default: {}, ConnectionRecoveryIndicator: () => null,
  SettingsPanel: ({ onClose }) => React.createElement('section', { role: 'dialog' }, React.createElement('button', { onClick: onClose }, 'close')) };
start = general.indexOf('function SettingsRoot('); end = general.indexOf('\n\t\t//#endregion', start);
vm.runInNewContext(general.slice(start, end), settingsContext);
const act = action => React.act(async () => { await action(); });
const rows = [], steps = [];
const render = wide => root.render(React.createElement(settingsContext.SettingsRoot, { wide, reconnect() {}, useConnectionState: select => select('connected'), useSections: select => select(rows), useOnboardingSteps: select => select(steps), useSessions: select => select({ phase: 'ready', byId: {} }), renderSlot: () => null, t: key => key === 'trigger' ? '设置' : key }));
(async () => {
  await act(() => render(false)); const trigger = document.querySelector('button[aria-haspopup=dialog]');
  assert.equal(trigger.getAttribute('aria-label'), '设置'); assert.equal(trigger.title, '设置', 'the collapsed icon-only settings button keeps an accessible name');
  await act(() => trigger.click()); assert.ok(document.querySelector('[role=dialog]'));
  await act(() => document.querySelector('[role=dialog] button').click()); assert.equal(document.activeElement, trigger);
  await act(() => render(true)); assert.equal(document.querySelector('button[aria-haspopup=dialog]').getAttribute('aria-label'), '设置');
  await act(() => root.unmount()); dom.window.close();
  console.log('PASS sidebar outcomes: failed/completed/stopped/blocked/unknown, new-run priority, durable metadata mapping, and named settings trigger with focus return');
})().catch(error => { console.error(error); process.exitCode = 1; dom.window.close(); });
