const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const modules = path.resolve(process.argv[2]);
const { JSDOM } = require(path.join(modules, "jsdom"));
const dom = new JSDOM("<!doctype html><html><head></head><body><main id=\"root\"></main></body></html>", { pretendToBeVisual: true, url: "http://127.0.0.1:58080/" });
Object.assign(global, { window: dom.window, document: dom.window.document, Node: dom.window.Node, HTMLElement: dom.window.HTMLElement, IS_REACT_ACT_ENVIRONMENT: true });
const React = require(path.join(modules, "react"));
const ReactDOM = require(path.join(modules, "react-dom/client"));
const runtimeErrors=[];
window.addEventListener('error',event=>runtimeErrors.push(event.message));
const definitions = {};
window.__ModuleLoader__ = { load: definition => { definitions[definition.id] = definition; } };
vm.runInNewContext(fs.readFileSync(path.resolve(__dirname, "../../release/plugins/dsh-sidebar-workbench-suite/lib/client.js"), "utf8"), { window, document, URL, URLSearchParams, AbortController: dom.window.AbortController, console, setInterval, clearInterval, setTimeout, clearTimeout, fetch: (...args) => global.fetch(...args) });
const registrations = { tabs: [], viewers: [] }, disposed = [];
let updatedTab = null;
const updatedTabs = [];
const sidebar = {
  registerTab(descriptor) { registrations.tabs.push(descriptor); return () => disposed.push("tab:" + descriptor.id); },
  registerFileViewer(descriptor) { registrations.viewers.push(descriptor); return () => disposed.push("viewer:" + descriptor.id); },
  updateTab(id, patch, scope) { updatedTab = { id, patch, scope }; updatedTabs.push(updatedTab); },
  getSnapshot() { return { prefs: { pluginSettings: {} } }; },
  subscribeState() { return () => {}; }
};
const sessions={},connection={};
let cleanup = null;
let root = null;
const settingWrites = [], slotEntries = [];
const computerSnapshot = { status: "ready", writable: true, value: { enabled: false, adapter: "auto", browserHeadless: true, maxBrowserSessions: 4, timeoutSeconds: 60, browserExecutable: "", command: "" } };
const computerScope = { getSnapshot: () => computerSnapshot, subscribe: () => () => {}, set: async (key, value) => { settingWrites.push([key, value]); } };
const settingsScope = { controls:{Switch:({checked,onChange,label,id,disabled})=>React.createElement('button',{id,disabled,role:'switch','aria-label':label,'aria-checked':checked,onClick:()=>onChange(!checked)})}, bind: ({ namespace }) => { assert.equal(namespace, "computer-use"); return computerScope; } };
const slots = { inject: (_name, factory) => factory(), register: (descriptor, component) => { slotEntries.push({ descriptor, component }); return () => {}; } };
const context = {
  betterSidebar: sidebar,
  settingsScope,
  slots,
  get(id) { return { betterSidebar: sidebar, connection, sessions, settingsScope, slots }[id]; },
  effect(factory) { cleanup = factory(); return cleanup; }
};
(async () => {
const plugin = definitions["dsh-sidebar-workbench-suite"].factory(id => id === "react" ? React : id === "@deepseek-ai/dsh-client-ui-primitives" ? {Button:({variant,size,children,...props})=>React.createElement('button',props,children),Menu:({anchor,open,items,onSelect})=>React.createElement('div',null,anchor,open&&React.createElement('div',{role:'menu'},items.map(item=>React.createElement('button',{key:item.id,role:'menuitem',disabled:item.disabled,onClick:()=>onSelect(item.id)},item.label))))} : {});
plugin.apply(context);
assert.deepEqual(registrations.tabs.map(row => row.id), ["suite:jobs", "suite:controlled-browser"]);
assert.deepEqual(registrations.viewers.map(row => row.id), ["suite:markdown", "suite:structured", "suite:office", "suite:code"]);
assert.equal(registrations.viewers[0].priority > registrations.viewers[1].priority, true);
assert.equal(registrations.viewers[0].settings.pluginToggles.length, 2);
assert.equal(slotEntries[0].descriptor.id, "computer-use");
root = ReactDOM.createRoot(document.getElementById("root"));
const h = React.createElement;
const render = async element => { await React.act(async () => { root.render(element); await new Promise(resolve => setTimeout(resolve, 20)); }); };
const click = async element => { assert.ok(element); await React.act(async () => { element.dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true })); await new Promise(resolve => setTimeout(resolve, 20)); }); };
const input = async (element, value) => { assert.ok(element); await React.act(async () => { const propsKey = Object.keys(element).find(key => key.startsWith("__reactProps$")); if (propsKey && typeof element[propsKey].onChange === "function") element[propsKey].onChange({ target: { value } }); else { const prototype = element instanceof dom.window.HTMLTextAreaElement ? dom.window.HTMLTextAreaElement.prototype : dom.window.HTMLInputElement.prototype; Object.getOwnPropertyDescriptor(prototype, "value").set.call(element, value); element.dispatchEvent(new dom.window.Event("input", { bubbles: true })); } await new Promise(resolve => setTimeout(resolve, 20)); }); };
const sourceText = "# Overview\n\n- first\n\nText content.\n";
const fetchRecords = [];
const jobEntries = { parent: [{ id: "job-1", kind: "bash", label: "compile", status: "running", startedAt: 1 }], other: [{ id: "job-1", kind: "bash", label: "other compile", status: "running", startedAt: 2 }] };
const fileBodies = new Map([["README.md", sourceText], ["data.json", '[{"name":"alpha","count":2}]'], ["preview.html", "<button>Preview</button>"], ["main.rs", "fn main() {}"]]);
let fileRevision = 1;const controlModes=new Map(),nativeTargets=new Map();
let computerAdapter="native",captureFailure=false,typeFailure=false,captureInterrupted=false,nativeForeground=true,focusFailure=false,resumeFailure=false;
global.fetch = async (url, options = {}) => {
  let requestBody = null;
  if (options.body) { try { requestBody = JSON.parse(options.body); } catch { requestBody = String(options.body); } }
  fetchRecords.push([String(url), options.method || "GET", requestBody]);
  if (String(url).includes("/__dsh-devices/")) return new Response(JSON.stringify({installed:false,devices:[],website:"https://uuyc.163.com/"}),{status:200,headers:{"Content-Type":"application/json"}});
  if (String(url).includes("__dsh-computer-use/meta")) return new Response(JSON.stringify({ enabled: true, available: true, adapter: computerAdapter, actions:computerAdapter==='native-desktop'?['start','list_windows','focus_window']:['start'], defaultBrowserSessionId: "default" }), { status: 200, headers: { "Content-Type": "application/json" } });
  if (String(url).includes("__dsh-computer-use/action") && requestBody.action==='list_windows') return new Response(JSON.stringify({windows:[{windowId:42,title:'验收编辑器'},{windowId:-1,title:'invalid'}]}),{status:200,headers:{'Content-Type':'application/json'}});
  if (String(url).includes("__dsh-computer-use/action") && captureFailure && requestBody.action==="capture") return new Response(JSON.stringify({error:{code:"COMPUTER_USE_UU_ERROR",message:"远端画面不可用"}}),{status:503,headers:{"Content-Type":"application/json"}});
  if (String(url).includes("__dsh-computer-use/action") && captureInterrupted && requestBody.action==="capture") return new Response(JSON.stringify({error:{code:"COMPUTER_USE_CAPTURE_INTERRUPTED",message:"输入已抢占截图"}}),{status:503,headers:{"Content-Type":"application/json"}});
  if (String(url).includes("__dsh-computer-use/action") && typeFailure && requestBody.action==="type") return new Response(JSON.stringify({error:{message:"输入失败"}}),{status:503,headers:{"Content-Type":"application/json"}});
  if (String(url).includes("__dsh-computer-use/action") && requestBody.action==='focus_window' && focusFailure) return new Response(JSON.stringify({error:{code:'COMPUTER_USE_WINDOW_NOT_FOCUSED',message:'系统未允许聚焦'}}),{status:400,headers:{'Content-Type':'application/json'}});
  if (String(url).includes("__dsh-computer-use/action") && requestBody.action==='resume_agent' && resumeFailure) return new Response(JSON.stringify({error:{code:'COMPUTER_USE_EMERGENCY_STOP_UNAVAILABLE',message:'全局急停快捷键不可用'}}),{status:400,headers:{'Content-Type':'application/json'}});
  if (String(url).includes("__dsh-computer-use/action")) { const owner = requestBody.ownerSessionId;if(requestBody.action==="takeover")controlModes.set(owner,"manual");if(requestBody.action==="resume_agent")controlModes.set(owner,"agent");if(requestBody.action==='focus_window')nativeForeground=true;if(requestBody.action==='start')nativeTargets.set(owner,requestBody.windowId??null); return new Response(JSON.stringify({ control:{mode:controlModes.get(owner)||"agent",generation:0}, state: { controlId:owner+"-control",windowId:nativeTargets.get(owner)??null,foreground:computerAdapter==='native-desktop'?nativeForeground:null,connected:true,interactive:true, url: "https://" + owner + ".test/", title: owner + " browser", viewport: { width: 1280, height: 720 } }, screenshot: { base64: "iVBORw0KGgo=", mediaType: "image/png" } }), { status: 200, headers: { "Content-Type": "application/json" } }); }
  if (String(url).includes("job-list")) { const parsed = new URL(String(url), dom.window.location.href); const owner = parsed.searchParams.get("sessionId"); return new Response(JSON.stringify({ entries: jobEntries[owner] || [] }), { status: 200, headers: { "Content-Type": "application/json" } }); }
  if (String(url).includes("job-read")) { const parsed = new URL(String(url), dom.window.location.href); const owner = parsed.searchParams.get("sessionId"); return new Response(JSON.stringify({ text: owner + " job output", cursor: 10, truncated: false, snapshot: { status: "completed" } }), { status: 200, headers: { "Content-Type": "application/json" } }); }
  if (String(url).includes("job-action")) return new Response(JSON.stringify({ accepted: true }), { status: 200, headers: { "Content-Type": "application/json" } });
  const parsed = new URL(String(url), dom.window.location.href), filePath = parsed.searchParams.get("path") || "README.md";
  if (options.method === "POST") { fileBodies.set(filePath, String(options.body)); fileRevision += 1; return new Response(JSON.stringify({ etag: '"file-' + fileRevision + '"', size: options.body.length }), { status: 200, headers: { "Content-Type": "application/json" } }); }
  return new Response(fileBodies.get(filePath) || "", { status: 200, headers: { etag: '"file-' + fileRevision + '"' } });
};
dom.window.fetch = global.fetch;
const viewerProps = { ctx: context, scope: { sessionId: "parent" }, path: "README.md", title: "README.md", content: sourceText };
await render(h(slotEntries[0].component));
assert.equal(document.querySelectorAll(".dswSuiteSetting").length, 7);
await click(document.querySelector('.dswSuiteSetting [role="switch"]'));
assert.deepEqual(settingWrites[0], ["enabled", true]);
await render(h(registrations.viewers[0].component, viewerProps));
assert.ok(document.querySelector('[aria-label="Markdown 大纲"]'));
assert.equal(document.querySelectorAll(".dswSuiteEditor textarea").length, 1);
await click([...document.querySelectorAll("button")].find(button => button.textContent === "预览"));
assert.equal(document.querySelectorAll(".dswSuiteEditor textarea").length, 0);
await click([...document.querySelectorAll("button")].find(button => button.textContent === "源码"));
const unsavedMarkdown = sourceText + "\nUNSAVED MARKDOWN";
await input(document.querySelector('textarea[aria-label="编辑 README.md"]'), unsavedMarkdown);
await render(h(plugin.test.MermaidDiagram, { source: "flowchart LR\nA[Start] --> B[Done]" }));
await render(h(registrations.viewers[0].component, viewerProps));
assert.equal(document.querySelector('textarea[aria-label="编辑 README.md"]').value, unsavedMarkdown, "Markdown draft must survive viewer remount/move");
await click([...document.querySelectorAll("button")].find(button => button.textContent === "保存"));
fileBodies.set("README.md", "# External after save\n"); fileRevision += 1;
await render(h(plugin.test.MermaidDiagram, { source: "flowchart LR\nA[Start] --> B[Done]" }));
assert.ok(document.querySelector('svg[aria-label="Mermaid flowchart"]'));
await render(h(registrations.viewers[0].component, viewerProps));
assert.equal(document.querySelector('textarea[aria-label="编辑 README.md"]').value, "# External after save\n", "saved drafts must leave the in-memory cache");
await render(h(registrations.viewers[1].component, { ...viewerProps, path: "data.json", title: "data.json", content: '[{"name":"alpha","count":2}]' }));
assert.deepEqual([...document.querySelectorAll("th")].map(node => node.textContent), ["name", "count"]);
assert.match(document.body.textContent, /alpha/);
await render(h(registrations.viewers[3].component, { ...viewerProps, path: "preview.html", title: "preview.html", content: "<button>Preview</button>" }));
await click([...document.querySelectorAll("button")].find(button => button.textContent === "预览"));
assert.equal(document.querySelector("iframe").getAttribute("sandbox"), "allow-scripts");
await render(h(registrations.viewers[3].component, { ...viewerProps, path: "main.rs", title: "main.rs", content: "fn main() {}" }));
assert.ok(document.querySelector('.dswSuiteEditor textarea[aria-label="编辑 main.rs"]'), "switching from previewable HTML to code must restore the editor");
await input(document.querySelector('textarea[aria-label="编辑 main.rs"]'), "fn main() { /* unsaved */ }");
await render(h(registrations.viewers[1].component, { ...viewerProps, path: "data.json", title: "data.json", content: '[{"name":"alpha","count":2}]' }));
await render(h(registrations.viewers[3].component, { ...viewerProps, path: "main.rs", title: "main.rs", content: "fn main() {}" }));
assert.equal(document.querySelector('textarea[aria-label="编辑 main.rs"]').value, "fn main() { /* unsaved */ }", "code draft must survive viewer remount/move");
await render(h(registrations.tabs[0].component, { ctx: context, scope: { sessionId: "parent" }, tab: { id: "jobs" }, visible: true }));
assert.ok(fetchRecords.some(row => row[0].includes("job-list") && row[0].includes("sessionId=parent")), "jobs must come from the owner-scoped Host projection");
await click(document.querySelector(".dswSuiteRow"));
await new Promise(resolve => setTimeout(resolve, 30));
assert.match(document.body.textContent, /parent job output/);
await click([...document.querySelectorAll("button")].find(button => button.textContent === "终止"));
assert.ok(fetchRecords.some(row => row[0].includes("job-action") && row[1] === "POST"));
await render(h(registrations.tabs[0].component, { ctx: context, scope: { sessionId: "other" }, tab: { id: "jobs" }, visible: true }));
assert.doesNotMatch(document.body.textContent, /parent job output/);
await click(document.querySelector(".dswSuiteRow"));
await new Promise(resolve => setTimeout(resolve, 30));
assert.match(document.body.textContent, /other job output/);
await render(h(registrations.tabs[1].component, { ctx: context, scope: { sessionId: "parent" }, tab: { id: "browser", meta: {} }, visible: true, pluginSettings: { autoRefresh: false } }));
assert.ok(fetchRecords.some(row => row[0].includes("__dsh-computer-use/action") && row[1] === "POST"));
assert.equal(document.querySelector('[data-tab="controlled-browser"]').dataset.browserSession, "default");
assert.equal(fetchRecords.find(row => row[0].includes("__dsh-computer-use/action"))[2].browserSessionId, "default");
assert.equal(document.querySelector(".dswSuiteBrowser img").alt, "parent browser");
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='人工接管'));
assert.match(document.body.textContent,/智能体控制暂停/);
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='交还智能体'));
assert.match(document.body.textContent,/智能体可操作/);
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='私密输入'));
assert.equal(document.querySelector('input[aria-label="发送到受控浏览器"]').type,'password');
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='Enter'));
assert.ok(fetchRecords.some(row=>row[2]?.action==='key'&&row[2].keys[0]==='Enter'));
await input(document.querySelector('input[aria-label="受控浏览器地址"]'), "localhost:5173/test");
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='转到'));
assert.ok(fetchRecords.some(row=>row[2]?.action==='navigate'&&row[2]?.url==='http://localhost:5173/test'));

await input(document.querySelector('input[aria-label="发送到受控浏览器"]'), "private browser input");
typeFailure=true;
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='输入'));
assert.equal(document.querySelector('input[aria-label="发送到受控浏览器"]').value, "private browser input", "failed input remains available for an explicit retry");
typeFailure=false;
await render(h(registrations.tabs[1].component, { ctx: context, scope: { sessionId: "other" }, tab: { id: "browser", meta: {} }, visible: true, pluginSettings: { autoRefresh: false } }));
assert.equal(document.querySelector('input[aria-label="发送到受控浏览器"]').value, "");
assert.equal(document.querySelector(".dswSuiteBrowser img").alt, "other browser");
assert.doesNotMatch(document.body.textContent, /parent browser|private browser input/);
registrations.tabs[1].onClose({ meta: { browserSessionId: "default" } }, { sessionId: "other" });
await new Promise(resolve => setTimeout(resolve, 20));
assert.ok(fetchRecords.filter(row => row[0].includes("__dsh-computer-use/action")).length >= 2);
const nativeDraws=[];
window.HTMLCanvasElement.prototype.getContext=function(){return {drawImage:(...args)=>nativeDraws.push(args)}};
window.HTMLElement.prototype.attachEvent=function(){};window.HTMLElement.prototype.detachEvent=function(){};
window.Image=class {constructor(){this.naturalWidth=1280;this.naturalHeight=720;}set src(value){if(value)setTimeout(()=>this.onload?.(),0);}};
computerAdapter="native-desktop";
await render(h(registrations.tabs[1].component, {ctx:context,scope:{sessionId:"desktop"},tab:{id:"desktop",meta:{}},visible:true}));
await React.act(async()=>{await new Promise(resolve=>setTimeout(resolve,25));});
assert.ok(document.querySelector(".dswDesktopCanvas canvas"));
assert.match(document.querySelector('[data-control-scope="local"]').textContent,/操作其他窗口也会暂停智能体/);
assert.ok(nativeDraws.length>0);
assert.equal(document.querySelector(".dswSuiteBrowser img"),null);
assert.equal(document.querySelector('input[aria-label="受控浏览器地址"]'),null);
assert.ok(![...document.querySelectorAll('button')].some(x=>['输入','私密输入','Enter','Tab'].includes(x.textContent)),"native desktop uses the same direct keyboard controls as UU");
const beforeWindowMenu=fetchRecords.length;
await click(document.querySelector('[aria-label="选择本机窗口"]'));
assert.ok(document.querySelector('[role="menu"]'));
assert.doesNotMatch(document.querySelector('[role="menu"]').textContent,/invalid/);
await click([...document.querySelectorAll('[role="menuitem"]')].find(x=>x.textContent==='验收编辑器'));
assert.deepEqual(fetchRecords.slice(beforeWindowMenu).filter(row=>row[2]?.ownerSessionId==='desktop'&&row[2]?.action!=='capture').map(row=>row[2].action),['list_windows'],"choosing a target only reads the window list and updates the local selection");
assert.match(document.body.textContent,/重新连接后切换/);
const beforeWindowReconnect=fetchRecords.length;
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='重新连接'));
const windowReconnect=fetchRecords.slice(beforeWindowReconnect).filter(row=>row[2]?.ownerSessionId==='desktop').map(row=>row[2]);
assert.deepEqual(windowReconnect.map(row=>row.action),['close','start']);
assert.equal(windowReconnect[1].windowId,42,"explicit reconnect passes the selected native windowId only after close");
await React.act(async()=>{await new Promise(resolve=>setTimeout(resolve,25));});
const nativeCanvas=document.querySelector('.dswDesktopCanvas canvas'),nativeKeyboard=document.querySelector('.dswDesktopKeyboard');
nativeCanvas.getBoundingClientRect=()=>({left:0,top:0,width:640,height:360});
nativeForeground=false;
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='刷新画面'));
await React.act(async()=>{await new Promise(resolve=>setTimeout(resolve,25));});
assert.match(document.body.textContent,/目标窗口在后台/);
const beforeActivate=fetchRecords.length;
await React.act(async()=>nativeCanvas.focus());
const activationKey=new dom.window.KeyboardEvent('keydown',{bubbles:true,cancelable:true,key:'a',code:'KeyA'});
await React.act(async()=>{nativeCanvas.dispatchEvent(new dom.window.MouseEvent('pointerdown',{bubbles:true,cancelable:true,button:0,clientX:100,clientY:80}));nativeKeyboard.value='pending input';nativeKeyboard.dispatchEvent(activationKey);nativeCanvas.dispatchEvent(new dom.window.MouseEvent('pointerdown',{bubbles:true,cancelable:true,button:0,clientX:100,clientY:80}));await new Promise(resolve=>setTimeout(resolve,30));});
assert.equal(activationKey.defaultPrevented,true,'keyboard input during activation cannot accumulate in the hidden sink');
assert.equal(nativeKeyboard.value,'');
assert.deepEqual(fetchRecords.slice(beforeActivate).filter(row=>row[2]?.ownerSessionId==='desktop'&&row[2]?.action!=='capture').map(row=>row[2].action),['focus_window'],"first click activates a background window without replaying stale click coordinates or pending keys");
await React.act(async()=>{await new Promise(resolve=>setTimeout(resolve,25));});
assert.match(document.body.textContent,/目标窗口已激活/);
nativeForeground=false;focusFailure=true;
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='刷新画面'));
await React.act(async()=>{nativeCanvas.dispatchEvent(new dom.window.MouseEvent('pointerdown',{bubbles:true,cancelable:true,button:0,clientX:100,clientY:80}));await new Promise(resolve=>setTimeout(resolve,25));});
assert.match(document.body.textContent,/系统未允许聚焦/);
focusFailure=false;
await React.act(async()=>{nativeCanvas.dispatchEvent(new dom.window.MouseEvent('pointerdown',{bubbles:true,cancelable:true,button:0,clientX:100,clientY:80}));await new Promise(resolve=>setTimeout(resolve,25));});
await React.act(async()=>{await new Promise(resolve=>setTimeout(resolve,25));});
assert.match(document.body.textContent,/目标窗口已激活/,'failed activation can be retried without using stale pixels as input');
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='激活窗口'));
await React.act(async()=>{await new Promise(resolve=>setTimeout(resolve,25));});
await React.act(async()=>{nativeCanvas.focus();await new Promise(resolve=>setTimeout(resolve,20));});
assert.equal(document.activeElement,nativeKeyboard,"Tab/focus on the native canvas transfers keyboard focus");
await React.act(async()=>{nativeKeyboard.dispatchEvent(new dom.window.KeyboardEvent('keydown',{bubbles:true,cancelable:true,key:'b',code:'KeyB'}));nativeKeyboard.dispatchEvent(new dom.window.KeyboardEvent('keyup',{bubbles:true,cancelable:true,key:'b',code:'KeyB'}));await new Promise(resolve=>setTimeout(resolve,20));});
assert.deepEqual(fetchRecords.filter(row=>row[2]?.ownerSessionId==='desktop'&&['key_down','key_up'].includes(row[2]?.action)).map(row=>row[2].action),['key_down','key_up']);
assert.ok(fetchRecords.some(row=>row[2]?.ownerSessionId==='desktop'&&row[2]?.action==='key_down'&&row[2].controlId==='desktop-control'&&row[2].includeScreenshot===false));
const beforeNativeWheel=fetchRecords.length;
await React.act(async()=>{nativeCanvas.dispatchEvent(new dom.window.WheelEvent('wheel',{bubbles:true,cancelable:true,clientX:64,clientY:80,deltaY:120}));await new Promise(resolve=>setTimeout(resolve,25));});
const nativeWheelRequests=fetchRecords.slice(beforeNativeWheel).filter(row=>row[2]?.ownerSessionId==='desktop'&&row[2]?.action!=='capture').map(row=>row[2]);
assert.deepEqual(nativeWheelRequests.map(row=>row.action),['scroll'],"native wheel positioning and scrolling use one ordered action");
assert.equal(nativeWheelRequests[0].x,128);assert.equal(nativeWheelRequests[0].y,160);
await React.act(async()=>{nativeKeyboard.dispatchEvent(new dom.window.KeyboardEvent('keydown',{bubbles:true,cancelable:true,key:'Control',code:'ControlLeft'}));await new Promise(resolve=>setTimeout(resolve,20));});
const nativeHandoffStart=fetchRecords.length;
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='人工接管'));
assert.deepEqual(fetchRecords.slice(nativeHandoffStart).filter(row=>row[2]?.ownerSessionId==='desktop').map(row=>row[2].action),['release_inputs','takeover'],"control handoff waits until held keys have been released");
captureInterrupted=true;
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='刷新画面'));
assert.equal(nativeCanvas.style.visibility,'visible',"input preempting a capture must not disconnect the native view");
assert.equal([...document.querySelectorAll('button')].find(x=>x.textContent==='自动刷新').getAttribute('aria-pressed'),'true');
assert.doesNotMatch(document.body.textContent,/输入已抢占截图/);
captureInterrupted=false;
captureFailure=true;
await click([...document.querySelectorAll("button")].find(button=>button.textContent==="刷新画面"));
assert.equal(document.querySelector(".dswSuiteBrowser img"),null,"failed desktop capture must remove stale pixels");
assert.equal(nativeCanvas.style.visibility,'hidden',"failed native capture hides the last canvas frame");
const nativeKeyCount=fetchRecords.filter(row=>row[2]?.ownerSessionId==='desktop'&&row[2]?.action==='key_down').length;
await React.act(async()=>{nativeKeyboard.dispatchEvent(new dom.window.KeyboardEvent('keydown',{bubbles:true,cancelable:true,key:'b',code:'KeyB'}));await new Promise(resolve=>setTimeout(resolve,20));});
assert.equal(fetchRecords.filter(row=>row[2]?.ownerSessionId==='desktop'&&row[2]?.action==='key_down').length,nativeKeyCount,"stale native frames never accept input");
const captureCount=fetchRecords.filter(row=>row[2]?.ownerSessionId==="desktop"&&row[2]?.action==="capture").length;
await React.act(async()=>{await new Promise(resolve=>setTimeout(resolve,650));});
assert.equal(fetchRecords.filter(row=>row[2]?.ownerSessionId==="desktop"&&row[2]?.action==="capture").length,captureCount,"a failed desktop stream must stop polling");
await click([...document.querySelectorAll("button")].find(button=>button.textContent==="关闭会话"));
assert.match(document.body.textContent,/未连接/);
// Exercise the UU canvas independently of the legacy snapshot browser adapter.
captureFailure=false;computerAdapter="uu-desktop";
const sockets=[],decoders=[],draws=[],closedFrames=[];
window.HTMLCanvasElement.prototype.getContext=function(){return {drawImage:(...args)=>draws.push(args)}};
window.HTMLElement.prototype.attachEvent=function(){};window.HTMLElement.prototype.detachEvent=function(){};
window.WebSocket=class { constructor(url){this.url=url;this.closed=false;this.sent=[];sockets.push(this)}send(value){this.sent.push(value)}close(){if(!this.closed){this.closed=true;this.onclose?.()}}message(data){this.onmessage?.({data})}};
window.EncodedVideoChunk=class {constructor(data){Object.assign(this,data)}};
window.VideoDecoder=class {constructor(callbacks){this.callbacks=callbacks;this.state="unconfigured";this.decodeQueueSize=0;decoders.push(this)}configure(config){this.config=config;this.state="configured"}decode(chunk){assert.equal(this.state,"configured");this.callbacks.output({displayWidth:1280,displayHeight:720,close:()=>closedFrames.push(chunk.timestamp)})}close(){assert.notEqual(this.state,"closed","decoder must be closed once");this.state="closed"}};
const tick=async(callback=()=>{})=>React.act(async()=>{callback();await new Promise(resolve=>setTimeout(resolve,25));});
await render(h(registrations.tabs[1].component,{ctx:context,scope:{sessionId:"uu"},tab:{id:"uu",meta:{}},visible:true}));
assert.equal(sockets.length,1);assert.match(sockets[0].url,/ownerSessionId=uu/);
assert.equal(document.querySelector('.dswSuiteBrowser img'),null);
assert.ok(![...document.querySelectorAll('button')].some(x=>['输入','私密输入','Enter','Tab','刷新画面'].includes(x.textContent)),"UU uses direct input, no snapshot toolbar");
const metadata={kind:"state",state:{controlId:"uu-control",connected:true,interactive:true,title:"UU Desktop",emergencyStopShortcut:"Ctrl+Alt+Esc",viewport:{width:1280,height:720}},control:{mode:"manual",generation:10,pauseReason:"escape-hotkey"},codec:"avc1.42C028",width:1280,height:720};
await tick(()=>sockets[0].message(JSON.stringify(metadata)));
assert.match(document.querySelector('[data-control-scope="remote"]').textContent,/Ctrl\+Alt\+Esc/);
assert.match(document.querySelector('[data-control-pause="escape-hotkey"]').textContent,/已触发全局急停快捷键/);
const outsideEscapeStart=fetchRecords.length;
await tick(()=>document.body.dispatchEvent(new dom.window.KeyboardEvent('keydown',{bubbles:true,cancelable:true,key:'Escape',code:'Escape'})));
assert.ok(!fetchRecords.slice(outsideEscapeStart).some(row=>row[2]?.action==='takeover'),'Escape outside the controlled surface must not issue takeover');
const packet=new ArrayBuffer(14);new Uint8Array(packet)[0]=1;new DataView(packet).setBigUint64(1,33333n,true);
await tick(()=>sockets[0].message(packet));
assert.equal(draws.length,1);assert.deepEqual(closedFrames,[33333]);
const canvas=document.querySelector('canvas'),keyboard=document.querySelector('.dswDesktopKeyboard');
canvas.getBoundingClientRect=()=>({left:10,top:20,width:640,height:360});
await tick(()=>canvas.focus());
assert.equal(document.activeElement,keyboard,"Tab/focus on the UU canvas transfers keyboard focus");
await tick(()=>canvas.dispatchEvent(new dom.window.MouseEvent('pointerdown',{bubbles:true,button:2,clientX:330,clientY:200})));
assert.equal(document.activeElement,keyboard);
await tick(()=>keyboard.dispatchEvent(new dom.window.KeyboardEvent('keydown',{bubbles:true,cancelable:true,key:'a',code:'KeyA'})));
await tick(()=>keyboard.dispatchEvent(new dom.window.KeyboardEvent('keyup',{bubbles:true,cancelable:true,key:'a',code:'KeyA'})));
await tick(()=>canvas.dispatchEvent(new dom.window.MouseEvent('pointerup',{bubbles:true,button:2,clientX:350,clientY:210})));
const uuInput=fetchRecords.filter(x=>x[2]?.ownerSessionId==='uu').map(x=>x[2]);
assert.deepEqual(uuInput.filter(x=>['mouse_down','key_down','key_up','mouse_up'].includes(x.action)).map(x=>x.action),['mouse_down','key_down','key_up','mouse_up']);
assert.ok(uuInput.some(x=>x.action==='mouse_down'&&x.button==='right'&&x.x===640&&x.y===360&&x.controlId==='uu-control'&&x.includeScreenshot===false));
assert.ok(uuInput.some(x=>x.action==='key_down'&&x.key==='KeyA'));
assert.match(document.body.textContent,/人工接管中/,'old HTTP mode must not override newer video state');
const wheel=new dom.window.WheelEvent('wheel',{bubbles:true,cancelable:true,clientX:330,clientY:200,deltaY:3,deltaMode:1});
await tick(()=>canvas.dispatchEvent(wheel));
assert.equal(wheel.defaultPrevented,true,"desktop wheel must prevent page scrolling through a non-passive listener");
assert.ok(fetchRecords.some(row=>row[2]?.ownerSessionId==='uu'&&row[2]?.action==='scroll'&&row[2].deltaY===48));
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='100%'));
assert.equal(document.querySelector('.dswDesktopCanvas').dataset.actualSize,'true');
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='适应窗口'));
assert.equal(document.querySelector('.dswDesktopCanvas').dataset.actualSize,undefined);
await tick(()=>canvas.dispatchEvent(new dom.window.MouseEvent('pointerdown',{bubbles:true,button:0,clientX:100,clientY:100})));
const releaseCount=fetchRecords.filter(row=>row[2]?.ownerSessionId==='uu'&&row[2]?.action==='release_inputs').length;
await tick(()=>canvas.dispatchEvent(new dom.window.Event('lostpointercapture',{bubbles:true})));
assert.equal(fetchRecords.filter(row=>row[2]?.ownerSessionId==='uu'&&row[2]?.action==='release_inputs').length,releaseCount+1,"lost drag capture releases the held remote button");
await tick(()=>keyboard.dispatchEvent(new dom.window.KeyboardEvent('keydown',{bubbles:true,cancelable:true,key:'Control',code:'ControlLeft'})));
await tick(()=>window.dispatchEvent(new dom.window.Event('blur')));
assert.ok(fetchRecords.some(x=>x[2]?.ownerSessionId==='uu'&&x[2]?.action==='release_inputs'));
const beforeIme=fetchRecords.length;
const composingKey=new dom.window.KeyboardEvent('keydown',{bubbles:true,cancelable:true,key:'Process',keyCode:229,isComposing:true});
await tick(()=>{keyboard.focus();keyboard.dispatchEvent(new dom.window.CompositionEvent('compositionstart',{bubbles:true}));keyboard.value='中文输入';keyboard.dispatchEvent(composingKey)});
assert.equal(composingKey.defaultPrevented,false,'active IME composition remains available to the browser');
assert.equal(keyboard.value,'中文输入','ordinary composition must not be cleared before commit');
await tick(()=>keyboard.dispatchEvent(new dom.window.CompositionEvent('compositionend',{bubbles:true,data:'中文输入'})));
assert.equal(keyboard.value,'');
assert.deepEqual(fetchRecords.slice(beforeIme).filter(row=>row[2]?.ownerSessionId==='uu'&&row[2]?.action==='type').map(row=>row[2].text),['中文输入']);
const beforeBlurIme=fetchRecords.length;
await tick(()=>{keyboard.dispatchEvent(new dom.window.CompositionEvent('compositionstart',{bubbles:true}));keyboard.value='临时输入';window.dispatchEvent(new dom.window.Event('blur'))});
assert.equal(keyboard.value,'','blur clears both hidden input and composition ownership');
await tick(()=>keyboard.dispatchEvent(new dom.window.CompositionEvent('compositionend',{bubbles:true,data:'失焦后的提交'})));
assert.ok(!fetchRecords.slice(beforeBlurIme).some(row=>row[2]?.ownerSessionId==='uu'&&row[2]?.action==='type'),'a late compositionend must not replay after blur');
const beforePause=fetchRecords.filter(row=>row[2]?.ownerSessionId==='uu'&&row[2]?.action==='key_down').length;
await tick(()=>{keyboard.focus();keyboard.dispatchEvent(new dom.window.CompositionEvent('compositionstart',{bubbles:true}));keyboard.value='暂停前输入'});
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='实时画面'));
assert.equal(sockets[0].closed,true,"pausing the live view closes its media transport");
assert.equal(keyboard.value,'','pausing clears an unfinished composition');
const pausedKey=new dom.window.KeyboardEvent('keydown',{bubbles:true,cancelable:true,key:'a',code:'KeyA'});
await tick(()=>{keyboard.value='blocked';keyboard.dispatchEvent(pausedKey)});
assert.equal(pausedKey.defaultPrevented,true);assert.equal(keyboard.value,'');
assert.equal(fetchRecords.filter(row=>row[2]?.ownerSessionId==='uu'&&row[2]?.action==='key_down').length,beforePause,"paused media never accepts blind keyboard input");
await click([...document.querySelectorAll('button')].find(x=>x.textContent==='实时画面'));
assert.equal(sockets.length,2);
await tick(()=>sockets[1].message(JSON.stringify(metadata)));
await tick(()=>sockets[1].message(packet));
await tick(()=>{keyboard.focus();keyboard.dispatchEvent(new dom.window.CompositionEvent('compositionstart',{bubbles:true}));keyboard.value='断线前输入'});
await tick(()=>{decoders.at(-1).state='closed';decoders.at(-1).callbacks.error(new Error('decode failed'))});
assert.equal(sockets[1].closed,true);assert.equal(canvas.style.visibility,'hidden','decode errors hide stale pixels');
assert.equal(keyboard.value,'','disconnect clears the keyboard sink');
const beforeDisconnectedIme=fetchRecords.length;
await tick(()=>keyboard.dispatchEvent(new dom.window.CompositionEvent('compositionend',{bubbles:true,data:'断线后的提交'})));
assert.ok(!fetchRecords.slice(beforeDisconnectedIme).some(row=>row[2]?.ownerSessionId==='uu'&&row[2]?.action==='type'));
const escape=new dom.window.KeyboardEvent('keydown',{bubbles:true,cancelable:true,key:'Escape',code:'Escape'});
await tick(()=>{keyboard.value='stale';keyboard.dispatchEvent(escape)});
assert.equal(escape.defaultPrevented,true);assert.equal(keyboard.value,'');
assert.ok(fetchRecords.slice(beforeDisconnectedIme).some(row=>row[2]?.ownerSessionId==='uu'&&row[2]?.action==='takeover'),'Escape can release control even while video is unavailable');
assert.ok(!fetchRecords.some(x=>x[2]?.ownerSessionId==='uu'&&x[2]?.action==='capture'),'UU live view never falls back to JPEG polling');
resumeFailure=true;
await click([...document.querySelectorAll('button')].find(button=>button.textContent==='交还智能体'));
assert.match(document.querySelector('[role="alert"]').textContent,/全局急停快捷键不可用/);
assert.ok(document.querySelector('[data-control-pause="emergency-stop-unavailable"]'));
assert.ok([...document.querySelectorAll('button')].some(button=>button.textContent==='交还智能体'),'failed hotkey registration must not show agent ownership');
resumeFailure=false;
await render(h('div',null,'done'));
plugin.test.clearFileDrafts();
const threeMiBInMemory = "x".repeat(1536 * 1024);
assert.equal(plugin.test.rememberFileDraft("oldest", threeMiBInMemory, "", "etag"), true);
assert.equal(plugin.test.rememberFileDraft("middle", threeMiBInMemory, "", "etag"), true);
assert.equal(plugin.test.rememberFileDraft("newest", threeMiBInMemory, "", "etag"), false);
assert.equal(JSON.stringify(plugin.test.fileDraftCacheSnapshot().keys), JSON.stringify(["oldest", "middle"]), "capacity rejection must preserve older unsaved drafts");
assert.equal(plugin.test.rememberFileDraft("oversized", "x".repeat(2 * 1024 * 1024 + 1), "", "etag"), false);
assert.equal(plugin.test.fileDraftCacheSnapshot().keys.includes("oversized"), false, "single drafts over 4 MiB are not cached");
plugin.test.clearFileDrafts();
let pageHidden=false;
Object.defineProperty(document,"hidden",{configurable:true,get:()=>pageHidden});
let polls=0,concurrent=0,peakConcurrent=0;
const stopPolling=plugin.test.visiblePoll(async signal=>{polls++;concurrent++;peakConcurrent=Math.max(peakConcurrent,concurrent);await new Promise(resolve=>setTimeout(resolve,20));concurrent--;return 20},20);
await new Promise(resolve=>setTimeout(resolve,25));
pageHidden=true;document.dispatchEvent(new dom.window.Event("visibilitychange"));
const hiddenPolls=polls;await new Promise(resolve=>setTimeout(resolve,75));assert.equal(polls,hiddenPolls,"hidden pages stop polling");
pageHidden=false;document.dispatchEvent(new dom.window.Event("visibilitychange"));
await new Promise(resolve=>setTimeout(resolve,25));assert.ok(polls>hiddenPolls,"visible pages resume promptly");
stopPolling();const stoppedPolls=polls;await new Promise(resolve=>setTimeout(resolve,75));assert.equal(polls,stoppedPolls);assert.equal(peakConcurrent,1,"poll requests never overlap");
cleanup();
assert.equal(disposed.length, 6);
assert.deepEqual(runtimeErrors,[],"sidebar interactions must not raise browser runtime errors");
await React.act(async () => root.unmount());
dom.window.close();
console.log("PASS companion suite: external registration, Markdown outline/Mermaid, structured data, devices, jobs and disposal");
})().catch(async error => { console.error(error); process.exitCode = 1; await React.act(async()=>root?.unmount()); dom.window.close(); });
