const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), vm = require('node:vm');
const modules = process.argv[2] || process.env.DSH_REACT_TEST_MODULES;
const { JSDOM } = require(path.join(modules, 'jsdom'));
const dom = new JSDOM('<main></main>', { pretendToBeVisual: true, url: 'http://todo-editor.test' });
Object.assign(global, { window: dom.window, document: dom.window.document, IS_REACT_ACT_ENVIRONMENT: true });
const react = require(path.join(modules, 'react')), crypto = require('node:crypto').webcrypto;
const root = require(path.join(modules, 'react-dom/client')).createRoot(document.querySelector('main'));
const runtime = fs.readFileSync(path.join(__dirname, '../../web/src/runtime-plugins/client-runtime.js'), 'utf8');
const begin = runtime.indexOf('function createRevisionDraftStore('), end = runtime.indexOf('exports.createRevisionDraftStore', begin);
const shared = { window, crypto }; vm.runInNewContext(runtime.slice(begin, end), shared);
const source = fs.readFileSync(path.join(__dirname, '../../web/src/runtime-plugins/ui-conversation.js'), 'utf8');
const from = source.indexOf('const todoDrafts ='), to = source.indexOf('/** Dock adapter:', from);
const primitives = new Proxy({ Tooltip: ({ children }) => children }, { get: (value, key) => value[key] || (() => null) });
const ctx = { react, window, crypto, _deepseek_ai_dsh_client_runtime_client: shared, _deepseek_ai_dsh_client_ui_primitives: primitives, TodoPanel_module_css_default: {}, progressLabel: () => '', StatusGlyph: () => null };
vm.runInNewContext(source.slice(from, to), ctx);
let todos = [{ content: 'One\nsecond line', status: 'in_progress' }, { content: 'Two', status: 'pending' }], running = true, child = false, calls = [], stops = 0, pending = [];
const clone = value => JSON.parse(JSON.stringify(value));
const act = fn => react.act(async () => { fn?.(); await new Promise(resolve => setImmediate(resolve)); });
const render = (sessionId = 'session-a') => act(() => root.render(react.createElement(ctx.TodoPanel, { sessionId, todos, t: key => key, useSession: fn => fn({ running, subagent: child ? {} : null }), updateTodos: (expected, action) => { calls.push(clone({ sessionId, expected, action })); return new Promise((resolve, reject) => pending.push({ resolve, reject })); }, cancelTurn: async () => { stops++; }, notify: () => {} })));
const buttons = label => [...document.querySelectorAll('button')].filter(button => button.getAttribute('aria-label') === label || button.textContent === label);
const button = label => { const selected = buttons(label)[0]; assert.ok(selected, label); return selected; };
const click = (label, index = 0) => act(() => { assert.ok(buttons(label)[index], label); buttons(label)[index].click(); });
const textarea = () => document.querySelector('textarea');
const input = value => act(() => { Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype, 'value').set.call(textarea(), value); textarea().dispatchEvent(new window.Event('input', { bubbles: true })); });
const select = value => act(() => { const element = document.querySelector('select'); Object.getOwnPropertyDescriptor(window.HTMLSelectElement.prototype, 'value').set.call(element, value); element.dispatchEvent(new window.Event('change', { bubbles: true })); });
(async () => {
  await render(); await click('todo.title'); await click('todo.edit');
  assert.equal(textarea().value, 'One\nsecond line'); await input('Draft\nmultiline');
  const original = clone(todos); todos = [todos[0], { ...todos[1], status: 'completed' }]; await render();
  assert.equal(textarea().value, 'Draft\nmultiline'); assert.equal(button('todo.save').disabled, true, 'any list change conflicts with the edit-start snapshot');
  await click('todo.save'); assert.equal(calls.length, 0); assert.equal(button('todo.rebase').disabled, true, 'explicit target selection is required');
  await select('0'); await click('todo.rebase'); await click('todo.save');
  assert.deepEqual(calls[0].expected, todos); assert.notDeepEqual(calls[0].expected, original);
  assert.equal(calls[0].action.content, 'Draft\nmultiline'); assert.equal(textarea().disabled, true);
  assert.equal(button('todo.stopTurn').disabled, false, 'save does not disable Stop'); await click('todo.stopTurn'); assert.equal(stops, 1);
  await act(() => pending[0].reject(Error('lost response'))); assert.equal(textarea().value, 'Draft\nmultiline'); assert.equal(textarea().disabled, false);
  todos = []; await render(); assert.equal(textarea().value, 'Draft\nmultiline'); assert.equal(button('todo.save').disabled, true); assert.match(document.body.textContent, /todo.noCurrent/);
  await click('todo.cancelEdit'); await act(() => root.render(null)); await render(); await click('todo.title'); await click('todo.restore');
  assert.equal(textarea().value, 'Draft\nmultiline', 'empty list still exposes persisted drafts');
  todos = [{ content: 'Replacement', status: 'pending' }, { content: 'Other', status: 'pending' }]; await render(); await select('1');
  todos = [todos[1], todos[0]]; await render(); assert.equal(document.querySelector('select').value, '', 'reorder invalidates previous target selection');
  await select('0'); await click('todo.rebase'); await click('todo.save'); assert.equal(calls[1].action.index, 0); assert.deepEqual(calls[1].expected, todos);
  await act(() => pending[1].resolve()); assert.equal(textarea(), null);
  await click('todo.edit'); await input('Old scope draft'); await click('todo.save'); const old = pending[2];
  await render('session-b'); await click('todo.edit'); await input('New scope draft'); await act(() => old.resolve());
  assert.equal(textarea().value, 'New scope draft', 'old response cannot close new editor');
  await render('session-a'); await click('todo.edit'); await input('Later A draft'); await click('todo.save'); const olderA = pending[3];
  await render('session-b'); await render('session-a'); await click('todo.edit'); await input('Newest A draft');
  await act(() => olderA.resolve()); assert.equal(textarea().value, 'Newest A draft', 'A→B→A has a distinct scope generation');
  child = true; await render(); assert.equal(textarea().disabled, true); assert.equal(textarea().value, 'Newest A draft');
  assert.equal(button('todo.save').disabled, true, 'read-only state cannot dispatch edits');
  child = false; await render();
  const setItem = window.Storage.prototype.setItem; window.Storage.prototype.setItem = () => { throw Error('quota'); };
  const count = calls.length; await input('Volatile quota draft'); await click('todo.save'); assert.equal(calls.length, count, 'undurable draft is not submitted');
  assert.match(document.body.textContent, /todo.storageError/); window.Storage.prototype.setItem = setItem;
  await click('todo.save'); assert.equal(calls.length, count + 1); assert.equal(calls.at(-1).action.content, 'Volatile quota draft');
  await act(() => pending.at(-1).resolve());
  await act(() => root.unmount()); dom.window.close();
  console.log('PASS Todo editor: full snapshot CAS, explicit rebase, reorder/removal recovery, multiline drafts, Stop during save, quota protection and late response isolation');
})().catch(error => { console.error(error); process.exitCode = 1; dom.window.close(); });
