const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..'),modules=process.argv[2];
const {JSDOM}=require(path.join(modules,'jsdom'));
const dom=new JSDOM('<main style="transform:translateX(20px);overflow:hidden"></main>',{url:'http://localhost/'});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});
const React=require(path.join(modules,'react')),ReactDOM=require(path.join(modules,'react-dom')),Client=require(path.join(modules,'react-dom/client')),jsx=require(path.join(modules,'react/jsx-runtime'));
const acorn=require(path.join(root,'crates/computer-use/tool-computer-use-command/assets/acorn.cjs'));
const bundlePath=fs.readdirSync(path.join(root,'web/dist/assets')).find(name=>/^index-.*\.js$/.test(name));
const bundle=fs.readFileSync(path.join(root,'web/dist/assets',bundlePath),'utf8');
const builtinName=/ImageLightbox:(\w+)/.exec(bundle)[1],begin=bundle.indexOf(`function ${builtinName}(`);
const builtin=acorn.parseExpressionAt(bundle,begin,{ecmaVersion:'latest'}),lightboxCode=bundle.slice(builtin.start,builtin.end);
// Execute the shipped component, including its body portal and focus lifecycle.
const builtinContext={R:React,ln:ReactDOM,f:jsx,zo:{backdrop:'lightbox',mask:'lightbox-mask',image:'lightbox-image',close:'lightbox-close'},fu:()=>null,window,document,HTMLElement};
vm.runInNewContext(`${lightboxCode};this.Lightbox=${builtinName};`,builtinContext);
const source=fs.readFileSync(path.join(root,'web/src/runtime-plugins/ui-tool.js'),'utf8');
const node=acorn.parseExpressionAt(source,source.indexOf('function ToolImage('),{ecmaVersion:'latest'});
const context={react:React,react_jsx_runtime:jsx,_deepseek_ai_dsh_client_ui_attachment:{ImageLightbox:builtinContext.Lightbox}};
vm.runInNewContext(source.slice(node.start,node.end)+';this.ToolImage=ToolImage;',context);
const mounted=Client.createRoot(document.querySelector('main'));
const attachment={attachmentId:'image-1',name:'图纸.png'};let leases=0,releases=0;
const loadImage=()=>{throw Error('expected lease')};
loadImage.acquire=()=>{leases++;let released=false;const release=()=>{if(!released){released=true;leases--;releases++}};const task=Promise.resolve({url:'blob:fixture',release});task.release=release;return task};
const act=fn=>React.act(async()=>{await fn();await new Promise(resolve=>setImmediate(resolve))});
(async()=>{
 await act(()=>mounted.render(React.createElement(context.ToolImage,{attachment,loadImage,t:key=>key})));
 const opener=document.querySelector('button');opener.focus();await act(()=>opener.click());
 const dialog=document.querySelector('[role=dialog]');assert.equal(dialog.parentElement,document.body,'preview escapes transformed/scrolling tool ancestors');
 assert.equal(dialog.querySelector('img').src,'blob:fixture');assert.equal(document.querySelectorAll('a[target]').length,0);
 const close=dialog.querySelector('button');assert.equal(document.activeElement,close);
 await act(()=>mounted.render(React.createElement(context.ToolImage,{attachment:{...attachment},loadImage,t:key=>key})));
 assert.equal(document.querySelector('[role=dialog]'),dialog,'equivalent history projections keep an open preview and its lease');assert.equal(leases,1);
 await act(()=>window.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape'})));
 assert.equal(document.querySelector('[role=dialog]'),null);assert.equal(document.activeElement,opener);assert.equal(leases,1);
 await act(()=>opener.click());await act(()=>document.querySelector('.lightbox-mask').dispatchEvent(new window.MouseEvent('mousedown',{bubbles:true})));
 assert.equal(document.querySelector('[role=dialog]'),null);assert.equal(document.activeElement,opener);
 await act(()=>opener.click());await act(()=>mounted.unmount());assert.equal(document.querySelector('[role=dialog]'),null);assert.equal(leases,0);assert.equal(releases,1);
 assert.ok(!source.includes('dsh:computer-use-start'),'mounting a historical tool card must not start or open control');
 dom.window.close();console.log('PASS shipped image lightbox: body portal, focus restoration, Escape/backdrop close, lease cleanup and no historical control side effects');
})().catch(error=>{console.error(error);process.exitCode=1;dom.window.close()});
