const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '../../web/src/runtime-plugins/client-runtime.js'), 'utf8');
const start = source.indexOf('var MutableLocationDataStore = class'), end = source.indexOf('//#region lib/types/client/sessions/conversation-assembler.js', start);
const scope = {};
vm.runInNewContext(source.slice(start, end), scope);
const index = new scope.ConversationLocationIndex();
const entries = ['turn/start', 'step/start', 'assistant/message', 'step/end', 'turn/end'].map((type, seq) => ({ event: { type, seq, time: seq, data: { turn: 1, ...type.startsWith('turn/') ? {} : { step: 1 } } } }));
index.rebuild(entries);
const turn = index.snapshot().turns.get(1), step = turn.steps[0];
const stepData = { owner: 'assistant:1:1', data: { kind: 'step', turn: 1, step: 1, key: 'assistant-step', value: { finalNode: { seq: 2, messageId: 'message' } } } };
const tailData = { owner: 'tail:1', data: { kind: 'turn', turn: 1, key: 'turn-tail', value: { closing: stepData.data.value } } };
index.replaceData([stepData]);
index.replaceData([stepData, tailData]);
assert.equal(step.data.get('assistant-step'), stepData.data.value);
assert.equal(turn.data.get('turn-tail'), tailData.data.value, 'step-first publication must retain the turn store read by feedback and file footers');
assert.equal(index.locationOf(entries[0].event).turn.data, turn.data);
index.replaceData([]);
index.applyData([{ owner: tailData.owner, previous: null, next: tailData.data }]);
assert.equal(turn.data.get('turn-tail'), tailData.data.value, 'empty intermediate data cannot orphan the active turn store');
index.rebuild([]); index.replaceData([]);
assert.equal(index.turnDataStores.size, 0); assert.equal(index.stepDataStores.size, 0, 'evicted windows release unused stores');
console.log('PASS turn tail locations: stable stores through staged publication and cleanup after eviction');
