window.__ModuleLoader__.load({id:"dsh-artifacts",factory:require=>{
  const React=require("react"),h=React.createElement;
  const ID="dsh-artifacts";
  const displayPath=value=>globalThis.__DSH_FILE_ACTIONS__?.displayPath(value)??String(value??"").replace(/^\\\\\?\\UNC\\/i,"\\\\").replace(/^\\\\\?\\/,"");
  const labels={created:"新增",modified:"修改",presented:"已交付",deleted:"已移除",active:"运行中",retained:"保留中",candidate:"待交付",interrupted:"运行中断",failed:"失败材料",quarantined:"恢复队列",reclaimed:"已回收"};
  const bytes=n=>n>1073741824?`${(n/1073741824).toFixed(2)} GiB`:n>1048576?`${(n/1048576).toFixed(1)} MiB`:n>1024?`${(n/1024).toFixed(1)} KiB`:`${n||0} B`;
  async function api(operation,args,signal){const response=await fetch(`/__dsh-artifacts/${operation}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(args),signal});const value=await response.json().catch(()=>({message:`HTTP ${response.status}`}));if(!response.ok)throw Error(value.message||`HTTP ${response.status}`);return value}
  function useList(operation,args){
    const [state,setState]=React.useState({entries:[],loading:true,error:""});const [revision,refresh]=React.useReducer(n=>n+1,0);const key=JSON.stringify(args);
    React.useEffect(()=>{const controller=new AbortController();let timer;
      const load=async()=>{try{const value=await api(operation,JSON.parse(key),controller.signal);if(!controller.signal.aborted)setState({...value,loading:false,error:""})}catch(error){if(!controller.signal.aborted)setState(previous=>({...previous,loading:false,error:error.message}))}finally{if(!controller.signal.aborted)timer=setTimeout(load,3000)}};
      void load();return()=>{controller.abort();clearTimeout(timer)};
    },[operation,key,revision]);
    return [state,refresh];
  }
  function ErrorLine({error}){return error?h("p",{role:"alert",className:"dsa-error"},error.message||String(error)):null}
  function ResourceContents({id}){
    const [directory,setDirectory]=React.useState("");const [state]=useList("resource-files",{id,path:directory});const [text,setText]=React.useState(null);const [error,setError]=React.useState("");const reader=React.useRef(null);
    React.useEffect(()=>()=>reader.current?.abort(),[]);
    const open=async entry=>{reader.current?.abort();setError("");setText(null);if(entry.kind==="directory"){setDirectory(entry.path);return}const controller=new AbortController();reader.current=controller;try{const result=await api("resource-read",{id,path:entry.path},controller.signal);if(!controller.signal.aborted)setText(result.text)}catch(error){if(!controller.signal.aborted)setError(error.message)}};
    return h("div",null,directory&&h("button",{type:"button",onClick:()=>{reader.current?.abort();setText(null);setDirectory(directory.split("/").slice(0,-1).join("/"))}},"上一级"),h(ErrorLine,{error:error||state.error||state.warning}),h("ul",{className:"dsa-files"},state.entries.map(entry=>h("li",{key:entry.path},h("button",{type:"button",className:"dsa-file",onClick:()=>void open(entry)},entry.kind==="directory"?"▸ ":"",entry.name,entry.kind==="file"?` · ${bytes(entry.size)}`:"")))),state.truncated&&h("p",null,"目录较大，显示前 500 项"),text!==null&&h("pre",{style:{whiteSpace:"pre-wrap",overflowWrap:"anywhere",maxHeight:360,overflow:"auto"}},text));
  }
  function ResourceFiles({id}){const [open,setOpen]=React.useState(false);return h("div",null,h("button",{type:"button",onClick:()=>setOpen(!open)},open?"收起文件":"查看文件"),open&&h(ResourceContents,{id}));}
  function ResourceList({sessionId,onClose}){
    const [state,refresh]=useList("resources",sessionId?{sessionId}:{});const [error,setError]=React.useState("");const [busy,setBusy]=React.useState(false);
    const action=async(row,action,extra={})=>{setBusy(true);setError("");try{await api("resource-action",{id:row.id,action,...extra});refresh()}catch(error){setError(error.message)}finally{setBusy(false)}};
    const restore=async row=>{setBusy(true);setError("");try{await api("file-action",{sessionId:row.owner,id:row.id,action:"restore"});refresh()}catch(error){setError(error.message)}finally{setBusy(false)}};
    const collect=async()=>{setBusy(true);setError("");try{await api("collect",{});refresh()}catch(error){setError(error.message)}finally{setBusy(false)}};
    const rows=state.entries||[];
    return h("section",{className:"dsa-resources","aria-label":"垃圾槽内容"},h("div",{className:"dsa-bar"},h("strong",null,"垃圾槽"),h("span",null,`${rows.length} 项 · ${bytes(rows.reduce((sum,row)=>sum+row.bytes,0))}`),h("button",{type:"button",disabled:busy,onClick:collect},"清理可回收项"),onClose&&h("button",{type:"button",onClick:onClose},"返回产物")),h(ErrorLine,{error:error||state.error||state.warning}),state.loading&&h("p",null,"正在读取…"),!state.loading&&!rows.length&&h("p",{className:"dsa-empty"},"暂无受管临时材料"),rows.map(row=>h("article",{className:"dsa-resource",key:row.id},h("div",null,h("strong",null,row.label),h("span",{className:"dsa-tag"},row.busy?"正在使用":row.pinned?"固定保留":labels[row.state]||row.state),h("span",null,row.sizePending?"占用统计中":bytes(row.bytes))),h("small",null,row.owner),h("p",{className:"dsa-path",title:displayPath(row.path)},displayPath(row.path)),h(ErrorLine,{error:row.error}),row.state!=="reclaimed"&&h(ResourceFiles,{id:row.id}),h("div",{className:"dsa-actions"},row.state!=="reclaimed"&&h("button",{type:"button",disabled:busy||row.state==="quarantined",onClick:()=>void action(row,"pin",{pinned:!row.pinned})},row.pinned?"取消固定":"固定保留"),row.state==="candidate"&&h("button",{type:"button",disabled:busy||row.busy,onClick:()=>void action(row,"release")},"标记已完成"),row.kind==="trash"&&row.origin?.sha256&&!row.origin.restored&&h("button",{type:"button",disabled:busy||row.busy,onClick:()=>void restore(row)},"恢复原文件"),row.state==="quarantined"?h("button",{type:"button",disabled:busy,onClick:()=>void action(row,"restore")},"恢复临时材料"):row.state!=="reclaimed"&&h("button",{type:"button",disabled:busy||row.busy||row.pinned||row.state==="candidate",onClick:()=>void action(row,"trash")},"移入恢复队列")))));
  }
  function ArtifactView(props){return h(ArtifactSessionView,{...props,key:props.sessionId})}
  function ArtifactSessionView({sessionId,ctx}){
    const [state,refresh]=useList("list",{sessionId});const [garbage,setGarbage]=React.useState(false);const [menu,setMenu]=React.useState(null);const [error,setError]=React.useState("");const [busy,setBusy]=React.useState(false);const [rename,setRename]=React.useState(null);
    React.useEffect(()=>{const close=event=>{if(!event.target.closest?.(".dsa-menu"))setMenu(null)};const key=event=>{if(event.key==="Escape"){setMenu(null);setRename(null)}};document.addEventListener("pointerdown",close);document.addEventListener("keydown",key);return()=>{document.removeEventListener("pointerdown",close);document.removeEventListener("keydown",key)}},[]);
    const open=async(row,intent="preview")=>{setMenu(null);setError("");try{if(intent==="copy"){await navigator.clipboard?.writeText(displayPath(row.path));setError("路径已复制");return}if(intent==="preview"){const sidebar=ctx.get("betterSidebar",false);if(sidebar?.openFile){sidebar.openFile({sessionId},row.path);return}window.open(`/__dsh-preview/file?${new URLSearchParams({sessionId,path:row.path})}`,"_blank","noopener");return}if(intent==="open"&&/\.(docx?|xlsx?|pptx?|wps|et|dps)$/i.test(row.path))intent="office";const response=await fetch("/__dsh-preview/file-action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId,path:row.path,intent})});const value=await response.json().catch(()=>({message:`HTTP ${response.status}`}));if(!response.ok)throw Error(value.message||"无法打开文件")}catch(error){setError(error.message)}};
    const change=async(row,action,newPath)=>{setBusy(true);setMenu(null);setError("");try{await api("file-action",{sessionId,path:row.path,etag:row.etag,action,newPath});setRename(null);refresh()}catch(error){setError(error.message)}finally{setBusy(false)}};
    if(garbage)return h(ResourceList,{key:sessionId,sessionId,onClose:()=>setGarbage(false)});
    return h("section",{className:"dsa-root","aria-label":"产物管理"},h("div",{className:"dsa-bar"},h("strong",null,"产物"),h("span",null,`${state.entries.length} 个文件`),h("button",{type:"button",onClick:refresh},"刷新")),h(ErrorLine,{error:error||state.error||state.warning}),state.truncated&&h("p",{role:"status"},"工作区较大，扫描已达到文件数量上限；工具记录的变更仍会显示。"),state.loading&&h("p",null,"正在读取变更…"),!state.loading&&!state.entries.length&&h("p",{className:"dsa-empty"},"此任务暂未记录文件变更"),h("ul",{className:"dsa-files"},state.entries.map(row=>h("li",{key:row.path,onContextMenu:event=>{event.preventDefault();setMenu({row,x:Math.min(event.clientX,window.innerWidth-205),y:Math.min(event.clientY,window.innerHeight-245)})}},h("button",{type:"button",className:"dsa-file",disabled:row.change==="deleted",onClick:()=>void open(row)},h("span",{className:"dsa-tag","data-change":row.change},labels[row.change]),h("span",{className:"dsa-path",title:displayPath(row.path)},displayPath(row.path)),h("small",null,bytes(row.size))),h("button",{type:"button","aria-label":`管理 ${row.path}`,onClick:event=>{const rect=event.currentTarget.getBoundingClientRect();setMenu({row,x:Math.max(8,Math.min(rect.left,window.innerWidth-205)),y:Math.min(rect.bottom,window.innerHeight-245)})}},"⋯")))),h("footer",{className:"dsa-footer"},h("button",{type:"button",onClick:()=>setGarbage(true)},"查看产生的垃圾列表")),menu&&h("div",{className:"dsa-menu",role:"menu",style:{left:menu.x,top:menu.y}},[["预览","preview"],["复制路径","copy"],["在资源管理器中显示","reveal"],["使用本地工具打开","open"],["在编辑器中打开","editor"]].map(([label,intent])=>h("button",{key:intent,type:"button",role:"menuitem",disabled:menu.row.change==="deleted",onClick:()=>void open(menu.row,intent)},label)),h("button",{type:"button",role:"menuitem",disabled:busy||menu.row.change==="deleted",onClick:()=>{setRename({row:menu.row,path:menu.row.path});setMenu(null)}},"重命名"),h("button",{type:"button",role:"menuitem",disabled:busy||menu.row.change==="deleted",onClick:()=>void change(menu.row,"trash")},"移入垃圾槽")),rename&&h("div",{className:"dsa-dialog",role:"dialog","aria-modal":true,"aria-label":"重命名产物"},h("label",null,"新路径",h("input",{autoFocus:true,value:rename.path,onChange:event=>setRename({...rename,path:event.target.value}),onKeyDown:event=>{if(event.key==="Enter")void change(rename.row,"rename",rename.path)}})),h("button",{type:"button",disabled:busy,onClick:()=>void change(rename.row,"rename",rename.path)},"保存"),h("button",{type:"button",onClick:()=>setRename(null)},"取消")));
  }
  function Settings({scope}){
    const subscribe=React.useCallback(listener=>scope.subscribe(listener),[scope]);const read=React.useCallback(()=>scope.getSnapshot(),[scope]);
    const snapshot=React.useSyncExternalStore(subscribe,read,read);const value=snapshot.value||{};const [show,setShow]=React.useState(false);const [error,setError]=React.useState("");const [location,setLocation]=React.useState(displayPath(value.location||""));
    React.useEffect(()=>setLocation(displayPath(value.location||"")),[value.location]);
    const save=async(key,value)=>{setError("");try{await scope.set(key,value);if(key==="location")await api("resources",{})}catch(error){setError(error.message)}};
    return h("section",{className:"dsa-root"},h("h3",null,"垃圾槽"),h(ErrorLine,{error:error||snapshot.error}),[["enabled","启用垃圾槽"],["autoClean","自动清理"],["reduceContext","减少过程内容进入上下文"]].map(([key,label])=>h("label",{className:"dsa-setting",key},h("span",null,label),h("input",{type:"checkbox",checked:value[key]!==false,onChange:event=>void save(key,event.target.checked)}))),[["keepDays","已结束任务保留天数",7,365],["failedDays","失败材料保留天数",14,365],["recoveryDays","恢复队列保留天数",3,30],["softLimitGib","空间软上限（GiB）",20,4096]].map(([key,label,fallback,max])=>h("label",{className:"dsa-setting",key},h("span",null,label),h("input",{type:"number",min:1,max,defaultValue:value[key]??fallback,key:`${key}:${value[key]}`,onBlur:event=>{const n=Number(event.target.value);if(Number.isInteger(n)&&n>=1&&n<=max)void save(key,n);else setError("请输入有效范围内的整数")}}))),h("details",null,h("summary",null,"高级设置"),h("label",{className:"dsa-setting"},"存储位置",h("input",{value:location,placeholder:"系统管理",onChange:event=>setLocation(event.target.value)})),h("button",{type:"button",onClick:()=>void save("location",location.trim())},"保存位置"),h("p",null,"新运行使用新位置，已有材料继续保留并显示。")),h("button",{type:"button",onClick:()=>setShow(!show)},show?"收起内容":"查看内容"),show&&h(ResourceList,{}));
  }
  function apply(ctx){
    const style=document.createElement("style");style.dataset.plugin=ID;style.textContent=`.dsa-root,.dsa-resources{width:100%;max-width:960px;margin:auto;padding:18px;box-sizing:border-box;color:var(--dsw-alias-label-primary);font-size:14px}.dsa-root button,.dsa-resources button{font:inherit;color:inherit;background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l2);border-radius:7px;padding:6px 10px;cursor:pointer}.dsa-root button:disabled,.dsa-resources button:disabled{opacity:.5;cursor:default}.dsa-bar,.dsa-actions,.dsa-setting{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.dsa-bar{padding-bottom:12px;border-bottom:1px solid var(--dsw-alias-border-l2)}.dsa-bar strong{margin-right:auto}.dsa-files{padding:0;list-style:none}.dsa-files li{display:flex;gap:8px;border-bottom:1px solid var(--dsw-alias-border-l2);padding:8px 0}.dsa-files .dsa-file{display:flex;align-items:center;gap:12px;min-width:0;flex:1;border:0;text-align:left;background:transparent}.dsa-path{overflow-wrap:anywhere;word-break:break-word;min-width:0}.dsa-file .dsa-path{flex:1}.dsa-tag{white-space:nowrap;color:var(--dsw-alias-label-tertiary);font-size:12px}.dsa-tag[data-change=created]{color:var(--dsw-alias-state-success-primary)}.dsa-tag[data-change=modified]{color:var(--dsw-alias-state-business-primary)}.dsa-error{color:var(--dsw-alias-state-error-primary);overflow-wrap:anywhere}.dsa-empty{color:var(--dsw-alias-label-tertiary);padding:32px 0}.dsa-footer{position:sticky;bottom:0;padding:12px 0;background:var(--dsw-alias-bg-layer-1)}.dsa-menu{position:fixed;z-index:10000;width:200px;padding:6px;background:var(--dsw-alias-bg-layer-1,#fff);border:1px solid var(--dsw-alias-border-l2);border-radius:9px;box-shadow:var(--dsw-shadow-lv1)}.dsa-menu button{display:block;width:100%;text-align:left;border:0}.dsa-menu button:hover{background:var(--dsw-alias-interactive-bg-hover)}.dsa-dialog{position:fixed;z-index:10001;left:50%;top:35%;transform:translateX(-50%);width:min(440px,90vw);padding:20px;background:var(--dsw-alias-bg-layer-1,#fff);border:1px solid var(--dsw-alias-border-l2);border-radius:10px;box-shadow:var(--dsw-shadow-lv1)}.dsa-dialog input{display:block;box-sizing:border-box;width:100%;margin:10px 0}.dsa-setting{justify-content:space-between;margin:14px 0}.dsa-setting input{max-width:65%;padding:6px;color:inherit;background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l2);border-radius:6px}.dsa-setting input[type=number]{width:90px}.dsa-resource{padding:14px 0;border-bottom:1px solid var(--dsw-alias-border-l2)}.dsa-resource>div:first-child{display:flex;gap:12px;flex-wrap:wrap}.dsa-resource small{color:var(--dsw-alias-label-tertiary)}.dsa-resource .dsa-path{font-size:12px;color:var(--dsw-alias-label-tertiary)}@media(max-width:650px){.dsa-root,.dsa-resources{padding:10px}.dsa-file{flex-wrap:wrap}.dsa-file .dsa-path{flex-basis:70%}.dsa-actions{gap:6px}.dsa-menu{max-width:calc(100vw - 20px)}}`;
    document.head.appendChild(style);ctx.effect(()=>()=>style.remove());
    const scope=ctx.settingsScope.bind({namespace:"workspace-scratch"});
    ctx.slots.inject("settings.section",()=>ctx.slots.register({name:"settings.section",id:"workspace-scratch",order:80,label:"垃圾槽"},()=>h(Settings,{scope})));
    ctx.slots.inject("conversation.view",()=>ctx.slots.register({name:"conversation.view",id:"artifacts",order:15,label:"产物",inject:sessionId=>({sessionId,ctx})},props=>h(ArtifactView,{...props,key:props.sessionId})));
  }
  return {apply,inject:["slots","settingsScope","connection"],test:{ArtifactView,ResourceList,Settings}};
}});
