import 'package:lucide_icons_flutter/lucide_icons.dart';

import 'icons.dart';

/// Compatibility for integrations still passing Lucide IconData.
/// Keep this adapter named so package updates cannot silently remap glyphs.
final dshIconAssets = <int, String>{
  LucideIcons.alarmClock.codePoint: DshIcons.alarmClock.asset,
  LucideIcons.archive.codePoint: DshIcons.archive.asset,
  LucideIcons.arrowDown.codePoint: DshIcons.arrowDown.asset,
  LucideIcons.arrowLeft.codePoint: DshIcons.arrowLeft.asset,
  LucideIcons.arrowUp.codePoint: DshIcons.arrowUp.asset,
  LucideIcons.bookOpen.codePoint: DshIcons.bookOpen.asset,
  LucideIcons.brain.codePoint: DshIcons.brain.asset,
  LucideIcons.briefcase.codePoint: DshIcons.briefcase.asset,
  LucideIcons.calendarClock.codePoint: DshIcons.calendarClock.asset,
  LucideIcons.check.codePoint: DshIcons.check.asset,
  LucideIcons.chevronDown.codePoint: DshIcons.chevronDown.asset,
  LucideIcons.chevronLeft.codePoint: DshIcons.chevronLeft.asset,
  LucideIcons.chevronRight.codePoint: DshIcons.chevronRight.asset,
  LucideIcons.chevronUp.codePoint: DshIcons.chevronUp.asset,
  LucideIcons.circle.codePoint: DshIcons.circle.asset,
  LucideIcons.circleAlert.codePoint: DshIcons.circleAlert.asset,
  LucideIcons.circleCheck.codePoint: DshIcons.circleCheck.asset,
  LucideIcons.circleHelp.codePoint: DshIcons.circleHelp.asset,
  LucideIcons.circlePlus.codePoint: DshIcons.circlePlus.asset,
  LucideIcons.clock.codePoint: DshIcons.clock.asset,
  LucideIcons.clock3.codePoint: DshIcons.clock3.asset,
  LucideIcons.code.codePoint: DshIcons.code.asset,
  LucideIcons.copy.codePoint: DshIcons.copy.asset,
  LucideIcons.database.codePoint: DshIcons.database.asset,
  LucideIcons.download.codePoint: DshIcons.download.asset,
  LucideIcons.ellipsis.codePoint: DshIcons.ellipsis.asset,
  LucideIcons.eye.codePoint: DshIcons.eye.asset,
  LucideIcons.file.codePoint: DshIcons.file.asset,
  LucideIcons.filePlus.codePoint: DshIcons.filePlus.asset,
  LucideIcons.fileText.codePoint: DshIcons.fileText.asset,
  LucideIcons.files.codePoint: DshIcons.files.asset,
  LucideIcons.folder.codePoint: DshIcons.folder.asset,
  LucideIcons.folderCog.codePoint: DshIcons.folderCog.asset,
  LucideIcons.folderOpen.codePoint: DshIcons.folderOpen.asset,
  LucideIcons.folderPlus.codePoint: DshIcons.folderPlus.asset,
  LucideIcons.gitBranch.codePoint: DshIcons.gitBranch.asset,
  LucideIcons.gitCompareArrows.codePoint: DshIcons.gitCompareArrows.asset,
  LucideIcons.grid2x2.codePoint: DshIcons.grid2x2.asset,
  LucideIcons.history.codePoint: DshIcons.history.asset,
  LucideIcons.image.codePoint: DshIcons.image.asset,
  LucideIcons.inbox.codePoint: DshIcons.inbox.asset,
  LucideIcons.keyboard.codePoint: DshIcons.keyboard.asset,
  LucideIcons.layoutGrid.codePoint: DshIcons.layoutGrid.asset,
  LucideIcons.link.codePoint: DshIcons.link.asset,
  LucideIcons.listChecks.codePoint: DshIcons.listChecks.asset,
  LucideIcons.listFilter.codePoint: DshIcons.listFilter.asset,
  LucideIcons.loaderCircle.codePoint: DshIcons.loaderCircle.asset,
  LucideIcons.maximize.codePoint: DshIcons.maximize.asset,
  LucideIcons.messageCircle.codePoint: DshIcons.messageCircle.asset,
  LucideIcons.mic.codePoint: DshIcons.mic.asset,
  LucideIcons.minus.codePoint: DshIcons.minus.asset,
  LucideIcons.moon.codePoint: DshIcons.moon.asset,
  LucideIcons.panelLeft.codePoint: DshIcons.panelLeft.asset,
  LucideIcons.panelLeftClose.codePoint: DshIcons.panelLeftClose.asset,
  LucideIcons.panelRight.codePoint: DshIcons.panelRight.asset,
  LucideIcons.paperclip.codePoint: DshIcons.paperclip.asset,
  LucideIcons.pause.codePoint: DshIcons.pause.asset,
  LucideIcons.pencil.codePoint: DshIcons.pencil.asset,
  LucideIcons.play.codePoint: DshIcons.play.asset,
  LucideIcons.plus.codePoint: DshIcons.plus.asset,
  LucideIcons.puzzle.codePoint: DshIcons.puzzle.asset,
  LucideIcons.refreshCw.codePoint: DshIcons.refreshCw.asset,
  LucideIcons.rotateCcw.codePoint: DshIcons.rotateCcw.asset,
  LucideIcons.rotateCw.codePoint: DshIcons.rotateCw.asset,
  LucideIcons.search.codePoint: DshIcons.search.asset,
  LucideIcons.searchX.codePoint: DshIcons.searchX.asset,
  LucideIcons.settings.codePoint: DshIcons.settings.asset,
  LucideIcons.shield.codePoint: DshIcons.shield.asset,
  LucideIcons.shieldAlert.codePoint: DshIcons.shieldAlert.asset,
  LucideIcons.shieldCheck.codePoint: DshIcons.shieldCheck.asset,
  LucideIcons.slidersHorizontal.codePoint: DshIcons.slidersHorizontal.asset,
  LucideIcons.square.codePoint: DshIcons.square.asset,
  LucideIcons.squareCheck.codePoint: DshIcons.squareCheck.asset,
  LucideIcons.squareTerminal.codePoint: DshIcons.squareTerminal.asset,
  LucideIcons.sun.codePoint: DshIcons.sun.asset,
  LucideIcons.terminal.codePoint: DshIcons.terminal.asset,
  LucideIcons.thumbsDown.codePoint: DshIcons.thumbsDown.asset,
  LucideIcons.thumbsUp.codePoint: DshIcons.thumbsUp.asset,
  LucideIcons.trash2.codePoint: DshIcons.trash2.asset,
  LucideIcons.unplug.codePoint: DshIcons.unplug.asset,
  LucideIcons.users.codePoint: DshIcons.users.asset,
  LucideIcons.video.codePoint: DshIcons.video.asset,
  LucideIcons.volume2.codePoint: DshIcons.volume2.asset,
  LucideIcons.workflow.codePoint: DshIcons.workflow.asset,
  LucideIcons.wrapText.codePoint: DshIcons.wrapText.asset,
  LucideIcons.wrench.codePoint: DshIcons.wrench.asset,
  LucideIcons.x.codePoint: DshIcons.x.asset,
};

/// Resource names generated from host todo and permission states.
const dshDynamicIconAssets = <String>[
  'assets/icons/todo-pending.svg',
  'assets/icons/todo-in_progress.svg',
  'assets/icons/todo-completed.svg',
  'assets/icons/web-permission-danger-full-access.svg',
  'assets/icons/web-permission-read-only.svg',
  'assets/icons/web-permission-workspace-write.svg',
];
