//! The known session event vocabulary. Rust port of
//! `packages/core/session/src/known-event-types.ts` (generated by the
//! persistence-catalog script in TS; kept verbatim here).

/// Every `SessionEventMap` member declared in the repository — the event
/// vocabulary this build understands. The persistence read path refuses to
/// interpret a log containing a type outside this set unless the event
/// carries the envelope's `ignorable` marker.
pub const KNOWN_SESSION_EVENT_TYPES: [&str; 45] = [
    "agent-preset/selected",
    "agent/inbox/spliced",
    "approval/asked",
    "approval/decided",
    "approval/policy",
    "assistant/chunk",
    "assistant/message",
    "command/done",
    "command/run",
    "compaction/end",
    "compaction/prune",
    "compaction/start",
    "compaction/summary",
    "feedback/record",
    "goal/change",
    "hook/invoked",
    "hook/result",
    "llm/retry",
    "llm/retry-started",
    "model/selection",
    "permission/preset",
    "plan/mode",
    "request/context",
    "request/header",
    "sandbox/mode",
    "schedule/change",
    "session/end-seed",
    "session/title",
    "session/title-llm-request",
    "step/end",
    "step/start",
    "subagent/descriptor",
    "todo/write",
    "tool-workflow/agent-end",
    "tool-workflow/agent-start",
    "tool-workflow/run-end",
    "tool-workflow/run-start",
    "tool/call",
    "tool/code-dispatch",
    "tool/code-dispatch-start",
    "tool/result",
    "turn/end",
    "turn/start",
    "user/message",
    "web/deepseek-search-llm-request",
];

/// Whether a type is in this build's known event vocabulary.
pub fn is_known_session_event_type(type_: &str) -> bool {
    KNOWN_SESSION_EVENT_TYPES.contains(&type_)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_contains_core_types() {
        assert!(is_known_session_event_type("turn/start"));
        assert!(is_known_session_event_type("user/message"));
        assert!(is_known_session_event_type("assistant/chunk"));
        assert!(is_known_session_event_type("session/end-seed"));
        assert!(!is_known_session_event_type("made/up-type"));
        assert!(is_known_session_event_type("model/selection"));
        assert_eq!(KNOWN_SESSION_EVENT_TYPES.len(), 45);
    }

    #[test]
    fn catalog_is_sorted() {
        for window in KNOWN_SESSION_EVENT_TYPES.windows(2) {
            assert!(
                window[0] < window[1],
                "{} must precede {}",
                window[0],
                window[1]
            );
        }
    }
}
