//! Persistent event vocabulary shared by the upstream-compatible session
//! format and the Rust execution extensions.

/// Every `SessionEventMap` member declared in the repository — the event
/// vocabulary this build understands. The persistence read path refuses to
/// interpret a log containing a type outside this set unless the event
/// carries the envelope's `ignorable` marker.
pub const KNOWN_SESSION_EVENT_TYPES: [&str; 71] = [
    "agent-preset/selected",
    "agent/inbox/spliced",
    "approval/asked",
    "approval/decided",
    "approval/policy",
    "assistant/attempt",
    "assistant/chunk",
    "assistant/message",
    "command/done",
    "command/run",
    "compaction/end",
    "compaction/error",
    "compaction/prune",
    "compaction/recovery",
    "compaction/retry",
    "compaction/start",
    "compaction/summary",
    "deliverables/presented",
    "execution/ultra-child",
    "execution/ultra-admitted",
    "execution/ultra-settled",
    "execution/ultra-budget-exhausted",
    "feedback/record",
    "feedback/message-put",
    "feedback/message-delete",
    "goal/change",
    "hook/invoked",
    "hook/result",
    "image/offload",
    "llm/retry",
    "llm/retry-started",
    "model/selection",
    "permission/preset",
    "plan/mode",
    "request/context",
    "request/header",
    "request/phase",
    "sandbox/mode",
    "sandbox/roots-revoked",
    "schedule/change",
    "session-log-deepseek/delivery-accepted",
    "session/end-seed",
    "session/title",
    "session/title-llm-request",
    "step/end",
    "step/start",
    "system/message",
    "subagent/descriptor",
    "subagent/model-selection-policy",
    "team/config",
    "team/member",
    "team/message/cancelled",
    "team/message/delivered",
    "team/message/queued",
    "team/task",
    "todo/write",
    "terminal/permissions-revoked",
    "tool-workflow/agent-end",
    "tool-workflow/agent-start",
    "tool-workflow/run-end",
    "tool-workflow/run-start",
    "tool/call",
    "tool/code-dispatch",
    "tool/code-dispatch-start",
    "tool/result",
    "tools/discovery",
    "turn/end",
    "turn/start",
    "user/message",
    "web/deepseek-search-llm-request",
    "web/hosted-search-request",
];

/// Whether a type is in this build's known event vocabulary.
pub fn is_known_session_event_type(type_: &str) -> bool {
    KNOWN_SESSION_EVENT_TYPES.contains(&type_)
}
